#+TITLE: Desarrollo de una herramienta software para la simulación de sistemas fotovoltaicos con R
#+SUBTITLE: Trabajo de Fin de Grado
#+STARTUP: indent
#+STARTUP: inlineimages 
#+SETUPFILE: config.org
#+OPTIONS: H:3
#+PROPERTY: header-args: :session solaR2 :results output :exports both

* Introducción
*** Objetivo principal
**** Desarrollo de un paquete en =R=
   #+begin_src R :results none
library(solaR2)
   #+end_src

*** Objetivos secundarios
**** GNU Emacs
:PROPERTIES:
:BEAMER_COL: 0.2
:BEAMER_ENV: block
:END:
- =Org mode=
- =ESS=
**** Paquetes de =R=
:PROPERTIES:
:BEAMER_COL: 0.25
:BEAMER_ENV: block
:END:
- =solaR=
- =zoo=
- =data.table=
- =microbenchmark=
- =profvis=
- =lattice=
**** LaTeX
:PROPERTIES:
:BEAMER_COL: 0.2
:BEAMER_ENV: block
:END:
- Documento
- Presentación
**** Energía Solar Fotovoltaica
:PROPERTIES:
:BEAMER_COL: 0.25
:BEAMER_ENV: block
:END:
#+ATTR_LATEX: :width \textwidth
file:../figuras/portadaESF.png

* Estado del arte
** Sitación actual de la generación fotovoltaica
1. En 2022, la energía solar fotovoltaica creció un 137% a nivel mundial.
2. Se instalaron 240 GWp de nueva capacidad, superando los 1185 GWp en total.
3. China lidera con más de 106 GWp instalados, seguido por la Unión Europea con 41 GWp.
4. La energía solar representa el 31% de la capacidad de generación renovable global.
5. Se añadió tres veces más energía solar que eólica en 2022.
6. La Unión Europea superó a EE.UU. en desarrollo fotovoltaico.
7. España lideró el mercado europeo con 8,6 GWp instalados.
8. El Plan REPowerEU busca alcanzar 400 GWp para 2030.
9. España instaló 5.641 MWp en plantas y aumentó el autoconsumo en un 108%.
10. El autoconsumo industrial creció notablemente, representando el 47% del total.
11. Se adjudicaron 1.200 MW a proyectos de hidrógeno verde y agrovoltaica.
12. El sector fotovoltaico aportó 7.014 millones de euros al PIB español y generó 197.383 empleos.
13. España fabrica el 65% de los componentes fotovoltaicos localmente y es un importante exportador.

** Soluciones actuales
*** Soluciones actuales
**** *PVsyst*
:PROPERTIES:
:BEAMER_COL: 0.2
:BEAMER_ENV: block
:END:
#+ATTR_LATEX: :width \textwidth
file:../figuras/Logo-PVsyst.png
**** *SISIFO*
:PROPERTIES:
:BEAMER_COL: 0.2
:BEAMER_ENV: block
:END:
#+ATTR_LATEX: :width \textwidth
file:../figuras/sisifo_naranja_cab2colorpeque1.png
**** *PVGIS*
:PROPERTIES:
:BEAMER_COL: 0.2
:BEAMER_ENV: block
:END:
#+ATTR_LATEX: :width \textwidth
file:../figuras/PVGIS.png
**** *System Advisor Model*
:PROPERTIES:
:BEAMER_COL: 0.2
:BEAMER_ENV: block
:END:
#+ATTR_LATEX: :width \textwidth
file:../figuras/SAM-logo-horizontal.png
*** =solaR=
**** Funcionamiento
- Geometría solar
- Datos meteorológicos
- Radiación en el plano horizontal
- Radiación en el plano del generador
- Simulación de SFCR
- Simulación de SFB
- Optimización de distancias
- Métodos de visualización
*** =solaR=
**** Carencias
- Modularidad
- Eficiencia y rendimiento
- Escalibilidad
- Manipulación de datos
  
* Marco teórico
*** Procedimiento de cálculo
#+ATTR_LATEX: :scale 1
file:../figuras/ProcedimientoCalculoRadiacionInclinada.pdf
* Desarrollo del código
*** Algorítmo de cálculo
#+ATTR_LATEX: :height 0.9\textheight
file:../figuras/procedure.pdf
*** =calcSol=
#+ATTR_LATEX: :width \textwidth
file:../figuras/calcsol.pdf
*** =Meteo=
#+ATTR_LATEX: :width \textwidth
file:../figuras/meteo.pdf
*** =calcG0=
#+ATTR_LATEX: :width \textwidth
file:../figuras/calcg0.pdf
*** =calcGef=
#+ATTR_LATEX: :width \textwidth
file:../figuras/calcgef.pdf
*** =prodGCPV=
#+ATTR_LATEX: :width \textwidth
file:../figuras/prodgcpv.pdf
*** =prodPVPS=
#+ATTR_LATEX: :width \textwidth
file:../figuras/prodpvps.pdf
* Ejemplo práctico de aplicación
*** Información meteorológica
#+begin_src R
etsidi_1315 <- readBDi(file = "TFG/data/PVGIS_1315.csv",
                       lat = 40.4, dates.col = "Dates",
                       format = "%Y-%m-%d %H:%M:%S")
#+end_src
*** Información meteorológica
#+ATTR_LATEX: :height 0.9\textheight
file:../figuras/ejemplos3.pdf
*** Producción de diferentes sistemas
#+begin_src R :exports none
module1 <- list(Vocn = 37.1,
                Iscn = 8.76,
                Vmn = 29.9,
                Imn = 8.37,
                Ncs = 60,
                Ncp = 1,
                CoefVT = 0.00338,
                TONC = 43.7)
module2 <- list(Vocn = 36.5,
                Iscn = 8.15,
                Vmn = 29,
                Imn = 7.59,
                Ncs = 60,
                Ncp = 1,
                CoefVT = 0.0037,
                TONC = 46)
generator1 <- list(Nms = 5, Nmp = 1)
generator2 <- list(Nms = 5, Nmp = 1)
inverter <- list(Ki = c(0.002, 0.005, 0.008),
                 Pinv = 1200,
                 Vmin = 100,
                 Vmax = 320,
                 Gumb = 20)
#+end_src
#+begin_src R
prod1 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
                  dataRad = etsidi_1315, beta = 30, alpha = -19,
                  module = module1, generator = generator1,
                  inverter = inverter)
show(as.data.tableY(prod1))
#+end_src
#+begin_src R
prod2 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
                  dataRad = etsidi_1315, beta = 30, alpha = -19,
                  module = module2, generator = generator2,
                  inverter = inverter)
show(as.data.tableY(prod2))
#+end_src
*** Comparación de producciones
#+ATTR_LATEX: :height 0.9\textheight
[[file:../figuras/ejemplos4.pdf]]
* Conclusiones
** Aportaciones
*** Blame
#+ATTR_LATEX: :height 0.9\textheight
file:../figuras/blame-fCompD.pdf
*** Blame
#+ATTR_LATEX: :width \textwidth
file:../figuras/blame-fCompD_cropped.pdf
*** Insights
#+ATTR_LATEX: :height 0.9\textheight
file:../figuras/contributors.png
** Desarrollo a futuro
*** Desarrollo a futuro
**** Interfaz de usuario
**** Mejora de funciones
**** Toma de datos 
**** Uso de paquete especializados en datos espaciales
- =terra=   
