\chapter{Desarrollo del código}
label:chap:desarrollo-codigo
En la figura [[fig:prod-solar2]], se muestra el proceso de cálculo que sigue el paquete a la hora de obtener la estimación de la producción del sistema fotovoltaico.
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio
#+CAPTION: Proceso de cálculo de las funciones de =solaR2=
#+NAME: fig:prod-solar2
[[file:figuras/procedure.pdf]]
A la hora de estimar la producción, el programa sigue los siguientes procesos:
* Geometría solar.
label:sec:geometria-solar
Para calcular la geometría que definen las posiciones de la Tierra y el Sol, =solaR2= se vale de una función constructora, =calcSol= [ref:subsec:calcsol], la cual mediante las funciones =fSolD= [ref:subsec:fsold] y =fSolI= [ref:subsec:fsoli] cálcula todos los ángulos y componentes que caracterizan la geometría solar.

Como se puede ver en la figura ref:fig:calcSol, =calcSol= funciona gracias a dos funciones:
- =fSolD=: la cual computa la geometría a nivel diario, es decir, los ángulos y componentes que se pueden calcular en cada día independiente.
  estas son:
  - Declinación (\(\delta\)): calculada a partir de la función =declination=[fn:1].
  - Excentricidad (\(\epsilon_o\)): obtenida mediante la función =eccentricity=.
  - Ecuación del tiempo (\(EoT\)): obtenida mediante la función =eot=.
  - Ángulo del amanecer (\(\omega_s\)): calculada a partir de la función =sunrise=.
  - Irradiancia diaria extra-atmosférica (\(B_{0d}(0)\)): obtenida a paritr de la función =bo0d=.
#+begin_src R :exports none :session R
  library(solaR2)
#+end_src
#+begin_src R :session R
  lat <- 40
  BTd <- fBTd()
  fSolD()
#+end_src
- =fSolI=: que calcula la geometría a nivel intradiario, es decir, aquella que se puede calcular en unidades infinitesimas de tiempo.
#+CAPTION: Cálculo de la geometría solar mediante la función =calcSol=, la cual unifica las funciones =fSolD= y =fSolI= resultando en un objeto clase =Sol= el cual contiene toda la información geométrica necesaria para realizar las siguientes estimaciones. label:fig:calcSol
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio
[[file:figuras/calcSol.pdf]]

** Radiación en el plano horizontal.
   1. La información de irradiación en el plano horizontal (en todos sus componentes o, en su defecto, solo la global(\(G_d(0)\))) y temperatura viene dada en un objeto de clase =Meteo=.
   2. Mediante la función fCompD, se calcula:
      - La fracción de radiación difusa diaria (\(F_{Dd}\)).
      - El índice de claridad diario (\(K_{Td}\)).
      - Si solo se tienen datos de la componente global de irradición:
	- La irradiación directa en el plano horizontal (\(B_d(0)\)).
	- La irradiación difusa en el plano horizontal (\(D_d(0)\)).
   3. Mediante la función fCompI, se calcula:
      - La fracción de radiación difusa (\(F_D\)).
      - El índice de claridad (\(K_T\)).
      - Si solo se tienen datos de la componenete global de irradiancia (\(G(0)\)):
	- La irradiancia directa en el plano horizontal (\(B(0)\)).
	- La irradiancia difusa en el plano horizontal (\(D(0)\)).
   4. El resultado de ambas funciones junto a medias mensuales y valores anuales se consolidan en un solo objeto de clase =G0= (que incluye los objetos =Sol= y =Meteo= de los que parte) mediante la función calcG0.
** Radiación en el plano del generador.
   1. La información de radiación puede venir dada en forma de un objeto de clase =Meteo= o un objeto de clase =G0= (ya que es este último el que se necesita para estimar la radiación en el plano del generador).
   2. Mediante la función fTheta, se calcula:
      - Ángulo de inclinación de la superficie del módulo (\(\beta\)).
      - Ángulo azimutal de la superficie del módulo (\(\alpha\) ).
      - Ángulo de incidencia de la irradiancia solar en la superficie del módulo (\(\theta_s\)).
   3. Mediante la función fInclin, se calcula:
      - La irradiancia extra-terrestre en la superficie inclinada (\(B_0(\beta, \alpha)\)).
      - La irradiancia directa normal (\(B(n)\)).
      - Las irradiancias global (\(G(\beta, \alpha)\)), directa (\(B(\beta, \alpha)\)), difusa (\(D(\beta, \alpha)\))(total, isotropica y anisotrópica) y del albedo (\(R(\beta, \alpha)\)) sobre una superficie inclinada.
      - Las irradiancias efectivas global (\(G_{ef}(\beta, \alpha)\)), directa (\(B_{ef}(\beta, \alpha)\)), difusa (\(D_{ef}(\beta, \alpha)\))(total, isotropica y anisotrópica) y del albedo (\(R_{ef}(\beta, \alpha)\)) sobre una superficie inclinada.
      - Los factores de pérdidas angulares para las componentes directa (\(FT\)), difusa (\(FT_D\)), y del albedo (\(FT_R\)).
   4. Mediante la función calcShd, se puede calcular:
      - La irradiancia e irradiación incluyendo sombras para seguidores a dos ejes y horizontales y paneles fijos mediante la función fSombra.  
   5. El resultado de estas funciones junto a medias mensuales y valores anuales se consolidan en un solo objeto de clase =Gef= (que incluye el objeto =G0= del que parte) mediante la función calcGef.
** Producción eléctrica.
   1. Mediante la función fProd, se calcula:
      - La potencia en corriente continua (\(P_{DC}\)).
      - La potencia en corriente alterna (\(P_{AC}\)).
   2. Estos resultados, llevados a valores diarios, mensuales y anuales, se pueden convertir en valores de energía (\(E_{DC}\) y \(E_{AC}\)) y de productividad del sistema (\(Y_f\)), los cuales se consolidan en un solo objeto de clase =ProdGCPV= (que incluye el objeto =Gef= del que parte) mediante la función prodGCPV.

* Footnotes

[fn:1] Todas las funciones mencionadas en este punto, se encuentran en el apartado ref:subsec:utils-angles. 
