#+PROPERTY: header-args:R :results output :exports both
\chapter{Ejemplo práctico de aplicación}
label:chap:ejemplo-practico-aplicacion
Una vez explicado cómo funciona el paquete, se puede realizar una demostración práctica tomando como ejemplo los módulos fotovoltaicos que tiene en su azotea la Escuela Técnica Superior de Ingeniería y Diseño Industrial (en adelante, la ETSIDI).

Se tomará de base un estudio realizado por profesores de la escuela cite:adrada17, en el cual comparan la producción energética de seis tipos de tecnologías fotovoltaicas.

En este ejemplo se realizará el mismo análisis tomando tres herramientas distintas: =solaR=, para poder tomar como referencia el paquete del que sale, apreciando las mejoras del programa. =PVSyst=, ya que es uno de los softwares más usados en el ámbito de la fotovoltaica y puede servir como punto de referencia. Y, por último, =solaR2=.

* =solaR=
label:sec:solaR
Se empieza inicilizando el paquete:
#+begin_src R :session solaR
  library(solaR)
#+end_src

En el estudio anterior, se recopilaron datos intradiarios de irradiación intradiaria. Sin embargo, estos datos fueron tomados en un plano inclinado, por lo que ni =solaR=, ni =solaR2= son capaces de interpretarlos correctamente. En su lugar, para este ejemplo se van a tomar datos horarios de la plataforma =PVGIS= cite:pvgis de los años 2013, 2014 y 2015 en la localización de la ETSIDI.
#+begin_src R :session solaR :results graphics output :file "TFG/figuras/ejemplos1.pdf" :width 8 :height 6
etsidi_1315 <- readBDi(file = 'TFG/data/PVGIS_1315.csv',
                       lat = 40.4, time.col = 'Dates',
                       format = '%Y-%m-%d %H:%M:%S')
xyplot(etsidi_1315)
#+end_src
#+ATTR_LATEX: :width 0.7\textwidth
#+CAPTION: Representación gráfica de un objeto =Meteo= formado con la información meteorológica de la azotea de la ETSIDI entre los años 2013 y 2015 (información horaria).
file:figuras/ejemplos1.pdf

Una vez se tienen estos datos, se puede calcular la producción que van a tener los diferentes sistemas fotovoltaicos.

Para ello, se necesitan los parámetros de los diferentes sistemas. En la tabla ref:tab:parametros-tecnicos-modulos-fotovoltaicos, se pueden ver los distintos parámetros de los módulos fotovoltaicos.
#+begin_export latex
\begin{center}
{\scriptsize }%
\begin{table}[]
{\scriptsize \caption{Parámetros técnicos de diferentes tipos de células solares.\label{tab:parametros-tecnicos-modulos-fotovoltaicos}}}
\centering{}{\scriptsize }\begin{tabular}{>{\centering}m{5cm} *{2}{>{\centering}m{2cm}}}
\toprule 
{\scriptsize \textbf{Parámetros Técnicos}} & {\scriptsize \textbf{mc-Si}} & {\scriptsize \textbf{pc-Si}}\tabularnewline
\midrule
{\scriptsize Potencia se salida (Wp)} & {\scriptsize 250} & {\scriptsize 220}\tabularnewline
{\scriptsize Voltaje en $P_{max}$ (Vmp)} & {\scriptsize 29.9} & {\scriptsize 29.0}\tabularnewline
{\scriptsize Corriente en $P_{max}$ (Imp)} & {\scriptsize 8.37} & {\scriptsize 7.59}\tabularnewline
{\scriptsize Voltaje en circuito abierto (Voc)} & {\scriptsize 37.1} & {\scriptsize 36.5}\tabularnewline
{\scriptsize Corriente en cortocircuito (Isc)} & {\scriptsize 8.76} & {\scriptsize 8.15}\tabularnewline
{\scriptsize Eficiencia del módulo (\%)} & {\scriptsize 15.5} & {\scriptsize 14.4} \tabularnewline
{\scriptsize $\alpha_{Isc}$ (\%/K)} & {\scriptsize 0.0043} & {\scriptsize 0.06} \tabularnewline
{\scriptsize $\beta_{Voc}$ (\%/K)} & {\scriptsize -0.338} & {\scriptsize -0.37}\tabularnewline
{\scriptsize $\gamma_{Pmpp}$ (\%/K)} & {\scriptsize -0.469} & {\scriptsize -0.45}\tabularnewline
{\scriptsize Temperatura NOC (ºC)} & {\scriptsize 43.7} & {\scriptsize 46}\tabularnewline
\bottomrule
\end{tabular}
\end{table}
\end{center}
#+end_export
Se almacena esta información en listas con la información de cada módulo.

#+begin_src R :session solaR
## mc-Si
module1 <- list(Vocn = 37.1,
                Iscn = 8.76,
                Vmn = 29.9,
                Imn = 8.37,
                Ncs = 60,
                Ncp = 1,
                CoefVT = 0.00338,
                TONC = 43.7)
## pc-Si
module2 <- list(Vocn = 36.5,
                Iscn = 8.15,
                Vmn = 29,
                Imn = 7.59,
                Ncs = 60,
                Ncp = 1,
                CoefVT = 0.0037,
                TONC = 46)
#+end_src

Una vez se tiene la información de cada tipo de módulo, en la tabla ref:tab:sistemas-fotovoltaicos se pueden ver la información de la agrupación de cada sistema.
#+begin_export latex
\begin{center}
{\footnotesize }%
\begin{table}[h]
{\scriptsize \caption{Sistemas fotovoltaicos.\label{tab:sistemas-fotovoltaicos}}}
\centering{}{\scriptsize }\begin{tabular}{*{7}{>{\centering}m{1.85cm}}}
\toprule 
{\scriptsize \textbf{Sistema}} & {\scriptsize \textbf{Tecnología}} & {\scriptsize \textbf{Año de Fabricación}} & {\scriptsize \textbf{Módulos en Serie}} & {\scriptsize \textbf{Módulos en Paralelo}} & {\scriptsize \textbf{Potencia del Sistema STC ($Wp_{STC}$)}} & {\scriptsize \textbf{Tamaño ($m^2$)}}\tabularnewline
\midrule
{\scriptsize 1} & {\scriptsize mc-Si} & {\scriptsize 2012} & {\scriptsize 5} & {\scriptsize 1} & {\scriptsize 1250} & {\scriptsize 8}\tabularnewline
{\scriptsize 2} & {\scriptsize pc-Si} & {\scriptsize 2009} & {\scriptsize 5} & {\scriptsize 1} & {\scriptsize 1100} & {\scriptsize 8.2}\tabularnewline
\bottomrule
\end{tabular}
\end{table}
\end{center}
#+end_export
De la misma manera, se almacenará esta información en listas.

#+begin_src R :session solaR
## mc-Si
generator1 <- list(Nms = 5, Nmp = 1)
## pc-Si
generator2 <- list(Nms = 5, Nmp = 1)
#+end_src

Una vez se tienen todos los parámetros del sistema fotovoltaico, se requieren los parámetros del inversor que tienen estos sistemas. Para facilitar el estudio, en el artículo explican que se usa el mismo inversor para todos los sistemas. Los parámetros de este se pueden ver en la tabla ref:tab:caracteristicas-inversor. 
#+begin_export latex
\begin{center}
{\footnotesize }%
\begin{table}
{\scriptsize \caption{Características del inversor.\label{tab:caracteristicas-inversor}}}
\centering{}{\scriptsize }\begin{tabular}{*{2}{>{\centering}m{5cm}}}
\toprule 
{\scriptsize \textbf{Inversor}} & {\scriptsize \textbf{SMA Sunny Boy-1200}} \tabularnewline
\midrule
{\scriptsize Potencia máxima DC} & {\scriptsize 1320 W} \tabularnewline
{\scriptsize Corriente máxima DC} & {\scriptsize 12.6 A} \tabularnewline
{\scriptsize Tensión máxima DC} & {\scriptsize 400 V} \tabularnewline
{\scriptsize Rango de tensión fotovoltaica (mpp)} & {\scriptsize 100-320 V} \tabularnewline
{\scriptsize Potencia máxima DC} & {\scriptsize 1320 W} \tabularnewline
{\scriptsize Potencia nominal de salida} & {\scriptsize 1200 W} \tabularnewline
{\scriptsize Maxima potencia aparente} & {\scriptsize 1200 VA} \tabularnewline
{\scriptsize Corriente máxima AC} & {\scriptsize 6.1 A}\tabularnewline
{\scriptsize Eficiencia} & {\scriptsize 92.1\%} \tabularnewline
\bottomrule
\end{tabular}
\end{table}
\end{center}
#+end_export
#+begin_export latex
\FloatBarrier
#+end_export

Se almacena esta información en otra lista:
#+begin_src R :session solaR
  inverter <- list(Ki = c(0.002, 0.005, 0.008),
                   Pinv = 1200,
		   Vmin = 100,
		   Vmax = 320,
                   Gumb = 20)
#+end_src

Una vez recopilada toda la información (la información que falta se deja sin añadir para que el propio paquete añada sus valores por defecto), se puede calcular la producción que tuvieron los sistemas:

#+begin_src R :session solaR
prod1 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
		  dataRad = etsidi_1315,
		  beta = 30, alfa = -19, 
		  module = module1, generator = generator1,
		  inverter = inverter)
prod2 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
		  dataRad = etsidi_1315,
		  beta = 30, alfa = -19, 
		  module = module2, generator = generator2,
		  inverter = inverter)

#+end_src
#+begin_src R :session solaR
show(as.zooY(prod1))
#+end_src
#+begin_src R :session solaR
show(as.zooY(prod2))
#+end_src
#+begin_src R :session solaR :results graphics :file "TFG/figuras/ejemplos2.pdf" :width 6 :height 4.5
compare(prod1, prod2)
#+end_src
#+ATTR_LATEX: :width 0.7\textwidth
#+CAPTION: Comparación gráfica entre las productividades de los sistemas.
file:figuras/ejemplos2.pdf


* =PVsyst=
Con la herramienta =PVsyst=, se ha generado un año promedio de datos de irradiación en la localización y con estos datos se han obtenido dos informes (uno por cada sistema).

Por comodidad, en este documento se van a extraer solo unas tablas con los resultados principales. Sin embargo, los informes completos están disponibles en el [[https://github.com/solarization/TFG_Francisco_Delgado_Lopez][github]] del documento.

En las tabla ref:tab:pvsyst se tienen los resultados de la simulación de los sistemas.
#+begin_export latex
\begin{center}
{\footnotesize }%
\begin{table}[H]
{\scriptsize \caption{Energía media mensual estimada por \texttt{PVSyst} en $KWh$.\label{tab:pvsyst}}}
\centering{}{\scriptsize }\begin{tabular}{*{3}{>{\centering}m{2cm}}}
\toprule 
{\scriptsize} & {\scriptsize \textbf{$E_{AC}$}} & {\scriptsize \textbf{$Y_f$}}\tabularnewline
\midrule
{\scriptsize \textbf{mc-Si}} & {\scriptsize 1704.2} & {\scriptsize 1363}\tabularnewline
{\scriptsize \textbf{pc-Si}} & {\scriptsize 1464.5} & {\scriptsize 1331}\tabularnewline
\bottomrule
\end{tabular}
\end{table}
\end{center}
#+end_export


* =solaR2=
label:sec:solaR2
Con los datos obtenidos en la sección ref:sec:solaR, hacemos la misma operación pero con el paquete =solaR2=.
#+begin_src R :session solaR :exports none
save(module1, module2, generator1,
     generator2, inverter,
     file = 'TFG/data/ejemplos.RData')
#+end_src
#+begin_src R :session solaR2
library(solaR2)
#+end_src

Para ello importamos de la misma manera los datos de radiación.
#+begin_src R :session solaR2 :results graphics output :file "TFG/figuras/ejemplos3.pdf" :width 8 :height 6
etsidi_1315 <- readBDi(file = 'TFG/data/PVGIS_1315.csv',
                       lat = 40.4, dates.col = 'Dates',
                       format = '%Y-%m-%d %H:%M:%S')
xyplot(etsidi_1315)
#+end_src
#+ATTR_LATEX: :width 0.7\textwidth
#+CAPTION: Representación gráfica de un objeto =Meteo= formado con la información meteorológica de la azotea de la ETSIDI entre los años 2013 y 2015 (horaria).
file:figuras/ejemplos3.pdf
#+begin_src R :session solaR2 :exports none
  load('TFG/data/ejemplos.RData')
#+end_src

Con estos datos se procede al cálculo de la producción (los datos de los componentes del sistema son los mismos que los realizados en la sección ref:sec:solaR).

#+begin_src R :session solaR2
prod1 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
		  dataRad = etsidi_1315,
		  beta = 30, alpha = -19, 
		  module = module1, generator = generator1,
		  inverter = inverter)
prod2 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
		  dataRad = etsidi_1315,
		  beta = 30, alpha = -19, 
		  module = module2, generator = generator2,
		  inverter = inverter)
#+end_src
#+begin_src R :session solaR2
show(as.data.tableY(prod1))
#+end_src
#+begin_src R :session solaR2
show(as.data.tableY(prod2))
#+end_src
#+begin_src R :session solaR2 :results graphics output :file "TFG/figuras/ejemplos4.pdf" :width 6 :height 4.5
compare(prod1, prod2)
#+end_src
#+ATTR_LATEX: :width 0.7\textwidth
#+CAPTION: Comparación gráfica entre las productividades de los sistemas.
file:figuras/ejemplos4.pdf


* Comparación y conclusiones
label:sec:comparacion-conclusiones
Como se puede observar en las secciones anteriores, tanto el paquete =solaR= como el paquete =solaR2= ofrecen los mismos resultados, ya que toman las mismas referencias y estudios para realizar los cáculos. Además, ambos son muy aproximados a los cálculos realizados por =PVSyst=. Sin embargo, el paquete =solaR2=, aparte de la corrección de algunos errores, presenta unas claras ventajas frente a su antecesor. Estas son:
- *Modularidad*: el paquete =solaR2= presenta muchas funciones que son capaces de realizar pequeñas operaciones, al contrario que =solaR=, que no permite esto.
- *Eficiencia*: al estar basado en =data.table=, el paquete gana eficiencia en operaciones complejas. Para mostrar esto vamos a utilizar el paquete =microbenchmark=.
  #+begin_src R :session solaR
  ## Con el paquete solaR
  library(microbenchmark)
  ## se recortan los datos a un solo año
  etsidi_13 <- etsidi_1315[as.Date('2013-01-01'), as.Date('2013-12-31')]
  prodGCPVcustom <- function(){  
    prod1 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
		      dataRad = etsidi_13, beta = 30, alfa =-19,
		      module = module1, generator = generator1,
		      inverter = inverter)
  }
  microbenchmark(prodGCPVcustom(), times = 20)
  #+end_src
  #+begin_src R :session solaR2
  ## Con el paquete solaR2
  library(microbenchmark)
  etsidi_13 <- etsidi_1315[as.Date('2013-01-01'), as.Date('2013-12-31')]
  prodGCPVcustom <- function(){  
    prod1 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
		      dataRad = etsidi_13, beta = 30, alpha =-19,
		      module = module1, generator = generator1,
		      inverter = inverter)
  }
  microbenchmark(prodGCPVcustom(), times = 20)
  #+end_src
  
En los resultados anteriores se pueden ver los tiempos de ejecución que han tenido las expresiones, el tiempo que interesa es =mean= el cual es el tiempo medio de ejecución. Mientras que con =solaR= se tiene un tiempo de ejecución medio de $805 ms$, en =solaR2= es de $533 ms$ representando una notable mejoría.
