#+PROPERTY: header-args: :results output :exports both
\chapter{Ejemplo práctico de aplicación}
label:chap:ejemplo-practico-aplicacion
Una vez explicado como funciona el paquete, se puede realizar una demostración práctica tomando como ejemplo los módulos fotovoltaicos que tiene en su azotea la Escuela Técnica Superior de Ingeniería y Diseño Industrial (en adelante la ETSIDI).

Se tomará de base un estudio realizado por profesores de la escuela cite:adrada17, en el cual, comparan la producción energética de seis tipos de tecnologías fotovoltaicas.

En este ejemplo se realizará el mismo análisis tomando tres herramientas distintas: =solaR=, para poder tomar como referencia el paquete del que sale para poder apreciar las mejoras del programa, =PVSyst=, ya que es uno de los softwares más usados en el ámbito de la fotovoltaica y puede servir como punto de referencia, y por último =solaR2=.

* =solaR=
label:sec:solaR
Se empieza inicilizando el paquete:
#+begin_src R :session solaR
  library(solaR)
#+end_src

En el estudio anterior, se recopilaron datos intradiarios de irradiación los cuales fueron almacenados en archivos.
#+begin_src R :session solaR
enemar13 <- readBDi(file = 'TFG/data/ETSIDI/etsidi/EneMar2013_1.csv',
                    lat = 40.4, time.col = 'Fecha')
show(enemar13)
#+end_src

Una vez se tienen estos datos, se puede calcular la producción que van a tener los diferentes sistemas fotovoltaicos.

Para ello, se necesitan los parámetros de los diferentes sistemas. En la tabla ref:tab:parametros-tecnicos-modulos-fotovoltaicos se pueden ver los distintos parámetros de los módulos fotovoltaicos.
#+begin_export latex
\begin{center}
{\scriptsize }%
\begin{table}[]
{\scriptsize \caption{Parámetros técnicos de diferentes tipos de células solares.\label{tab:parametros-tecnicos-modulos-fotovoltaicos}}}
\centering{}{\scriptsize }\begin{tabular}{>{\centering}m{5cm} *{2}{>{\centering}m{2cm}}}
\toprule 
{\scriptsize \textbf{Parámetros Técnicos}} & {\scriptsize \textbf{mc-Si}} & {\scriptsize \textbf{pc-Si}}\tabularnewline
\midrule
{\scriptsize Potencia se salida (Wp)} & {\scriptsize 250} & {\scriptsize 220}\tabularnewline
{\scriptsize Voltaje en $P_{max}$ (Vmp)} & {\scriptsize 29.9} & {\scriptsize 29.0}\tabularnewline
{\scriptsize Corriente en $P_{max}$ (Imp)} & {\scriptsize 8.37} & {\scriptsize 7.59}\tabularnewline
{\scriptsize Voltaje en circuito abierto (Voc)} & {\scriptsize 37.1} & {\scriptsize 36.5}\tabularnewline
{\scriptsize Corriente en cortocircuito (Isc)} & {\scriptsize 8.76} & {\scriptsize 8.15}\tabularnewline
{\scriptsize Eficiencia del módulo (\%)} & {\scriptsize 15.5} & {\scriptsize 14.4} \tabularnewline
{\scriptsize $\alpha_{Isc}$ (\%/K)} & {\scriptsize 0.0043} & {\scriptsize 0.06} \tabularnewline
{\scriptsize $\beta_{Voc}$ (\%/K)} & {\scriptsize -0.338} & {\scriptsize -0.37}\tabularnewline
{\scriptsize $\gamma_{Pmpp}$ (\%/K)} & {\scriptsize -0.469} & {\scriptsize -0.45}\tabularnewline
{\scriptsize Temperatura NOC (ºC)} & {\scriptsize 43.7} & {\scriptsize 46}\tabularnewline
\bottomrule
\end{tabular}
\end{table}
\end{center}
#+end_export
Se almacena esta información en listas con la información de cada módulo.

#+begin_src R :session solaR
## mc-Si
module1 <- list(Vocn = 37.1,
                Iscn = 8.76,
                Vmn = 29.9,
                Imn = 8.37,
                Ncs = 60,
                Ncp = 1,
                CoefVT = 0.00338,
                TONC = 43.7)
## pc-Si
module2 <- list(Vocn = 36.5,
                Iscn = 8.15,
                Vmn = 29,
                Imn = 7.59,
                Ncs = 60,
                Ncp = 1,
                CoefVT = 0.0037,
                TONC = 46)
#+end_src

Una vez se tiene la información de cada tipo de módulo, en la tabla ref:tab:sistemas-fotovoltaicos se pueden ver la información de la agrupación de cada sistema.
#+begin_export latex
\begin{center}
{\footnotesize }%
\begin{table}
{\scriptsize \caption{Sistemas fotovoltaicos.\label{tab:sistemas-fotovoltaicos}}}
\centering{}{\scriptsize }\begin{tabular}{*{7}{>{\centering}m{1.85cm}}}
\toprule 
{\scriptsize \textbf{Sistema}} & {\scriptsize \textbf{Tecnología}} & {\scriptsize \textbf{Año de Fabricación}} & {\scriptsize \textbf{Módulos en Serie}} & {\scriptsize \textbf{Módulos en Paralelo}} & {\scriptsize \textbf{Potencia del Sistema STC ($Wp_{STC}$)}} & {\scriptsize \textbf{Tamaño ($m^2$)}}\tabularnewline
\midrule
{\scriptsize 1} & {\scriptsize mc-Si} & {\scriptsize 2012} & {\scriptsize 5} & {\scriptsize 1} & {\scriptsize 1250} & {\scriptsize 8}\tabularnewline
{\scriptsize 2} & {\scriptsize pc-Si} & {\scriptsize 2009} & {\scriptsize 5} & {\scriptsize 1} & {\scriptsize 1100} & {\scriptsize 8.2}\tabularnewline
\bottomrule
\end{tabular}
\end{table}
\end{center}
#+end_export
De la misma manera, se almacenará esta información en listas.

#+begin_src R :session solaR
## mc-Si
generator1 <- list(Nms = 5, Nmp = 1)
## pc-Si
generator2 <- list(Nms = 5, Nmp = 1)
#+end_src

Una vez se tienen todos los parémtros del sistema fotovoltaico, se requieren los parámetros del inversor que tienen estos sistemas. Para facilitar el estudio, en el artículo explican que se usa el mismo inversor para todos los sistemas. Los parámetros de este se pueden ver en la tabla ref:tab:caracteristicas-inversor. 
#+begin_export latex
\begin{center}
{\footnotesize }%
\begin{table}
{\scriptsize \caption{Carácteristicas del inversor.\label{tab:caracteristicas-inversor}}}
\centering{}{\scriptsize }\begin{tabular}{*{2}{>{\centering}m{5cm}}}
\toprule 
{\scriptsize \textbf{Inversor}} & {\scriptsize \textbf{SMA Sunny Boy-1200}} \tabularnewline
\midrule
{\scriptsize Potencia máxima DC} & {\scriptsize 1320 W} \tabularnewline
{\scriptsize Corriente máxima DC} & {\scriptsize 12.6 A} \tabularnewline
{\scriptsize Tensión máxima DC} & {\scriptsize 400 V} \tabularnewline
{\scriptsize Rango de tensión fotovoltaica (mpp)} & {\scriptsize 100-320 V} \tabularnewline
{\scriptsize Potencia máxima DC} & {\scriptsize 1320 W} \tabularnewline
{\scriptsize Potencia nominal de salida} & {\scriptsize 1200 W} \tabularnewline
{\scriptsize Maxima potencia aparente} & {\scriptsize 1200 VA} \tabularnewline
{\scriptsize Corriente máxima AC} & {\scriptsize 6.1 A}\tabularnewline
{\scriptsize Eficiencia} & {\scriptsize 92.1\%} \tabularnewline
\bottomrule
\end{tabular}
\end{table}
\end{center}
#+end_export

Se almacena esta información en otra lista:
#+begin_src R :session solaR
  inverter <- list(Pinv = 1200,
		   Vmin = 100,
		   Vmax = 320)
#+end_src

Una vez recopilada toda la información (la información que falta se deja sin añadir para que el propio paquete añada sus valores por defecto), se puede calcular la producción que tuvieron los sistemas:

#+begin_src R :session solaR
prod1 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
		  dataRad = enemar13,
		  beta = 30, alfa = -19, iS = 1,
		  module = module1, generator = generator1,
		  inverter = inverter)
show(prod1)
#+end_src
#+begin_src R :session solaR
prod2 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
		  dataRad = enemar13,
		  beta = 30, alfa = -19, iS = 1,
		  module = module2, generator = generator2,
		  inverter = inverter)
show(prod2)
#+end_src
* =PVsyst=
Con la herramienta =PVsyst=, se ha generado un año promedio de datos de irradiación en la localización y con estos datos se han obtenido dos informes (uno por cada sistema).

Por comodidad, en este documento se van a extraer solo unas tablas con los resultados principales, sin embargo los informes completos están disponibles en el [[https://github.com/solarization/TFG_Francisco_Delgado_Lopez][github]] del documento.

En las tablas ref:tab:pvsyst1 y ref:tab:pvsyst2 se tienen los resultados de la simulación de los sistemas.
#+begin_export latex
\begin{center}
{\footnotesize }%
\begin{table}
{\scriptsize \caption{Energía media mensual estimada por \texttt{PVSyst} en $KWh$ del sistema 1.\label{tab:pvsyst1}}}
\centering{}{\scriptsize }\begin{tabular}{*{13}{>{\centering}m{0.75cm}}}
\toprule 
{\scriptsize \textbf{Ene}} & {\scriptsize \textbf{Feb}} & {\scriptsize \textbf{Mar}} & {\scriptsize \textbf{Abr}} & {\scriptsize \textbf{May}} & {\scriptsize \textbf{Jun}} & {\scriptsize \textbf{Jul}} & {\scriptsize \textbf{Ago}} & {\scriptsize \textbf{Sep}} & {\scriptsize \textbf{Oct}} & {\scriptsize \textbf{Nov}} & {\scriptsize \textbf{Dic}} & {\scriptsize \textbf{Total}}\tabularnewline
\midrule
{\scriptsize 3,7} & {\scriptsize 4,0} & {\scriptsize 5,6} & {\scriptsize 5,3} & {\scriptsize 6,7} & {\scriptsize 6,7} & {\scriptsize 7,9} & {\scriptsize 7,2} & {\scriptsize 6,4} & {\scriptsize 4,8} & {\scriptsize 3,5} & {\scriptsize 3,6} & {\scriptsize 1941,1} \tabularnewline
\bottomrule
\end{tabular}
\end{table}
\end{center}
#+end_export
#+begin_export latex
\begin{center}
{\footnotesize }%
\begin{table}
{\scriptsize \caption{Energía media mensual estimada por \texttt{PVSyst} en $KWh$ del sistema 2.\label{tab:pvsyst2}}}
\centering{}{\scriptsize }\begin{tabular}{*{13}{>{\centering}m{0.75cm}}}
\toprule 
{\scriptsize \textbf{Ene}} & {\scriptsize \textbf{Feb}} & {\scriptsize \textbf{Mar}} & {\scriptsize \textbf{Abr}} & {\scriptsize \textbf{May}} & {\scriptsize \textbf{Jun}} & {\scriptsize \textbf{Jul}} & {\scriptsize \textbf{Ago}} & {\scriptsize \textbf{Sep}} & {\scriptsize \textbf{Oct}} & {\scriptsize \textbf{Nov}} & {\scriptsize \textbf{Dic}} & {\scriptsize \textbf{Total}}\tabularnewline
\midrule
{\scriptsize 4,3} & {\scriptsize 4,6} & {\scriptsize 6,4} & {\scriptsize 6,1} & {\scriptsize 7,3} & {\scriptsize 7,3} & {\scriptsize 8,3} & {\scriptsize 7,7} & {\scriptsize 6,9} & {\scriptsize 5,4} & {\scriptsize 4,1} & {\scriptsize 4,4} & {\scriptsize 2213,7} \tabularnewline
\bottomrule
\end{tabular}
\end{table}
\end{center}
#+end_export



* =solaR2=
label:sec:solaR2
Con los datos obtenidos en la sección ref:sec:solaR, hacemos la misma operación pero con el paquete =solaR2=.
#+begin_src R :session solaR :exports none
  save(module1, module2, generator1,
       generator2, inverter,
       file = 'TFG/data/ejemplos.RData')
#+end_src
#+begin_src R :session solaR2
library(solaR2)
#+end_src

Para ello importamos de la misma manera los datos de radiación.
#+begin_src R :session solaR2
enemar13 <- readBDi(file = 'TFG/data/ETSIDI/etsidi/EneMar2013_1.csv',
                    lat = 40.4, dates.col = 'Fecha')
show(enemar13)
#+end_src
#+begin_src R :session solaR2 :exports none
  load('TFG/data/ejemplos.RData')
#+end_src

Con estos datos se procede al cálculo de la producción (los datos de los componentes del sistema son los mismos que los realizados en la sección ref:sec:solaR).
#+begin_src R :session solaR2
prod1 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
		  dataRad = enemar13,
		  beta = 30, alfa = -19, iS = 1,
		  module = module1, generator = generator1,
		  inverter = inverter)
show(prod1)
#+end_src
#+begin_src R :session solaR2
prod2 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
		  dataRad = enemar13,
		  beta = 30, alfa = -19, iS = 1,
		  module = module2, generator = generator2,
		  inverter = inverter)
show(prod2)
#+end_src

* Comparación y conclusiones
label:sec:comparacion-conclusiones
Como se puede observar en las secciones anteriores, tanto el paquete =solaR= como el paquete =solaR2= ofrecen los mismos resultados ya que toman las mismas referencias y estudios para realizar los cáculos. Sin embargo, el paquete =solaR2=, a parte de la corrección de algunos erores, presenta unas claras ventajas frente a su antecesor. Estas son:
- *Eficiencia*: al estar basado en =data.table=, el paquete gana eficiencia en operaciones complejas. Para mostrar esto vamos a utilizar el paquete =microbenchmark=.
  #+begin_src R :session solaR
  ## Con el paquete solaR
  library(microbenchmark)
  prodGCPVcustom <- function(){  
    prod1 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
		      dataRad = enemar13, beta = 30, alfa =-19,
		      iS = 1, module = module1,
		      generator = generator1, inverter = inverter)
  }
  microbenchmark(prodGCPVcustom(), times = 50)
  #+end_src
  #+begin_src R :session solaR2
  ## Con el paquete solaR2
  library(microbenchmark)
  prodGCPVcustom <- function(){  
    prod1 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'bdI',
		      dataRad = enemar13, beta = 30, alfa =-19,
		      iS = 1, module = module1,
		      generator = generator1, inverter = inverter)
  }
  microbenchmark(prodGCPVcustom(), times = 50)
  #+end_src
  Aquí se puede ver que la eficiencia mejora. Sin embargo, suponiendo que en vez de un sistema fijo, tuvieramos un sistema de seguimiento de doble eje y quisieramos optener la mejor combinación de distancias, se podría utilizar la función =optimShd=, la cual al ser una tarea muy exigente se aprecia con más detalle las virtudes del paquete =solaR2= gracias al uso de =data.table=.
  #+begin_src R :session solaR
  ## Con el paquete solaR
  struct2x <- list(W = 23.11, L = 9.8, Nrow = 2, Ncol = 3)
  dist2x <- list(Lew = c(30, 45),Lns = c(20, 40))
  optimShdcustom <- function(){  
    optim <- optimShd(lat = 40.4, modeTrk = 'two', modeRad = 'bdI',
		      dataRad = enemar13, beta = 30, alfa =-19,
		      iS = 1, module = module1,
		      generator = generator1, inverter = inverter,
		      modeShd = c('area', 'prom'),
		      distances = dist2x, struct = struct2x,
		      res = 5, prog = FALSE)
  }
  microbenchmark(optimShdcustom(), times = 20)
  #+end_src
  #+begin_src R :session solaR2
  ## Con el paquete solaR2
  struct2x <- list(W = 23.11, L = 9.8, Nrow = 2, Ncol = 3)
  dist2x <- list(Lew = c(30, 45),Lns = c(20, 40))
  optimShdcustom <- function(){  
    optim <- optimShd(lat = 40.4, modeTrk = 'two', modeRad = 'bdI',
		      dataRad = enemar13, beta = 30, alfa =-19,
		      iS = 1, module = module1,
		      generator = generator1, inverter = inverter,
		      modeShd = c('area', 'prom'),
		      distances = dist2x, struct = struct2x,
		      res = 5, prog = FALSE)
  }
  microbenchmark(optimShdcustom(), times = 20)
  #+end_src
  
