#+PROPERTY: header-args: :results output :exports both
\chapter{Ejemplo práctico de aplicación}
label:chap:ejemplo-practico-aplicacion
Una vez explicado como funciona el paquete, se puede realizar una demostración práctica tomando como ejemplo los módulos fotovoltaicos que tiene en su azotea la Escuela Técnica Superior de Ingeniería y Diseño Industrial (en adelante la ETSIDI).

Se tomará de base un estudio realizado por profesores de la escuela cite:adrada17, en el cual, comparan la producción energética de seis tipos de tecnologías fotovoltaicas.

En este ejemplo se realizará el mismo análisis tomando tres herramientas distintas: =solaR=, para poder tomar como referencia el paquete del que sale para poder apreciar las mejoras del programa, =PVSyst=, ya que es uno de los softwares más usados en el ámbito de la fotovoltaica y puede servir como punto de referencia, y por último =solaR2=.

* =solaR=
label:sec:solaR
Se empieza inicilizando el paquete:
#+begin_src R :session solaR
  library(solaR)
#+end_src

En el estudio anterior, se recopilaron datos intradiarios de irradiación



Una vez se tienen estos datos, se puede calcular la producción que van a tener los diferentes sistemas fotovoltaicos.

Para ello, se necesitan los parámetros de los diferentes sistemas. En la tabla ref:tab:parametros-tecnicos-modulos-fotovoltaicos se pueden ver los distintos parámetros de los módulos fotovoltaicos.
#+begin_export latex
\begin{center}
{\scriptsize }%
\begin{table}[]
{\scriptsize \caption{Parámetros técnicos de diferentes tipos de células solares.\label{tab:parametros-tecnicos-modulos-fotovoltaicos}}}
\centering{}{\scriptsize }\begin{tabular}{>{\centering}m{5cm} *{2}{>{\centering}m{2cm}}}
\toprule 
{\scriptsize \textbf{Parámetros Técnicos}} & {\scriptsize \textbf{mc-Si}} & {\scriptsize \textbf{pc-Si}}\tabularnewline
\midrule
{\scriptsize Potencia se salida (Wp)} & {\scriptsize 250} & {\scriptsize 220}\tabularnewline
{\scriptsize Voltaje en $P_{max}$ (Vmp)} & {\scriptsize 29.9} & {\scriptsize 29.0}\tabularnewline
{\scriptsize Corriente en $P_{max}$ (Imp)} & {\scriptsize 8.37} & {\scriptsize 7.59}\tabularnewline
{\scriptsize Voltaje en circuito abierto (Voc)} & {\scriptsize 37.1} & {\scriptsize 36.5}\tabularnewline
{\scriptsize Corriente en cortocircuito (Isc)} & {\scriptsize 8.76} & {\scriptsize 8.15}\tabularnewline
{\scriptsize Eficiencia del módulo (\%)} & {\scriptsize 15.5} & {\scriptsize 14.4} \tabularnewline
{\scriptsize $\alpha_{Isc}$ (\%/K)} & {\scriptsize 0.0043} & {\scriptsize 0.06} \tabularnewline
{\scriptsize $\beta_{Voc}$ (\%/K)} & {\scriptsize -0.338} & {\scriptsize -0.37}\tabularnewline
{\scriptsize $\gamma_{Pmpp}$ (\%/K)} & {\scriptsize -0.469} & {\scriptsize -0.45}\tabularnewline
{\scriptsize Temperatura NOC (ºC)} & {\scriptsize 43.7} & {\scriptsize 46}\tabularnewline
\bottomrule
\end{tabular}
\end{table}
\end{center}
#+end_export
Se almacena esta información en listas con la información de cada módulo.

#+begin_src R :session solaR
## mc-Si
module1 <- list(Vocn = 37.1,
                Iscn = 8.76,
                Vmn = 29.9,
                Imn = 8.37,
                CoefVT = 0.00338,
                TONC = 43.7)
## pc-Si
module2 <- list(Vocn = 36.5,
                Iscn = 8.15,
                Vmn = 29,
                Imn = 7.59,
                CoefVT = 0.0037,
                TONC = 46)
#+end_src

Una vez se tiene la información de cada tipo de módulo, en la tabla ref:tab:sistemas-fotovoltaicos se pueden ver la información de la agrupación de cada sistema.
#+begin_export latex
\begin{center}
{\footnotesize }%
\begin{table}
{\scriptsize \caption{Sistemas fotovoltaicos.\label{tab:sistemas-fotovoltaicos}}}
\centering{}{\scriptsize }\begin{tabular}{*{7}{>{\centering}m{1.85cm}}}
\toprule 
{\scriptsize \textbf{Sistema}} & {\scriptsize \textbf{Tecnología}} & {\scriptsize \textbf{Año de Fabricación}} & {\scriptsize \textbf{Módulos en Serie}} & {\scriptsize \textbf{Módulos en Paralelo}} & {\scriptsize \textbf{Potencia del Sistema STC ($Wp_{STC}$)}} & {\scriptsize \textbf{Tamaño ($m^2$)}}\tabularnewline
\midrule
{\scriptsize 1} & {\scriptsize mc-Si} & {\scriptsize 2012} & {\scriptsize 5} & {\scriptsize 1} & {\scriptsize 1250} & {\scriptsize 8}\tabularnewline
{\scriptsize 2} & {\scriptsize pc-Si} & {\scriptsize 2009} & {\scriptsize 5} & {\scriptsize 1} & {\scriptsize 1100} & {\scriptsize 8.2}\tabularnewline
\bottomrule
\end{tabular}
\end{table}
\end{center}
#+end_export
De la misma manera, se almacenará esta información en listas.

#+begin_src R :session solaR
## mc-Si
generator1 <- list(Nms = 5, Nmp = 1)
## pc-Si
generator2 <- list(Nms = 5, Nmp = 1)
#+end_src

Una vez se tienen todos los parémtros del sistema fotovoltaico, se requieren los parámetros del inversor que tienen estos sistemas. Para facilitar el estudio, en el artículo explican que se usa el mismo inversor para todos los sistemas. Los parámetros de este se pueden ver en la tabla ref:tab:caracteristicas-inversor. 
#+begin_export latex
\begin{center}
{\footnotesize }%
\begin{table}
{\scriptsize \caption{Carácteristicas del inversor.\label{tab:caracteristicas-inversor}}}
\centering{}{\scriptsize }\begin{tabular}{*{2}{>{\centering}m{5cm}}}
\toprule 
{\scriptsize \textbf{Inversor}} & {\scriptsize \textbf{SMA Sunny Boy-1200}} \tabularnewline
\midrule
{\scriptsize Potencia máxima DC} & {\scriptsize 1320 W} \tabularnewline
{\scriptsize Corriente máxima DC} & {\scriptsize 12.6 A} \tabularnewline
{\scriptsize Tensión máxima DC} & {\scriptsize 400 V} \tabularnewline
{\scriptsize Rango de tensión fotovoltaica (mpp)} & {\scriptsize 100-320 V} \tabularnewline
{\scriptsize Potencia máxima DC} & {\scriptsize 1320 W} \tabularnewline
{\scriptsize Potencia nominal de salida} & {\scriptsize 1200 W} \tabularnewline
{\scriptsize Maxima potencia aparente} & {\scriptsize 1200 VA} \tabularnewline
{\scriptsize Corriente máxima AC} & {\scriptsize 6.1 A}\tabularnewline
{\scriptsize Eficiencia} & {\scriptsize 92.1\%} \tabularnewline
\bottomrule
\end{tabular}
\end{table}
\end{center}
#+end_export

Se almacena esta información en otra lista:
#+begin_src R :session solaR
  inverter <- list(Pinv = 1200,
		   Vmin = 100,
		   Vmax = 320)
#+end_src

Una vez recopilada toda la información (la información que falta se deja sin añadir para que el propio paquete añada sus valores por defecto), se puede calcular la producción que tuvieron los sistemas:

#+begin_src R :session solaR
  prod1 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'prom',
		    dataRad = list(G0dm = G0_estudio, year = 2013),
		    beta = 30, alfa = -19, iS = 1,
		    module = module1, generator = generator1,
		    inverter = inverter)
  show(prod1)
#+end_src
#+begin_src R :session solaR
  prod2 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'prom',
		    dataRad = list(G0dm = G0_estudio, year = 2013),
		    beta = 30, alfa = -19, iS = 1,
		    module = module2, generator = generator2,
		    inverter = inverter)
  show(prod2)
#+end_src
* =PVsyst=

...


* =solaR2=
label:sec:solaR2
Con los datos obtenidos en la sección ref:sec:solaR, hacemos la misma operación pero con el paquete =solaR2=.
#+begin_src R :session solaR :exports none
  save(G0_estudio, module1, module2, generator1,
       generator2, inverter,
       file = 'TFG/data/ejemplos.RData')
#+end_src
#+begin_src R :session solaR2
  library(solaR2)
#+end_src
#+begin_src R :session solaR2 :exports none
  load('TFG/data/ejemplos.RData')
#+end_src
#+begin_src R :session solaR2
  prod1 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'prom',
		    dataRad = list(G0dm = G0_estudio, year = 2013),
		    beta = 30, alfa = -19, iS = 1,
		    module = module1, generator = generator1,
		    inverter = inverter)
  show(prod1)
#+end_src
#+begin_src R :session solaR2
  prod2 <- prodGCPV(lat = 40.4, modeTrk = 'fixed', modeRad = 'prom',
		    dataRad = list(G0dm = G0_estudio, year = 2013),
		    beta = 30, alfa = -19, iS = 1,
		    module = module2, generator = generator2,
		    inverter = inverter)
  show(prod2)
#+end_src

* Comparación entre los tres 
