\chapter{Estado del arte}
label:chap:estado-arte
* Situación actual de la generación fotovoltaica
label:sec:situacion-actual-generacion-fotovoltaica
Según el informe anual de 2023 de la UNEF[fn:1] cite:unef23 en 2022 la fotovoltaica se posicionó como la tecnología con más crecimiento a nivel internacional, tanto entre las renovables como entre las no renovables. Se instalaron 240 GWp de nueva capacidad fotovoltaica a nivel mundial, suponiendo esto un incremento del 137% con respecto a 2021.

A pesar de las diversas crisis internacionales, la energía solar fotovoltaica alcanzó a superar los 1185 GWp instalados. Como otros años, las cifras indican que China continuó siendo el primer actor mundial, superando los 106 GWp de potencia instalada en el año. La Unión Europea se situó en el segundo puesto, duplicando la potencia instalada en 2021, y alcanzando un nuevo record con 41 GWp instalados en 2022.

La producción energía fotovoltaica a nivel mundial representó el 31% de la capacidad de generación renovable, convirtiendose así en la segunda fuente de generación, solo por detrás de la energía hidráulica. En 2022 se añadió 3 veces más de energía solar que de energía eólica en todo el mundo.

Por otro lado, la Unión Europea superó a EE.UU. como el segundo mayor actor mundial en desarrollo fotovoltaico, instalando un 47% más que en 2021 y alcanzando una potencia acumulada de más de 208 GWp. España lideró el mercado europeo con 8,6 GWp instalados en 2022, superando a Alemania.

El año 2022 fue significativo en términos legislativos con el lanzamiento del Plan REPowerEU[fn:2] cite:europeo22. Dentro de este plan, se lanzó la Estrategía de Energía Solar con el objetivo de alcanzar 400 GWp (320 GW) para 2030, incluyendo medidas para desarrollar tejados solares, impulsar la industria fotovoltaica y apoyar la formación de profesionales en el sector.

En 2022, España vivió un auge en el desarrollo fotovoltaico, instalando 5.641 MWp en plantas en suelo, un 30% más que en 2021, y aumentando el autoconsumo en un 108%, alcanzando 3.008 MWp. El sector industrial de autoconsumo creció notablemente, representando el 47% del autoconsumo total.

España implementó varias iniciativas legislativas para enfrentar la volatilidad de precios de la energía y la dependencia del gas, destacando el RD-ley 6/2022 cite:boe622 y el RD 10/2022 cite:boe1022, que han modificado mecanismos de precios y estableciendo límites al precio del gas.

El Plan SE+[fn:3] cite:demografico22 incluye medidas fiscales y administrativas para apoyar las renovables y el autoconsumo. En 2022, se realizaron subastas de energía renovable, asignando 140 MW a solar fotovoltaica en la tercera subasta y 1.800MW en la cuarta, aunque esta última quedó desierta por precios de reserva bajos.

Se adjudicaron 1.200 MW del nudo de transición justa de Andorra a Enel Green Power España, con planes para instalar plantas de hidrógeno verde y agrovoltaica. la actividad en hidrógeno verde y almacenamiento también creció, con fondos adicionales y exenciones de cargos.

El autoconsumo, apoyado por diversas regulaciones y altos precios de la electricidad, registró un crecimiento significativo, alcanzado 2.504 MW de nueva potencia en 2022. Las comunidades energéticas también avanzaron gracias a ayudas específicas, a pesar de la falta de un marco regulatorio definido.

2022 estuvo marcado por los programas financiados por la Unión Europea, especialmente el Mecanismo de Recuperación y Resiliencia cite:hacienda22 que canaliza los fondos NextGenerationEU cite:union20. El PERTE[fn:4], aprobado en diciembre de 2021, espera crear más de 280.000 empleos, con ayudas que se ejecutarán hasta 2026. En 2023 se solicitó a Bruselas una adenda para segunda fase del PERTE, obteniendo 2.700 millones de euros adicionales.

La contribución del sector fotovoltaico a la economía española en 2022 fue significativa, aportando 7.014 millones de euros al PIB[fn:5], un 51% más que el año anterior, y generando una huella econóimca total de 15.656 millones de euros. En términos de empleo, el sector involucró a 197.383 trabajadores, de los cuales 40.683 fueros directos, 97.600 indirectos y 59.100 inducidos.

El sector industrial fotovoltaico nacional tiene una fuerte presencia en España, con hasta un 65% de los componenetes manufacturados localmente. Empresas españolas se encuentran entre los principales fabricantes mundiales de inversores y seguidores solares. Además, España es un importante exportador de estructuras fotovoltaicas y cuenta con iniciativas prometedoras para la fabricación de módulos solares.

En definitiva, la fotovoltaica es una tecnología en auge y con perspectivas para ser el pilar de la transición ecológica. Por ello, surge la necesidad de encontrar herramientas que permitan estimar el desempeño que estos sistemas pueden tener a la hora de realizar estudios de viabilidad económica.

* Soluciones actuales y sus carencias
label:sec:soluciones-actuales-carencias
Como se mencionó en el capítulo ref:chap:introduccion, existen una serie de herramientas que permiten el cálculo y la simulación de instalaciones fotovoltaicas. Todas ellas presentan una serie de ventajas específicas, a cambio de una serie de limitaciones. Estas son:
1. *PVsyst - Photovoltaic Software* cite:pvsyst
   Este software es probablemente el más conocido dentro del ámbito del estudio y la estimación de instalaciones fotovoltaicas. Destaca por la personalización detallada de los componentes de la instalación (módulos, inversores, sombreado, etc.), lo que ermite una simulación precisa a través de datos meteorológicos y parámetros detallados del sistema. Su uso está extendido en proyectos de gran escala y estuidos avanzados de eficiencia.
   - Ventajas:
     - *Completo y profesional*: PVsyst es altamente detallado, permitiendo análisis avanzados para proyectos pequeños y grandes.
     - *Base de datos meteorológicos*: Integra datos climáticos de fuentes como Meteonorm cite:jan20, lo que mejora la precisión de las simulaciones.
     - *Simulaciones avanzadas*: Permite modelar la energía producida por una planta fotovoltaica y calcular las pérdidas debidas a sombreamiento, inclinación, orientaciones y resistencias internas de los módulos.
     - *Herramientas de dimensionamiento*: Ofrece módulos específicos para diseñar la configuración de inversores y módulos solares.
   - Limitaciones:
     - *Costo*: Es un software comercial , con licencias que pueden ser costosas para proyectos pequeños.
     - *Curva de aprendizaje*: Su interfaz puede resultar compleja para usuarios nuevos, lo que implica una curva de aprendizaje considerable.
     - *Enfoque técnico*: Está más orientado a ingenieros y técnicos, por lo que carece de accedsibilidad para usuarios no especializados.
2. *SISIFO* cite:sisifo
   Herramienta web diseñada por el *Grupo de Sistemas Fotovoltaicos del Instituto de Energía Solar de la Universidad Politécnica de Madrid*. Está diseñada para ser accesible y fácil de usar, enfocándose en una audiencia más general, incluyenco ingenieros, pero también técnicos y académicos.
   - Ventajas:
     - *Facilidad de uso*: Tiene una interfaz amigable y fácil de utilizar, lo que lohace accesible para usuarios con distintos niveles de experiencia.
     - *Open-source*: Al ser de código abierto, permite a los desarrolladores modificar y adaptar el software a sus necesidades específicas.
     - *Simulación integrada*: Ofrece la posibilidad de realizar simulaciones basadas en datos meteorológicos, aunque con un nivel de detalle inferior a PVsyst.
     - *Soporte comunitario*: Al ser de código abierto, cuenta con una comunidad activa de usuarios y desarrrolladores que colaboran en mejoras y actualizaciones.
   - Limitaciones:
     - *Menos preciso*: Al compararse con otras herramientas, su precisión puede ser menor en cuanto a modelado y simulación de pérdidas, ya que simplifica varios aspectos del sistema.
     - *Limitaciones en grandes proyectos*: No está tan bien adaptado para grandes instalaciones o análisis financieros avanzados.
3. *PVGIS* cite:pvgis
   Aplicación web desarrolada por el *European Commission Joint Research Center* desde 2001. Está diseñada para proporcionar estimaciones de producción de energía solar en función de la ubicación geográfica y condiciones meteorológicas históricas.
   - Ventajas:
     - *Gratuito y accesible*: Esta herramienta es completamente gratuira y accesible a través de una interfaz web, lo que facilita el uso por parte de cualquier persona.
     - *Datos meteorológicos precisos*: Proporciona acceso a datos meteorológicos satelitales y de estaciones terrestres, lo que permite obtener estimaciones razonables de producción de energía.
     - *Estudios rápidos*: Es ideal para obtener estimaciones preliminares y estudios de viabilidad de sistemas fotovoltaicos.
4. *System Advisor Model* cite:sam
   Desarrollado por el *Laboratorio Nacional de Energías Renovables*, perteneciente al Departamento de energía del gobierno de EE.UU. Está orientada a la modelación tanto técnica como económica de sistemas de energía renovable, incluyendo fotovoltaicos.
   - Ventajas:
     - *Modelo económico avanzado*: Integra análisis detalados sobre la viabilidad económica, lo que permite evaluar tanto la producción energética como los costos y benefecios a lo largo de la vida útil del proyecto.
     - *Acceso a múltiples tecnologías*: Además de fotovoltaicos, permite modelar otras tecnologías de energía renovable, lo que lo hace más flexible para estuidos multidisciplinares.
     - *Integración de bases de datos*: Utiliza datos meteorológicos detallados, lo que mejora la precisión de las simulaciones.
   - Limitaciones:
     - *Complejidad*: Aunque gratuito, SAM es bastante complejo y técnico, lo que puede limitar su uso a usuarios con experiencia en el modelado de sistemas energéticos.
     - *Interfaz no tan intuitiva*: Comparado con otras herramientas, requiere un mayor tiempo de familiarización debido a su enfoque integral y detalle en las simulaciones.

Como se mencionó en el capitulo ref:chap:introduccion este proyecto toma su base en el paquete =solaR= cite:perpinan12, el cual es una herramienta robusta para el cálculo de la radiación solar y el rendimiento de sistemas fotvoltaicos.

Este paquete está diseñado utilizando clases =S4= en =R=, y su núcleo se basa en series temporales multivariantes almacenadas en objetos de la clase =zoo=. Su funcionamiento se basa, al igual que =solaR2=, en una serie de funciones constructoras que calculan objetos relacionados con cada paso de la simulación de un sistema fotovoltaico. Podemos dividir su funcionamiento en los siguientes grupos:
1. *Cálculo de la geometría solar*: calcula el movimiento aparente diario (con =fSolD=) e intradiario (con =fSolI=) del Sol desde la Tierra. Para ello se vale de la función =calcSol= la cual devuelve un objeto de clase =Sol= que contiene todos los ángulos necesarios.
2. *Almacenamiento de datos meteorológicos*: se define la clase =Meteo=, la cual, se construye mediante una serie de funciones (=readBD=, =readG0dm=, =zoo2Meteo=, =df2Meteo=...). Estas funciones toman los datos meteorológicos provenientes de distintas vias (un =data.frame=, un objeto =zoo=, un fichero...) y los adapta para que puedan ser manipulados por el resto de funciones del paquete.
3. *Cálculo de radiación en un plano horizontal*: tomando los objetos anteriores, es capaz de calcular (si no vienen ya dadas) las componentes de la irradiación (con =fCompD=) y de la irradiancia (con =fCompI=). La función =calcG0= devuelve un objeto =G0= que contiene las anteriores componentes y añade medias mensuales de valores diarios y sumas anuales de la irradiación.
4. *Cálculo de radiación en el plano del generador*: toma un objeto =G0= y lo transforma en un objeto =Gef= mediante la función =calcGef=, la cual utilizando las funciones =fTheta= y =fInclin= determinan la irradiación y la radiación efectiva al igual que las medias mensuales de la irradiación diaria y sumas anuales.
5. *Simulación de sistemas fotovoltaicos conectados a red*: con un objeto =Gef= y con los parametros del sistema, la función =prodGCPV=, tomando los resultado de la función =fProd=, cálcula la producción energética de un SFCR. Devuleve un objeto de clase =ProdGCPV= que incluye valores de potencias instantaneas y energías diarias, medias mensuales y sumas anuales.
6. *Simulación de sistemas fotovoltaicos de bombeo*: toma un objeto =Gef= y con los paremetros del sistema y de la bomba, la función =prodPVPS=, tomando los resultados de la función =fPump=, cálcula la producción energética de un SFB-
7. *Optimización de distancias*: es capaz de optimizar las distancias de un sfcr mediante la función =optimShd=, la cual devuelve un objeto =Shade= el cual contiene multiples combinaciones de distancias para que el usuario pueda decidir la mejor.
8. *Métodos de visualización*: para cada uno de los objetos mencionados existen métodos de visualización gráfica para ayudar a comprender los resultados obtenidos.
   
Pese a ser un herramienta muy capaz, =solaR= presenta una serie de carencias relativas:
- *Modularidad*: el paquete =solaR= contiene funciones que realizan muchas operaciones, esto deja poco lugar al usuario para que pueda entender cada componente independientemente.
- *Eficiencia y rendimiento*: el paquete =solaR= utiliza =zoo= para manejar series temporales, lo cual es adecuado para volúmenes de datos moderados. Sin embargo, =zoo= no está optimizado para operaciones de alta eficiencia en datasets grandes. 
- *Escalabilidad*: =solaR= puede experimentar problemas de escalabilidad al trabajar con datasets extensos, ya que =zoo= no es tan eficiente en operaciones que requieren manipulación compleja o paralelización. 
- *Manipulación de datos*: =zoo= es adecuado para manejar series temporales básicas, pero carece de las capacidades avanzadas de manipulación de datos que ofrecen otros paquetes.

En el capitulo [[ref:chap:ejemplo-practico-aplicacion]] se realizará un ejemplo práctico que compare los resultados entre =PVsyst=, =solaR= y =solaR2=

* Footnotes

[fn:5]PIB: Producto Interior Bruto. 
[fn:4]PERTE: Proyecto Estratégico para la Recuperación y Transformación Económica.
[fn:3]Plan + Seguridad Energética: Se trata de un plan con medidas de rápido impacto dirigidas al invierno 2022/2023, junto con medidas que contribuyen a un refuerzo estructural de esa seguridad energética.
[fn:2]Plan REPowerEU: Proyecto por el cual la Unión Europea quiere poner fin a su dependencia de los combustibles fósiles rusos ahorrando energía, diversificando los suministros y acelerando la transción hacia una energía limpia.
[fn:1]UNEF: Unión Española Fotovoltaica.
