\chapter{Introducción}
label:chap:introduccion

* Objetivos
label:sec:objetivos
El objetivo principal de este proyecto es el desarrollo de un paquete en R cite:rcoreteam23 con el cual poder realizar estimaciones y representaciones gráficas de la posible generación de una instalación fotovoltaica.

Durante el resto del documento, si fuera necesario, se hará referencia al paquete desarrollado en este proyecto con el nombre solaR2 [CITAR SOLAR2].

El usuario podrá colocar los datos que considere convenientes (desde una base de datos oficial, una base de datos propia... etc.) en cada una de las funciones que ofrece el paquete pudiendo así obtener resultados de la geometría solar, de la radiación horizontal, de la eficaz y hasta de la producción de diferentes tipos de sistemas fotovoltaicos.

El paquete también incluye una serie de funciones que permiten hacer representaciones gráficas de estos resultados con el fin de poder apreciar con más detalle las diferencias entre sistemas y contemplar cual es la mejor opción para el emplazamiento elegido.

Este proyecto toma su origen en el paquete ya existente =solaR= cite:perpinan12 el cual desarrolló el tutor de este proyecto en 2012. Por la antigüedad del código se propuso la idea de renovarlo teniendo en cuenta el paquete en el que basa su funcionamiento. El paquete =solaR= basó su funcionamiento en el paquete =zoo= cite:zeileis05 el cual proporciona una sólida base para trabajar con series temporales. Sin embargo, como base de =solaR2= se optó por el paquete =data.table= cite:barrett24. Este paquete ofrece una extensión de los clásicos =data.frame= de R en los =data.table=, los cuales pueden trabajar rápidamente con enormes cantidades de datos (por ejemplo, 100 GB de RAM).

La clave de ambos proyectos es que al estar alojados en R, cualquier usuario puede acceder a ellos de forma gratuita, tan solo necesitas tener instalado R en tu dispositivo.

Para alojar este proyecto se toman dos vías:
- =Github= cite:github: Donde se aloja la versión de desarrollo del paquete.
- =CRAN=: Acrónimo de Comprehensive R Archive Network, es el repositorio donde se alojan las versiones definitivas de los paquetes y desde el cual se descargan a la sesión de R.

El paquete =solaR2= permite realizar las siguientes operaciones:
- Cálculo de toda la geometría que caracteriza a la radiación procedente del Sol (ref:subsec:calcsol).
- Tratamiento de datos meteorológicos (en especial de radiación), procedentes de datos ofrecidos del usuario y de la red de estaciones SIAR cite:siar23 (ref:subsec:meteoreaders).
- Una vez calculado lo anterior, se pueden hacer estimaciones de:
  * Los componentes de radiación horizontal (ref:subsec:calcg0).
  * Los componentes de radiación eficaz en el plano inclinado (ref:subsec:calcgef).
  * La producción de sistemas fotovoltaicos conectados a red (ref:subsec:prodgcpv) y sistemas fotovoltaivos de bombeo (ref:subsec:prodpvps).

Este proyecto ha tenido a su vez una serie de objetivos secundarios:
- Uso y manejo de GNU Emacs cite:emacs85 en el que se realizaron todos los archivos que componen este documento (utilizando el modo Org cite:dominik03) y el paquete descrito (empleando ESS cite:ess24)
- Dominio de diferentes paquetes de R:
  * =zoo= cite:zeileis05: Paquete que proporciona un conjunto de clases y métodos en S3 para trabajar con series temporales regulares e irregulares.
    Usado en el paquete =solaR= como pilar central.
  * =data.table= cite:barrett24: Otorga una extensión a los datos de tipo data.frame que permite una alta eficiencia especialmente con conjuntos de datos muy grandes.
    Se ha utilizado en el paquete =solaR2= en sustitución del paquete =zoo= como tipo de dato principal en el cual se construyen las clases y métodos de este paquete.
  * =microbenchmark= cite:mersmann23: Proporciona infraestructura para medir y comparar con precisión el tiempo de ejecución de expresiones en R.
    Usado para comparar los tiempos de ejecución de ambos paquetes.
  * =profvis= cite:wickham24: Crea una interfaz gráfica donde explorar los datos de rendimiento de una expresión dada.
    Aplicada junto con =microbenchmark= para detectar y corregir cuellos de botella en el paquete =solaR2=
  * =lattice= cite:sarkar08: Proporciona diversas funciones con las que representar datos.
    El paquete =solaR2= utiliza este paquete para representar de forma visual los datos obtenidos en las estimaciones.
- Junto con el modo Org, se ha utilizado el prepador de textos LaTeX (partiendo de un archivo .org, se puede exportar a un archivo .tex para posteriormente exportar un pdf).
- Obtener conocimientos teóricos acerca de la radiación solar y de la producción de energía solar mediante sistemas fotovoltaicos y sus diversos tipos.
  Para ello se ha usado en mayor medida el libro "Energía Solar Fotovoltaica" cite:Perpinan2023.
* Análisis previo de soluciones
Este proyecto, como ya se ha comentado, es el heredero del paquete =solaR= desarrollado por Oscar Perpiñán. La filosofía de ambos paquetes es la misma y los resultados que dan son muy similares. Sin embargo, lo que les diferencia es el paquete sobre el que construyen sus datos.
Mientras que =solaR= basa sus clases y métodos en el paquete =zoo=, =solaR2= en el paquete =data.table=. Los dos paquetes pueden trabajar con series temporales, pero, mientras que =zoo= es más eficaz trabajando con series temporales, =data.table= es más eficiente a la hora de trabajar con una cantidad grande de datos, lo cual a la hora de realizar estimaciones muy precisas es beneficioso.
Por otro lado, existen otras soluciones fuera de R:
1. *PVsyst - Photovoltaic Software*\\
   Este software es probablemente el más conocido dentro del ámbito del estudio y la estimación de instalaciones fotovoltaicas. Permite una gran personalización de todos los componentes de la instalación.
2. *SISIFO*\\
   Herramienta web diseañda por el *Grupo de Sistemas Fotovoltaicos del Instituto de Energía Solar de la Universidad Politécnica de Madrid*.
3. *PVGIS*\\
   Aplicación web desarrolada por el *European Commission Joint Research Center* desde 2001.
4. *System Advisor Model*\\
   Desarrollado por el *Laboratorio Nacional de Energías Renovables*, perteneciente al Departamento de energía del gobierno de EE.UU.
En el capitulo [[ref:chap:ejemplo-practico-aplicacion]] se realizará un ejemplo práctico que compare los resultados entre *PVsyst*, =solaR= y =solaR2=
* Aspectos técnicos
label:sec:aspectos-tecnicos
Las fuentes de un paquete de =R= están contenidas en un directorio que contiene al menos:
- Los ficheros *DESCRIPTION* y *NAMESPACE*
- Los subdirectorios:
  - =R=: código en ficheros .R
  - =man=: páginas de ayuda de las funciones, métodos y clases contenidas en el paquete.
Esta estructura puede ser generada con =package.skeleton=

** DESCRIPTION
label:subsec:description
El fichero DESCRIPTION contiene la información básica:
#+begin_export latex
\begin{examplebox}
#+end_export
#+begin_example
     Package: pkgname
     Version: 0.5-1
     Date: 2004-01-01
     Title: My First Collection of Functions
     Authors@R: c(person("Joe", "Developer", role = c("aut", "cre"),
                          email = "Joe.Developer@some.domain.net"),
                   person("Pat", "Developer", role = "aut"),
                   person("A.", "User", role = "ctb",
     	             email = "A.User@whereever.net"))
     Author: Joe Developer and Pat Developer, with contributions from A. User
     Maintainer: Joe Developer <Joe.Developer@some.domain.net>
     Depends: R (>= 1.8.0), nlme
     Suggests: MASS
     Description: A short (one paragraph) description of what
       the package does and why it may be useful.
     License: GPL (>= 2)
     URL: http://www.r-project.org, http://www.another.url
#+end_example
#+begin_export latex
\end{examplebox}
#+end_export
- Los campos =Package=, =Version=, =License=, =Title=, =Autor= y =Maintainer= son obligatorios.
- Si usa métodos =S4= debe incluir =Depends: methods=.
** NAMESPACE
label:subsec:namespace
=R= usa un sistema de gestión de *espacio de nombres* que permite al autor del paquete especificar:
- Las *variables* del paquete que se *exportan* (y son, por tanto, accesibles a los usuarios).
- Las *variables* que se *importan* de otros paquetes.
- Las *clases y métodos* =S3= y =S4= que deben registrarse.

El =NAMESPACE= controla la estrategia de búsqueda de variables que utilizan las funciones del paquete:
- En primer lugar, busca entre las creadas localmente (por el código de la carpeta =R/=).
- En segundo lugar, busca entre las variables importadas explícitamente de otros paquetes.
- En tercer lugar, busca en el =NAMESPACE= del paquete =base=.
- Por último, busca siguiendo el camino habitual (usando =search()=).
#+begin_src R :exports both :results output
search()
#+end_src
*** Manejo de variables
- Exportar variables:
#+begin_src R :eval no
  export(f, g)
#+end_src
- Importar *todas* las variables de un paquete:
#+begin_src R :eval no
  import(pkgExt)
#+end_src
- Importar variables *concretas* de un paquete:
#+begin_src R :eval no
  importFrom(pkgExt, var1, var2)
#+end_src
*** Manejo de clases y métodos
- Para registrar un *método* para una *clase* determinada:
#+begin_src R :eval no
  S3method(print, myClass)
#+end_src
- Para usar clases y métodos =S4=:
#+begin_src R :eval no
  import("methods")
#+end_src
- Para registrar clases =S4=:
#+begin_src R :eval no
  exportClasses(class1, class2)
#+end_src
- Para registrar métodos =S4=:
#+begin_src R :eval no
  exportMethods(method1, method2)
#+end_src
- Para importar métodos y clases =S4= de otro paquete:
#+begin_src R :eval no
  importClassesFrom(package, ...)
  importMethodsFrom(package, ...)
#+end_src
** Documentación
label:subsec:documentacion
Las páginas de ayuda de los objetos =R= se escriben usando el formato "R documentation" (Rd), un lenguaje similar a LaTeX.
#+begin_export latex
\begin{examplebox}
#+end_export
#+begin_example
  \name{load}
  \alias{load}
  \title{Reload Saved Datasets}
  \description{
    Reload the datasets written to a file with the function
    \code{save}.
  }
  \usage{
    load(file, envir = parent.frame())
  }
  \arguments{
  \item{file}{a connection or a character string giving the
      name of the file to load.}
  \item{envir}{the environment where the data should be
      loaded.}
  }
  \seealso{
    \code{\link{save}}.
  }
  \examples{
    ## save all data
    save(list = ls(), file= "all.RData")
    
    ## restore the saved values to the current environment
    load("all.RData")
    
    ## restore the saved values to the workspace
    load("all.RData", .GlobalEnv)
  }
  \keyword{file}
#+end_example
#+begin_export latex
\end{examplebox}
#+end_export
