\chapter{Introducción}
label:chap:introduccion

* Objetivos
label:sec:objetivos
El objetivo principal de este proyecto es el desarrollo de un paquete en R cite:rcoreteam23 con el cual poder realizar estimaciones y representaciones gráficas de la geometría solar, radiación solar en el plano horizontal y del generador, y el funcionamiento de sistemas fotovoltaicos de conexión a red y de bombeo de agua.

Durante el resto del documento, si fuera necesario, se hará referencia al paquete desarrollado en este proyecto con el nombre solaR2 [CITAR SOLAR2].

El usuario puede colocar los datos que considere convenientes (desde una base de datos oficial, una base de datos propia... etc.) en cada una de las funciones que ofrece el paquete pudiendo así obtener resultados de la geometría solar, de la radiación horizontal, de la efectiva y hasta de la producción de diferentes tipos de sistemas fotovoltaicos.

El paquete también incluye una serie de funciones que permiten hacer representaciones gráficas de estos resultados con el fin de poder apreciar con más detalle las diferencias entre sistemas y contemplar cual es la mejor opción para el emplazamiento elegido.

Este proyecto toma su origen en el paquete ya existente =solaR= cite:perpinan12 el cual desarrolló el tutor de este proyecto en 2010. Esta versión, la 0.14, ha tenido una serie de actualizaciones, siendo la más reciente la 0.46 (en el 2021). Sin embargo, al ser versiones de un software antiguo se propuso la idea de renovarlo teniendo en cuenta el paquete en el que basa su funcionamiento. El paquete =solaR= basó su funcionamiento en el paquete =zoo= cite:zeileis05 el cual proporciona una sólida base para trabajar con series temporales. Sin embargo, como base de =solaR2= se optó por el paquete =data.table= cite:barrett24. Este paquete ofrece una extensión de los clásicos =data.frame= de R en los =data.table=, los cuales pueden trabajar rápidamente con enormes cantidades de datos (por ejemplo, 100 GB de RAM).

La clave de ambos proyectos es que al estar basados en R, cualquier usuario puede acceder a ellos de forma gratuita, tan solo necesitas tener instalado R en tu dispositivo.

Para alojar este proyecto se toman dos vías:
- =Github= cite:github: Donde se aloja la versión de desarrollo del paquete.
- =CRAN=: Acrónimo de Comprehensive R Archive Network, es el repositorio donde se alojan las versiones definitivas de los paquetes y desde el cual se descargan a la sesión de R.

El paquete =solaR2= permite realizar las siguientes operaciones:
- Cálculo de toda la geometría que caracteriza a la radiación procedente del Sol.
- Tratamiento de datos meteorológicos (en especial de radiación), procedentes de datos ofrecidos del usuario y de la red de estaciones SIAR cite:siar23.
- Una vez calculado lo anterior, se pueden hacer estimaciones de:
  * Los componentes de radiación horizontal.
  * Los componentes de radiación eficaz en el plano inclinado.
  * La producción de sistemas fotovoltaicos conectados a red y sistemas fotovoltaivos de bombeo.

Este proyecto ha tenido a su vez una serie de objetivos secundarios:
- Uso y manejo de GNU Emacs cite:emacs85 en el que se realizaron todos los archivos que componen este documento (utilizando el modo Org cite:dominik03) y el paquete descrito (empleando ESS cite:ess24)
- Dominio de diferentes paquetes de R:
  * =zoo= cite:zeileis05: Paquete que proporciona un conjunto de clases y métodos en S3 para trabajar con series temporales regulares e irregulares.
    Usado en el paquete =solaR= como pilar central.
  * =data.table= cite:barrett24: Otorga una extensión a los datos de tipo data.frame que permite una alta eficiencia especialmente con conjuntos de datos muy grandes.
    Se ha utilizado en el paquete =solaR2= en sustitución del paquete =zoo= como tipo de dato principal en el cual se construyen las clases y métodos de este paquete.
  * =microbenchmark= cite:mersmann23: Proporciona infraestructura para medir y comparar con precisión el tiempo de ejecución de expresiones en R.
    Usado para comparar los tiempos de ejecución de ambos paquetes.
  * =profvis= cite:wickham24: Crea una interfaz gráfica donde explorar los datos de rendimiento de una expresión dada.
    Aplicada junto con =microbenchmark= para detectar y corregir cuellos de botella en el paquete =solaR2=
  * =lattice= cite:sarkar08: Proporciona diversas funciones con las que representar datos.
    El paquete =solaR2= utiliza este paquete para representar de forma visual los datos obtenidos en las estimaciones.
- Junto con el modo Org, se ha utilizado el prepador de textos LaTeX (partiendo de un archivo .org, se puede exportar a un archivo .tex para posteriormente exportar un pdf).
- Obtener conocimientos teóricos acerca de la radiación solar y de la producción de energía solar mediante sistemas fotovoltaicos y sus diversos tipos.
  Para ello se ha usado en mayor medida el libro "Energía Solar Fotovoltaica" cite:Perpinan2023.
* Análisis previo de soluciones
Este proyecto, como ya se ha comentado, es el heredero del paquete =solaR= desarrollado por Oscar Perpiñán. La filosofía de ambos paquetes es la misma y los resultados que dan son muy similares. Sin embargo, lo que les diferencia es que =solaR2= es más modular, es decir, tiene muchas funciones autónomas que permiten realizar cálculos específicos, en especial de geometría y radiación, y, el paquete sobre el que construyen sus datos.

Mientras que =solaR= basa sus clases y métodos en el paquete =zoo=, =solaR2= en el paquete =data.table=. Los dos paquetes pueden trabajar con series temporales, pero, mientras que =zoo= es más eficaz trabajando con series temporales, =data.table= es más eficiente a la hora de trabajar con una cantidad grande de datos, lo cual a la hora de realizar estimaciones muy precisas es beneficioso.

Por otro lado, existen otras soluciones fuera de R:
1. *PVsyst - Photovoltaic Software* cite:pvsyst
   Este software es probablemente el más conocido dentro del ámbito del estudio y la estimación de instalaciones fotovoltaicas. Destaca por la personalización detallada de los componentes de la instalación (módulos, inversores, sombreado, etc.), lo que ermite una simulación precisa a través de datos meteorológicos y parámetros detallados del sistema. Su uso está extendido en proyectos de gran escala y estuidos avanzados de eficiencia.
   - Ventajas:
     - *Completo y profesional*: PVsyst es altamente detallado, permitiendo análisis avanzados para proyectos pequeños y grandes.
     - *Base de datos meteorológicos*: Integra datos climáticos de fuentes como Meteonorm cite:jan20, lo que mejora la precisión de las simulaciones.
     - *Simulaciones avanzadas*: Permite modelar la energía producida por una planta fotovoltaica y calcular las pérdidas debidas a sombreamiento, inclinación, orientaciones y resistencias internas de los módulos.
     - *Herramientas de dimensionamiento*: Ofrece módulos específicos para diseñar la configuración de inversores y módulos solares.
   - Limitaciones:
     - *Costo*: Es un software comercial , con licencias que pueden ser costosas para proyectos pequeños.
     - *Curva de aprendizaje*: Su interfaz puede resultar compleja para usuarios nuevos, lo que implica una curva de aprendizaje considerable.
     - *Enfoque técnico*: Está más orientado a ingenieros y técnicos, por lo que carece de accedsibilidad para usuarios no especializados.
2. *SISIFO* cite:sisifo
   Herramienta web diseñada por el *Grupo de Sistemas Fotovoltaicos del Instituto de Energía Solar de la Universidad Politécnica de Madrid*. Está diseñada para ser accesible y fácil de usar, enfocándose en una audiencia más general, incluyenco ingenieros, pero también técnicos y académicos.
   - Ventajas:
     - *Facilidad de uso*: Tiene una interfaz amigable y fácil de utilizar, lo que lohace accesible para usuarios con distintos niveles de experiencia.
     - *Open-source*: Al ser de código abierto, permite a los desarrolladores modificar y adaptar el software a sus necesidades específicas.
     - *Simulación integrada*: Ofrece la posibilidad de realizar simulaciones basadas en datos meteorológicos, aunque con un nivel de detalle inferior a PVsyst.
     - *Soporte comunitario*: Al ser de código abierto, cuenta con una comunidad activa de usuarios y desarrrolladores que colaboran en mejoras y actualizaciones.
   - Limitaciones:
     - *Menos preciso*: Al compararse con otras herramientas, su precisión puede ser menor en cuanto a modelado y simulación de pérdidas, ya que simplifica varios aspectos del sistema.
     - *Limitaciones en grandes proyectos*: No está tan bien adaptado para grandes instalaciones o análisis financieros avanzados.
3. *PVGIS* cite:pvgis
   Aplicación web desarrolada por el *European Commission Joint Research Center* desde 2001. Está diseñada para proporcionar estimaciones de producción de energía solar en función de la ubicación geográfica y condiciones meteorológicas históricas.
   - Ventajas:
     - *Gratuito y accesible*: Esta herramienta es completamente gratuira y accesible a través de una interfaz web, lo que facilita el uso por parte de cualquier persona.
     - *Datos meteorológicos precisos*: Proporciona acceso a datos meteorológicos satelitales y de estaciones terrestres, lo que permite obtener estimaciones razonables de producción de energía.
     - *Estudios rápidos*: Es ideal para obtener estimaciones preliminares y estudios de viabilidad de sistemas fotovoltaicos.
4. *System Advisor Model* cite:sam
   Desarrollado por el *Laboratorio Nacional de Energías Renovables*, perteneciente al Departamento de energía del gobierno de EE.UU. Está orientada a la modelación tanto técnica como económica de sistemas de energía renovable, incluyendo fotovoltaicos.
   - Ventajas:
     - *Modelo económico avanzado*: Integra análisis detalados sobre la viabilidad económica, lo que permite evaluar tanto la producción energética como los costos y benefecios a lo largo de la vida útil del proyecto.
     - *Acceso a múltiples tecnologías*: Además de fotovoltaicos, permite modelar otras tecnologías de energía renovable, lo que lo hace más flexible para estuidos multidisciplinares.
     - *Integración de bases de datos*: Utiliza datos meteorológicos detallados, lo que mejora la precisión de las simulaciones.
   - Limitaciones:
     - *Complejidad*: Aunque gratuito, SAM es bastante complejo y técnico, lo que puede limitar su uso a usuarios con experiencia en el modelado de sistemas energéticos.
     - *Interfaz no tan intuitiva*: Comparado con otras herramientas, requiere un mayor tiempo de familiarización debido a su enfoque integral y detalle en las simulaciones.
En el capitulo [[ref:chap:ejemplo-practico-aplicacion]] se realizará un ejemplo práctico que compare los resultados entre *PVsyst*, =solaR= y =solaR2=
