\chapter{Parte teórica y desarrollo del código}
El paquete =solaR2= toma como marco teórico el libro de Oscar Perpiñán, tutor de este trabajo, Energía Solar Fotovoltaica \cite{Perpinan2023} para cada una de las operaciones de cálculo que realizan cada una de las funciones.
En la figura [[fig:prod-calculo]], se muestra un diagrama que resume los pasos que se siguen a la hora de calcular la producción de sistemas fotovoltaicos.
#+ATTR_LATEX: :height 0.5\textheight :width 0.9\textwidth :options keepaspectratio
#+CAPTION: Procedimiento de cálculo
#+NAME: fig:prod-calculo
[[file:figuras/ProcedimientoCalculoRadiacionInclinada.pdf]]
Estos pasos son:
1. Obtener la irradiación global diaria en el plano horizontal
2. A partir de la irradiación global, obtener las componentes de difusa y directa.
3. Se trasladan estos valores de irradición a valores de irradiancia.
4. Con estos valores se pueden obtener los valores correspondientes en el plano del generador
   1. Sin los efectos de la suciedad de los modulos y las sombras que se generan unos con otros.
   2. Con estos efectos
5. Integrando estos valores se pueden obtener las estimaciones irradiación diaria difusa, directa y global
6. El generador fotovoltaico produce una potencia en corriente continua dependiente del rendimiento del mismo..
7. Se transforma en potencia en corriente alterna mediante un inversor que tiene una eficiencia asociada.
8. Integrando esta potencia se puede obtener la energía que produce el generador en un tiempo determinado.

* Naturaleza de la radiación solar
Para el cálculo de la radiación solar que incide en una superficie se deben distinguir tres componentes diferenciados:
- *Radiación Directa*, B\nomenclature[B]{\(B\)}{Radiación directa}: porción de radiación que procede en línea recta desde el Sol.
- *Radiación Difusa*, D\nomenclature[D]{\(D\)}{Radiación difusa}: fracción de radiación que procede de todo el cielo, excepto del Sol. Son todos aquellos rayos que dispersa la atmósfera.
- *Radiación del albedo*, R\nomenclature[R]{\(R\)}{Radiación del albedo}: parte de la radiación procedente de la reflexión con el suelo.
La suma de las tres componentes constituye la denominada radiación global: \nomenclature[G]{\(G\)}{Radiación global}
#+begin_export latex  
\begin{equation}
G = B + D + R
\label{eq:comp_rad}
\end{equation}
#+end_export
Tomando como base el libro antes mencionado [[cite:Perpinan2023]], se describirá el proceso que se ha de seguir para obtener una estimación de las componenetes directa y difusa a partir del dato de radiación global, dado que es el que comúnmente se puede obtener de una localización determinada.

** Radiación fuera de la atmósfera terrestre
Lo primero que se menciona en dicho proceso es la obtención de la irradiancia denominda extra-terrestre o extra-atmosférica, que es la radiación que llega a la atmósfera, directamente desde el Sol, que no sufre ninguna pérdida por interaccionar con algún medio. Como la relación entre el tamaño de nuesto plenta y la distancia entre el Sol y la Tierra es muy reducida, es posible asumir que el valor de dicha irradiancia es constante, siendo este valor $B_0=1367\frac{W}{m^2}$, según varias mediciones.
Como la órbita que describe la Tierra alrededor del Sol no es totalmente circular, sino que tiene forma de elipse, para calcular la irradiancia incidente en una superficie tangente a la atmosfera en ua latitud concreta, debemos aplicar un facot de correción de la excentricidad de la elipse:
#+begin_export latex
\begin{equation}
B_0(0)=B_0\epsilon_0cos\theta_{zs}
\label{eq:irrad_horiz}
\end{equation}
#+end_export
Siendo cada componente:
- Irradiancia extra-terrestre: $B_0=1367\frac{W}{m^2}$ \nomenclature[B0]{\(B_0\)}{Irradiancia extra-atmosférica o extra-terrestre}
- Factor de corrección por excentricidad: $\epsilon_0=(\frac{r_0}{r})^2=1+0.033\cdot cos(\frac{2\pi d_n}{365})$[fn:1] \nomenclature[epsilon0]{\(\epsilon_0\)}{Corrección debida a la excentricidad de la elipse de la trayectoria terrestre alrededor del sol}
- Ángulo zenital solar: $cos(\theta_{zs})=cos(\delta)cos(\omega)cos(\phi)+sin(\delta)+sin(\phi)$[fn:2] \nomenclature[thetazs]{\(\theta_{zs}\)}{Ángulo cenital solar}

  Donde:
  - Declinación: $\delta =23,45º\cdot sin(\frac{2\pi \cdot (d_n+284)}{365})$ \nomenclature[delta]{\(\delta\)}{Declinación}
  - Latitud: \(\phi\) \nomenclature[phi]{\(\phi\)}{Latitud}
  - Hora solar o tiempo solar verdadero: $\omega = 15\cdot (TO-AO-12)+\Delta \lambda +\frac{EoT}{4}$ \nomenclature[omega]{\(\omega\)}{Hora solar o tiempo solar verdadero}

    Donde:
    - Hora oficial: \(TO\) \nomenclature[TO]{\(TO\)}{Hora oficial}
    - Adelanto oficial durante el horario de verano: \(AO\) \nomenclature[AO]{\(AO\)}{Adelanto oficial durante el horario de verano}
    - Diferencia entre la longitud local y la longitud del huso horario: \(\Delta \lambda\) \nomenclature[deltalambda]{\(\Delta \lambda\)}{Diferencia entre la longitud local y la longitud del huso horario}
    - Ecuación del tiempo: $EoT=229,18\cdot (-0,0334\cdot sin(\frac{2\pi}{365,24}\cdot dn)+0,04184\cdot sin(2\cdot \frac{2\pi}{365,24}\cdot dn+3,5884))$ \nomenclature[EoT]{\(EoT\)}{Ecuación del tiempo}

Esta irradiancia extra-terrestre solo tiene componentes geométicas. De modo que, si integramos la ecuación [[ref:eq:irrad_horiz]], se obtiene la irradiación diaria extra-terrestre:
#+begin_export latex
\begin{equation}
B_{0d}(0)=-\frac{T}{\pi}B_0\epsilon_0(\omega_s sin\phi sin\delta + cos\phi cos\delta sin \omega_s)
\label{eq:irrad_dia}
\end{equation}
#+end_export
Siendo:
- Ángulo del amananecer: \nomenclature[omegas]{\(\omega_s\)}{Ángulo del amanecer}
  \[
  \omega_s=\begin{cases}
  -\arccos(-\tan\delta\tan\phi)& \text{si $|\tan\delta\tan\phi|<1$}\\
  -\pi& \text{si $-\tan\delta\tan\phi<-1$}\\
  0& \text{si $-\tan\delta\tan\phi>1$}
  \end{cases}\]

Es posible demostrar que el promedio mensual de esta irradiación diaria coincide numéricamente con el valor de irradiación diaria correspondiente a los denominados "días promedios", días en los que la declinación correpondiente coincide con el promedio mensual (tabla [[ref:tab:DiasPromedio]])
#+begin_export latex
\begin{center}
{\footnotesize }%
\begin{table}[h]
{\footnotesize \caption{Valor $d_{n}$ correspondiente a los doce días promedio.\label{tab:DiasPromedio}}
}{\footnotesize \par}

\centering{}{\footnotesize }\begin{tabular}{>{\centering}p{6mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{3mm}}
\toprule 
{\footnotesize Mes} & {\footnotesize Ene} & {\footnotesize Feb} & {\footnotesize Mar} & {\footnotesize Abr} & {\footnotesize May} & {\footnotesize Jun} & {\footnotesize Jul} & {\footnotesize Ago} & {\footnotesize Sep} & {\footnotesize Oct} & {\footnotesize Nov} & {\footnotesize Dic}\tabularnewline
\midrule
$d_{n}$ & {\footnotesize 17} & {\footnotesize 45} & {\footnotesize 74} & {\footnotesize 105} & {\footnotesize 135} & {\footnotesize 161} & {\footnotesize 199} & {\footnotesize 230} & {\footnotesize 261} & {\footnotesize 292} & {\footnotesize 322} & {\footnotesize 347}\tabularnewline
\bottomrule
\end{tabular}
\end{table}

\par\end{center}{\footnotesize \par}
#+end_export

** Cálculo de componentes de radiación solar
Para caracterizar la radiación solar en un lugar, Liu y Jordan [[cite:Liu.Jordan1960]] propusieron el índice de claridad, \(K_T\). Este índice es la relación entre la radiación global y la radiación extra-atmosférica, ambas en el plano horizontal. El índice de claridad diario es la relación entre los valores diarios de irradiación: \nomenclature[KT]{\(K_T\)}{Índice de claridad} \nomenclature[KTd]{\(K_{Td}\)}{Índice de claridad diario}
#+begin_export latex
\begin{equation}
K_{Td}=\frac{G_d(0)}{B_{0d}(0)}
\label{eq:ind-cla-dia}
\end{equation}
#+end_export 
mientras que el índice de claridad mensual es la relación entre las medias mensuales de la irradiación diaria: \nomenclature[KTm]{\(K_{Tm}\)}{Índice de claridad mensual}
#+begin_export latex
\begin{equation}
K_{Tm}=\frac{G_{d,m}(0)}{B_{0d,m}(0)}
\label{eq:ind-cla-men}
\end{equation}
#+end_export

Una vez se tiene el índice de claridad, se puede calcular la fracción de radiación difusa en el plano horizontal. En el caso de medias mensuales [[cite:Page1961]]:
#+begin_export latex
\begin{equation}
F_{Dm}=1-1,13\cdot K_{Tm}
\end{equation}
#+end_export
Donde:
- Fracción de radiación difusa: $F_D=\frac{D(0)}{G(0)}$ \nomenclature[FD]{\(F_D\)}{Fracción de difusa} \nomenclature[FDd]{\(F_{Dd}\)}{Fracción de difusa diaria} \nomenclature[FDm]{\(F_{Dm}\)}{Fracción de difusa mensual}

Al tener la fracción de radiación difusa, se pueden obtener los valores de la radiación directa y difusa en el plano horizontal:
#+begin_export latex
\begin{equation}
D_d(0)=F_D\cdot G_d(0)
\label{dif-rad}
\end{equation}
\begin{equation}
B_d(0)=G_d(0)-D_d(0)
\label{dir-rad}
\end{equation}
#+end_export

* Radiación en superficies inclinadas
Dados los valores de irradiación diaria difusa, directa y global en el plano horizontal se puede realizar la transformación al plano inclinado. Para ello, es necesario estimar el perfil de irradiancia correspondiente a cada valor de irradiación. dado que la variación solar durante una hora es baja, podemos suponer que el valor medio de la irradiancia durante esa hora coincide numéricamente con la irradiación horaria. Por otra parte, el análisis de valores /medios/  en /largas/ series temporales ha mostrado que la relación entre la irradiancia y la irradición extra-atmosférica [[cite:Collares-Pereira.Rabl1979]] ([[ref:eq:rel-dif]]):
#+begin_export latex
\begin{equation}
r_D=\frac{D(0)}{D_d(0)}=\frac{B_0(0)}{B_{0d}(0)}
\label{eq:rel-dif}
\end{equation}
#+end_export
Este factor \(r_D\)\nomenclature[rD]{\(r_D\)}{Relación entre la irradiancia y la irradiación difusa en el plano horizontal} es calculable directamente sabiendo que la relación entre irradiancia e irradiación extra-atmosférica es deducible teóricamente a partir de las ecuaciones [[ref:eq:irrad_horiz]] [[ref:eq:irrad_dia]]:
#+begin_export latex
\begin{equation}
\frac{B_0(0)}{B_{0d}(0)}=\frac{\pi}{T}\cdot \frac{cos(\omega)-cos(\omega_s)}{\omega_s\cdot cos(\omega_s)-sin(\omega_s)}=r_D
\label{eq:rel-dif2}
\end{equation}
#+end_export
el mismo análisis mostró una relación entre la irradiancia e irradiación global asimilable a una función dependiente de la hora solar ([[ref:eq:rel-glo]]):
#+begin_export latex
\begin{equation}
r_G=\frac{G(0)}{G_d(0)}=r_D\cdot(a+b\cdot cos(w))
\label{eq:rel-glo}
\end{equation}
#+end_export
Donde:
- $a=0,409-0,5016\cdot sin(\omega_s+\frac{\pi}{3})$
- $b=0,6609+0,4767\cdot sin(\omega_s+\frac{\pi}{3})$

Es importante resaltar que estos perfiles proceden de medias sobre largos períodos, y de ahí que, como es observable en la figura [[fig:Perfil-de-irradiancia]], las fluctuaciones propias del movimiento de nubes a lo largo del día queden atenuadas y se obtenga una curva sin alteraciones.
#+NAME: fig:Perfil-de-irradiancia
#+CAPTION: Perfil de irradiancia difusa y global obtenido a partir del generador empírico de [[cite:Collares-Pereira.Rabl1979]] para valores de irradiancia tomadas cada 10 minutos
#+ATTR_LATEX: :height 0.5\textheight :width 0.9\textwidth :options keepaspectratio
[[file:figuras/RgRd.pdf]]

** Transformación al plano del generador
Una vez otenidos los valores de irradiancia en el plano horizontal, se traspone al plano del generador:
- *Irradiancia Directa* $B(\beta ,\alpha)$: Ecuación basada en geometríasolar (ángulo zenital) y del generador (ángulo de incidencia).
  #+begin_export latex
  \begin{equation}
  B(\beta ,\alpha)=B(0)\cdot \frac{max(0,cos(\theta_s))}{cos(\theta_{zs})}
  \label{eq:irradiancia-directa-plano-generador}
  \end{equation}
  #+end_export
- *Irradiancia Difusa* $D(\beta ,\alpha)$: Utilizando el modelo de cielo anisotrópico [[cite:Perpinan2023]], se distinguen dos componentes de la irradiancia difusa, denominados /circunsolar/ e /isotrópica/. \nomenclature[DI]{\(D^I\)}{Radiación difusa isotrópica} \nomenclature[DC]{\(D^C\)}{Radiación difusa circunsolar}
  #+begin_export latex
  \begin{equation}
  D(\beta ,\alpha)=D^I(\beta ,\alpha)+D^C(\beta ,\alpha)
  \end{equation}
  \begin{equation}
  D^I(\beta ,\alpha)=D(0)(1-k_1)\cdot \frac{1+cos(\beta)}{2}
  \end{equation}
  \begin{equation}
  D^C(\beta, \alpha)=D(0)\cdot k_1\cdot \frac{max(0,cos(\theta_s))}{cos(\theta_{zs})}
  \end{equation}
  #+end_export
  Donde:
  - $k_1=\frac{B(n)}{B_0\cdot \epsilon_0}=\frac{B(0)}{B_0(0)}$
- *Irradiancia de albedo* $R(\beta ,\alpha)$: Se considera isotrópica debido a su baja contribución a la radiación global. Se calcula a partir de la irradiancia global en el plano horizontal usando un coeficiente de reflexión, \(\rho\)\nomenclature[rho]{\(\rho\)}{Coeficiente de reflexión del terreno para la irradiancia de albedo}, que depende del terreno. En la ecuación [[ref:eq:albedo-plano-generador]], se utiliza el factor $\frac{1-cos(\beta)}{2}$, complemetario al factor de visión de la difusa isotrópica (figura [[fig:AnguloVisionCielo]])
  #+begin_export latex
  \begin{equation}
  R(\beta ,\alpha)=\rho \cdot G(0)\cdot \frac{1 - cos(\beta)}{2}
  \label{eq:albedo-plano-generador}
  \end{equation}
  #+end_export
  #+NAME: fig:AnguloVisionCielo
  #+CAPTION: Ángulo de visión del cielo
  #+ATTR_LATEX: :height 0.5\textheight :width 0.9\textwidth :options keepaspectratio
  [[file:figuras/AnguloVisionCielo.pdf]]

* Operaciones del paquete =solaR2=
En la figura [[fig:prod-solar2]], se muestra el proceso de cálculo que sigue el paquete a la hora de obtener la estimación de la producción del sistema fotovoltaico.
#+ATTR_LATEX: :height 0.5\textheight :width 0.9\textwidth :options keepaspectratio
#+CAPTION: Proceso de cálculo de las funciones de =solaR2=
#+NAME: fig:prod-solar2
[[file:figuras/procedure.pdf]]
A la hora de estimar la producción, el programa sigue los siguientes procesos:
1. Se calcula la geometría que definen la posición de la Tierra frente al Sol.
   1. Mediante la función fSolD, se calcula:
      - El ángulo de declinación de la Tierra (\(\delta\)).
      - La corrección debida a la excentricidad de la elipse de la trayectoria terrestre alrededor del sol (\(\epsilon_0\)).
      - La ecuación del tiempo (\(EoT\)).
      - El ángulo del amanecer 
   2. Mediante la función fSolI, se calcula:
      - La hora solar (\(\omega\)).
      - El momento del día en el que es de noche.
      - El ángulo zenital solar (\(\theta_{zs}\)).
      - El ángulo de altura solar (\(\gamma_s\).
      - El ángulo azimutal solar (\(\psi_s\)).
      - La irradiancia extra-terrestre en el plano horizontal (\(B_0(0)\)).
   3. El resultado de ambas funciones se juntan en un solo objeto de clase =Sol= mediante la función calcSol.
2. Se estima la radiación en el plano horizontal.
   1. La información de irradiación en el plano horizontal (en todos sus componentes o, en su defecto, solo la global(\(G_d(0)\))) y temperatura viene dada en un objeto de clase =Meteo=.
   2. Mediante la función fCompD, se calcula:
      - La fracción de radiación difusa diaria (\(F_{Dd}\)).
      - El índice de claridad diario (\(K_{Td}\)).
      - Si solo se tienen datos de la componente global de irradición:
	- La irradiación directa en el plano horizontal (\(B_d(0)\)).
	- La irradiación difusa en el plano horizontal (\(D_d(0)\)).
   3. Mediante la función fCompI, se calcula:
      - La fracción de radiación difusa (\(F_D\)).
      - El índice de claridad (\(K_T\)).
      - Si solo se tienen datos de la componenete global de irradiancia (\(G(0)\)):
	- La irradiancia directa en el plano horizontal (\(B(0)\)).
	- La irradiancia difusa en el plano horizontal (\(D(0)\)).
   4. El resultado de ambas funciones junto a medias mensuales y valores anuales se consolidan en un solo objeto de clase =G0= (que incluye los objetos =Sol= y =Meteo= de los que parte) mediante la función calcG0.
3. Se estima la radiación en el plano del generador.
   1. La información de radiación puede venir dada en forma de un objeto de clase =Meteo= o un objeto de clase =G0= (ya que es este último el que se necesita para estimar la radiación en el plano del generador).
   2. Mediante la función fTheta, se calcula:
      - Ángulo de inclinación de la superficie del módulo (\(\beta\)).
      - Ángulo azimutal de la superficie del módulo (\(\alpha\) ).
      - Ángulo de incidencia de la irradiancia solar en la superficie del módulo (\(\theta_s\)).
   3. Mediante la función fInclin, se calcula:
      - La irradiancia extra-terrestre en la superficie inclinada (\(B_0(\beta, \alpha)\)).
      - La irradiancia directa normal (\(B(n)\)).
      - Las irradiancias global (\(G(\beta, \alpha)\)), directa (\(B(\beta, \alpha)\)), difusa (\(D(\beta, \alpha)\))(total, isotropica y anisotrópica) y del albedo (\(R(\beta, \alpha)\)) sobre una superficie inclinada.
      - Las irradiancias efectivas global (\(G_{ef}(\beta, \alpha)\)), directa (\(B_{ef}(\beta, \alpha)\)), difusa (\(D_{ef}(\beta, \alpha)\))(total, isotropica y anisotrópica) y del albedo (\(R_{ef}(\beta, \alpha)\)) sobre una superficie inclinada.
      - Los factores de pérdidas angulares para las componentes directa (\(FT\)), difusa (\(FT_D\)), y del albedo (\(FT_R\)).
   4. Mediante la función calcShd, se puede calcular:
      - La irradiancia e irradiación incluyendo sombras para seguidores a dos ejes y horizontales y paneles fijos mediante la función fSombra.  
   5. El resultado de estas funciones junto a medias mensuales y valores anuales se consolidan en un solo objeto de clase =Gef= (que incluye el objeto =G0= del que parte) mediante la función calcGef.
4. Se estima la producción eléctrica.
   1. Mediante la función fProd, se calcula:
      - La potencia en corriente continua (\(P_{DC}\)).
      - La potencia en corriente alterna (\(P_{AC}\).
   2. Estos resultados, llevados a valores diarios, mensuales y anuales, se pueden convertir en valores de energía (\(E_{DC}\) y \(E_{AC}\)) y de productividad del sistema (\(Y_f\)), los cuales se consolidan en un solo objeto de clase =ProdGCPV= (que incluye el objeto =Gef= del que parte) mediante la función prodGCPV.
      





* Footnotes
[fn:2] Se van a utilizar las ecuaciones propuestas por P.I. Cooper [[cite:Cooper1969]] por su simpleza.

[fn:1] Para las ecuaciones de este apartado se va a optar por poner la ecuación más simple posible. Sin embargo, el paquete =solaR2= otorga la posibilidad de realizar los cálculos de utilizando las ecuaciones propuestas por 4 autores diferentes.

