\chapter{Parte teórica y desarrollo del código}
label:chap:marcoteorico
El paquete =solaR2= toma como marco teórico el libro de Oscar Perpiñán, tutor de este trabajo, Energía Solar Fotovoltaica \cite{Perpinan2023} para cada una de las operaciones de cálculo que realizan cada una de las funciones.
En la figura [[fig:prod-calculo]], se muestra un diagrama que resume los pasos que se siguen a la hora de calcular la producción de sistemas fotovoltaicos.
#+CAPTION: Procedimiento de cálculo
#+NAME: fig:prod-calculo
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio
[[file:figuras/ProcedimientoCalculoRadiacionInclinada.pdf]]
Estos pasos son:
1. Obtener la irradiación global diaria en el plano horizontal
2. A partir de la irradiación global, obtener las componentes de difusa y directa.
3. Se trasladan estos valores de irradición a valores de irradiancia.
4. Con estos valores se pueden obtener los valores correspondientes en el plano del generador
   1. Sin los efectos de la suciedad de los modulos y las sombras que se generan unos con otros.
   2. Con estos efectos
5. Integrando estos valores se pueden obtener las estimaciones irradiación diaria difusa, directa y global
6. El generador fotovoltaico produce una potencia en corriente continua dependiente del rendimiento del mismo..
7. Se transforma en potencia en corriente alterna mediante un inversor que tiene una eficiencia asociada.
8. Integrando esta potencia se puede obtener la energía que produce el generador en un tiempo determinado.

* Naturaleza de la radiación solar
label:sec:radiaciónsolar
Para el cálculo de la radiación solar que incide en una superficie se deben distinguir tres componentes diferenciados:
- *Radiación Directa*, B\nomenclature[B]{\(B\)}{Radiación directa}: porción de radiación que procede en línea recta desde el Sol.
- *Radiación Difusa*, D\nomenclature[D]{\(D\)}{Radiación difusa}: fracción de radiación que procede de todo el cielo, excepto del Sol. Son todos aquellos rayos que dispersa la atmósfera.
- *Radiación del albedo*, R\nomenclature[R]{\(R\)}{Radiación del albedo}: parte de la radiación procedente de la reflexión con el suelo.
La suma de las tres componentes constituye la denominada radiación global: \nomenclature[G]{\(G\)}{Radiación global}
#+begin_export latex  
\begin{equation}
G = B + D + R
\label{eq:comp_rad}
\end{equation}
#+end_export
Tomando como base el libro antes mencionado [[cite:Perpinan2023]], se describirá el proceso que se ha de seguir para obtener una estimación de las componenetes directa y difusa a partir del dato de radiación global, dado que es el que comúnmente se puede obtener de una localización determinada.

** Radiación fuera de la atmósfera terrestre
Lo primero que se menciona en dicho proceso es la obtención de la irradiancia denominda extra-terrestre o extra-atmosférica, que es la radiación que llega a la atmósfera, directamente desde el Sol, que no sufre ninguna pérdida por interaccionar con algún medio. Como la relación entre el tamaño de nuesto plenta y la distancia entre el Sol y la Tierra es muy reducida, es posible asumir que el valor de dicha irradiancia es constante, siendo este valor $B_0=1367\frac{W}{m^2}$, según varias mediciones.
Como la órbita que describe la Tierra alrededor del Sol no es totalmente circular, sino que tiene forma de elipse, para calcular la irradiancia incidente en una superficie tangente a la atmosfera en ua latitud concreta, debemos aplicar un facot de correción de la excentricidad de la elipse:
#+begin_export latex
\begin{equation}
B_0(0)=B_0\epsilon_0cos\theta_{zs}
\label{eq:irrad_horiz}
\end{equation}
#+end_export
Siendo cada componente:
- Irradiancia extra-terrestre: $B_0=1367\frac{W}{m^2}$ \nomenclature[B0]{\(B_0\)}{Irradiancia extra-atmosférica o extra-terrestre}
- Factor de corrección por excentricidad: $\epsilon_0=(\frac{r_0}{r})^2=1+0.033\cdot cos(\frac{2\pi d_n}{365})$[fn:1] \nomenclature[epsilon0]{\(\epsilon_0\)}{Corrección debida a la excentricidad de la elipse de la trayectoria terrestre alrededor del sol}
- Ángulo zenital solar: $cos(\theta_{zs})=cos(\delta)cos(\omega)cos(\phi)+sin(\delta)+sin(\phi)$[fn:2] \nomenclature[thetazs]{\(\theta_{zs}\))}{Ángulo cenital solar}

  Donde:
  - Declinación: $\delta =23,45º\cdot sin(\frac{2\pi \cdot (d_n+284)}{365})$ \nomenclature[delta]{\(\delta\)}{Declinación}
  - Latitud: \(\phi\) \nomenclature[phi]{\(\phi\)}{Latitud}
  - Hora solar o tiempo solar verdadero: $\omega = 15\cdot (TO-AO-12)+\Delta \lambda +\frac{EoT}{4}$ \nomenclature[omega]{\(\omega\)}{Hora solar o tiempo solar verdadero}

    Donde:
    - Hora oficial: \(TO\) \nomenclature[TO]{\(TO\)}{Hora oficial}
    - Adelanto oficial durante el horario de verano: \(AO\) \nomenclature[AO]{\(AO\)}{Adelanto oficial durante el horario de verano}
    - Diferencia entre la longitud local y la longitud del huso horario: \(\Delta \lambda\) \nomenclature[deltalambda]{\(\Delta \lambda\)}{Diferencia entre la longitud local y la longitud del huso horario}
    - Ecuación del tiempo: $EoT=229,18\cdot (-0,0334\cdot sin(\frac{2\pi}{365,24}\cdot dn)+0,04184\cdot sin(2\cdot \frac{2\pi}{365,24}\cdot dn+3,5884))$ \nomenclature[EoT]{\(EoT\)}{Ecuación del tiempo}

Esta irradiancia extra-terrestre solo tiene componentes geométicas. De modo que, si integramos la ecuación [[ref:eq:irrad_horiz]], se obtiene la irradiación diaria extra-terrestre:
#+begin_export latex
\begin{equation}
B_{0d}(0)=-\frac{T}{\pi}B_0\epsilon_0(\omega_s sin\phi sin\delta + cos\phi cos\delta sin \omega_s)
\label{eq:irrad_dia}
\end{equation}
#+end_export
Siendo:
- Ángulo del amananecer: \nomenclature[omegas]{\(\omega_s\)}{Ángulo del amanecer}
  \[
  \omega_s=\begin{cases}
  -\arccos(-\tan\delta\tan\phi)& \text{si $|\tan\delta\tan\phi|<1$}\\
  -\pi& \text{si $-\tan\delta\tan\phi<-1$}\\
  0& \text{si $-\tan\delta\tan\phi>1$}
  \end{cases}\]

Es posible demostrar que el promedio mensual de esta irradiación diaria coincide numéricamente con el valor de irradiación diaria correspondiente a los denominados "días promedios", días en los que la declinación correpondiente coincide con el promedio mensual (tabla [[ref:tab:DiasPromedio]])
#+begin_export latex
\begin{center}
{\footnotesize }%
\begin{table}[h]
{\footnotesize \caption{Valor $d_{n}$ correspondiente a los doce días promedio.\label{tab:DiasPromedio}}
}{\footnotesize \par}

\centering{}{\footnotesize }\begin{tabular}{>{\centering}p{6mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{3mm}}
\toprule 
{\footnotesize Mes} & {\footnotesize Ene} & {\footnotesize Feb} & {\footnotesize Mar} & {\footnotesize Abr} & {\footnotesize May} & {\footnotesize Jun} & {\footnotesize Jul} & {\footnotesize Ago} & {\footnotesize Sep} & {\footnotesize Oct} & {\footnotesize Nov} & {\footnotesize Dic}\tabularnewline
\midrule
$d_{n}$ & {\footnotesize 17} & {\footnotesize 45} & {\footnotesize 74} & {\footnotesize 105} & {\footnotesize 135} & {\footnotesize 161} & {\footnotesize 199} & {\footnotesize 230} & {\footnotesize 261} & {\footnotesize 292} & {\footnotesize 322} & {\footnotesize 347}\tabularnewline
\bottomrule
\end{tabular}
\end{table}

\par\end{center}{\footnotesize \par}
#+end_export
 
** Cálculo de componentes de radiación solar
Para caracterizar la radiación solar en un lugar, Liu y Jordan [[cite:Liu.Jordan1960]] propusieron el índice de claridad, \(K_T\). Este índice es la relación entre la radiación global y la radiación extra-atmosférica, ambas en el plano horizontal. El índice de claridad diario es la relación entre los valores diarios de irradiación: \nomenclature[KT]{\(K_T\)}{Índice de claridad} \nomenclature[KTd]{\(K_{Td}\)}{Índice de claridad diario}
#+begin_export latex
\begin{equation}
K_{Td}=\frac{G_d(0)}{B_{0d}(0)}
\label{eq:ind-cla-dia}
\end{equation}
#+end_export 
mientras que el índice de claridad mensual es la relación entre las medias mensuales de la irradiación diaria: \nomenclature[KTm]{\(K_{Tm}\)}{Índice de claridad mensual}
#+begin_export latex
\begin{equation}
K_{Tm}=\frac{G_{d,m}(0)}{B_{0d,m}(0)}
\label{eq:ind-cla-men}
\end{equation}
#+end_export

Una vez se tiene el índice de claridad, se puede calcular la fracción de radiación difusa en el plano horizontal. En el caso de medias mensuales [[cite:Page1961]]:
#+begin_export latex
\begin{equation}
F_{Dm}=1-1,13\cdot K_{Tm}
\end{equation}
#+end_export
Donde:
- Fracción de radiación difusa: $F_D=\frac{D(0)}{G(0)}$ \nomenclature[FD]{\(F_D\)}{Fracción de difusa} \nomenclature[FDd]{\(F_{Dd}\)}{Fracción de difusa diaria} \nomenclature[FDm]{\(F_{Dm}\)}{Fracción de difusa mensual}

Al tener la fracción de radiación difusa, se pueden obtener los valores de la radiación directa y difusa en el plano horizontal:
#+begin_export latex
\begin{equation}
D_d(0)=F_D\cdot G_d(0)
\label{dif-rad}
\end{equation}
\begin{equation}
B_d(0)=G_d(0)-D_d(0)
\label{dir-rad}
\end{equation}
#+end_export

* Radiación en superficies inclinadas
label:sec:radiacionsuperficiesinclinadas
Dados los valores de irradiación diaria difusa, directa y global en el plano horizontal se puede realizar la transformación al plano inclinado. Para ello, es necesario estimar el perfil de irradiancia correspondiente a cada valor de irradiación. dado que la variación solar durante una hora es baja, podemos suponer que el valor medio de la irradiancia durante esa hora coincide numéricamente con la irradiación horaria. Por otra parte, el análisis de valores /medios/  en /largas/ series temporales ha mostrado que la relación entre la irradiancia y la irradición extra-atmosférica [[cite:Collares-Pereira.Rabl1979]] ([[ref:eq:rel-dif]]):
#+begin_export latex
\begin{equation}
r_D=\frac{D(0)}{D_d(0)}=\frac{B_0(0)}{B_{0d}(0)}
\label{eq:rel-dif}
\end{equation}
#+end_export
Este factor \(r_D\)\nomenclature[rD]{\(r_D\)}{Relación entre la irradiancia y la irradiación difusa en el plano horizontal} es calculable directamente sabiendo que la relación entre irradiancia e irradiación extra-atmosférica es deducible teóricamente a partir de las ecuaciones [[ref:eq:irrad_horiz]] [[ref:eq:irrad_dia]]:
#+begin_export latex
\begin{equation}
\frac{B_0(0)}{B_{0d}(0)}=\frac{\pi}{T}\cdot \frac{cos(\omega)-cos(\omega_s)}{\omega_s\cdot cos(\omega_s)-sin(\omega_s)}=r_D
\label{eq:rel-dif2}
\end{equation}
#+end_export
el mismo análisis mostró una relación entre la irradiancia e irradiación global asimilable a una función dependiente de la hora solar ([[ref:eq:rel-glo]]):
#+begin_export latex
\begin{equation}
r_G=\frac{G(0)}{G_d(0)}=r_D\cdot(a+b\cdot cos(w))
\label{eq:rel-glo}
\end{equation}
#+end_export
Donde:
- $a=0,409-0,5016\cdot sin(\omega_s+\frac{\pi}{3})$
- $b=0,6609+0,4767\cdot sin(\omega_s+\frac{\pi}{3})$

Es importante resaltar que estos perfiles proceden de medias sobre largos períodos, y de ahí que, como es observable en la figura [[fig:Perfil-de-irradiancia]], las fluctuaciones propias del movimiento de nubes a lo largo del día queden atenuadas y se obtenga una curva sin alteraciones.
#+NAME: fig:Perfil-de-irradiancia
#+CAPTION: Perfil de irradiancia difusa y global obtenido a partir del generador empírico de [[cite:Collares-Pereira.Rabl1979]] para valores de irradiancia tomadas cada 10 minutos
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio
[[file:figuras/RgRd.pdf]]

** Transformación al plano del generador
Una vez otenidos los valores de irradiancia en el plano horizontal, se traspone al plano del generador:
- *Irradiancia Directa* $B(\beta ,\alpha)$: Ecuación basada en geometríasolar (ángulo zenital) y del generador (ángulo de incidencia).
  #+begin_export latex
  \begin{equation}
  B(\beta ,\alpha)=B(0)\cdot \frac{max(0,cos(\theta_s))}{cos(\theta_{zs})}
  \label{eq:irradiancia-directa-plano-generador}
  \end{equation}
  #+end_export
- *Irradiancia Difusa* $D(\beta ,\alpha)$: Utilizando el modelo de cielo anisotrópico [[cite:Perpinan2023]], se distinguen dos componentes de la irradiancia difusa, denominados /circunsolar/ e /isotrópica/. \nomenclature[DI]{\(D^I\)}{Radiación difusa isotrópica} \nomenclature[DC]{\(D^C\)}{Radiación difusa circunsolar}
  #+begin_export latex
  \begin{equation}
  D(\beta ,\alpha)=D^I(\beta ,\alpha)+D^C(\beta ,\alpha)
  \end{equation}
  \begin{equation}
  D^I(\beta ,\alpha)=D(0)(1-k_1)\cdot \frac{1+cos(\beta)}{2}
  \end{equation}
  \begin{equation}
  D^C(\beta, \alpha)=D(0)\cdot k_1\cdot \frac{max(0,cos(\theta_s))}{cos(\theta_{zs})}
  \end{equation}
  #+end_export
  Donde:
  - $k_1=\frac{B(n)}{B_0\cdot \epsilon_0}=\frac{B(0)}{B_0(0)}$
- *Irradiancia de albedo* $R(\beta ,\alpha)$: Se considera isotrópica debido a su baja contribución a la radiación global. Se calcula a partir de la irradiancia global en el plano horizontal usando un coeficiente de reflexión, \(\rho\)\nomenclature[rho]{\(\rho\)}{Coeficiente de reflexión del terreno para la irradiancia de albedo}, que depende del terreno. En la ecuación [[ref:eq:albedo-plano-generador]], se utiliza el factor $\frac{1-cos(\beta)}{2}$, complemetario al factor de visión de la difusa isotrópica (figura [[fig:AnguloVisionCielo]])
  #+begin_export latex
  \begin{equation}
  R(\beta ,\alpha)=\rho \cdot G(0)\cdot \frac{1 - cos(\beta)}{2}
  \label{eq:albedo-plano-generador}
  \end{equation}
  #+end_export
  #+NAME: fig:AnguloVisionCielo
  #+CAPTION: Ángulo de visión del cielo
  #+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio
  [[file:figuras/AnguloVisionCielo.pdf]]

** Ángulo de incidencia y suciedad
En un módulo fotovoltaico, la radiación incidente generalmente no es perpendicular a la superficie del módulo, lo que provoca pérdidas por reflexión o pérdidas angulares, cuantificadas por el ángulo de incidencia \(\theta_s\)\nomenclature[thetas]{\(\theta_s\)}{Ángulo de incidencia o ángulo entre el vector solar y el vector director de una superficie}. La suciedad acumulada en la superficie del módulo también reduce la transmitancia del vidrio (representada por $T_{limpio}(0$)), disminuyendo la irradiancia efectiva, es decir, la radiación que realmente puede ser aprovechada por el módulo.
La irradiancia efectiva para radiación directa se expresa en la ecuación [[ref:eq:dir-ef]]:
#+begin_export latex
\begin{equation}
B_{ef}(\beta ,\alpha)=B(\beta ,\alpha)\cdot [\frac{T_{sucio}(0)}{T_{limpio}(0)}]\cdot (1-FTB(\theta_s))
\label{eq:dir-ef}
\end{equation}
#+end_export
donde $FTB(\theta_s)$ es el factor de pérdidas angulares, que se calcula con la ecuación [[ref:eq:factor-perdidas-directa]]: \nomenclature[FTB]{\(FT_B\)}{Factor de pérdidas angulares para irradiancia directa}\nomenclature[FTD]{\(FT_D\)}{Factor de pérdidas angulares para irradiancia difusa}\nomenclature[FTB]{\(FT_R\)}{Factor de pérdidas angulares para irradiancia de albedo}
#+begin_export latex
\begin{equation}
FTB(\theta_s)=\frac{exp(-\frac{cos(\theta_s)}{a_r})-exp(-\frac{1}{a_r})}{1-exp(-\frac{1}{a_r})}
\label{eq:factor-perdidas-directa}
\end{equation}
#+end_export
Este factor depende el ángulo de incidencia \(theta_s\) y del coeficiente de pérdidas angulares \(a_r\). Cuando la radiación es perpendicular a la superficie ($\theta_s=0$), \(FTB\) es cero. En la figura [[fig:PerdidasAngulares]] se puede observar que las pérdidas angulares son más significativas cuando \(\theta_s\) supera los 60º, y se acentúan con mayor suciedad.
#+NAME: fig:PerdidasAngulares
#+CAPTION: Pérdidas angulares de un módulo fotovoltaico para diferentes grados de suciedad en función del ángulo de incidencia.
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio 
[[file:figuras/Suciedad.pdf]]

Para calcular las componente de radiación difusa isotrópica y de albedo se utilizan las ecuaciones [[ref:eq:FTD]] y [[ref:eq:FTR]]:
#+begin_export latex
\begin{equation}
\text{FTD}(\beta) \approx exp[-\frac{1}{a_r}\cdot (c_1\cdot (sin\beta +\frac{\pi -\beta - sin\beta}{1+cos\beta})+c_2\cdot (sin\beta +\frac{\pi -\beta -sin\beta}{1+cos\beta})^2)]
\label{eq:FTD}
\end{equation}
#+end_export
#+begin_export latex
\begin{equation}
\text{FTR}(\beta) \approx exp[-\frac{1}{a_r}\cdot (c_1\cdot (sin\beta +\frac{\beta - sin\beta}{1-cos\beta})+c_2\cdot (sin\beta +\frac{\beta -sin\beta}{1-cos\beta})^2)]
\end{equation}
\label{eq:FTR}
#+end_export
Donde:
- Ángulo de inclinación del generador (en radianes): \(\beta\) \nomenclature[beta]{\(\beta\)}{Ángulo de inclinación de un sistema fotovoltaico}
- Coeficiente de pérdidas angulares: \(a_r\)
- Coeficientes de ajuste: \(c_1\) y \(c_2\) (en la tabla [[ref:tab:coef-perd]] se recogen algunos valores característicos de un módulo de silicio monocristalino convencional para diferentes grados de suciedad)
#+CAPTION: Valores del coeficiente de pérdidas angulares y transmitancia relativa en incidencia normal para diferentes tipos de suciedad. label:tab:coef-perd
|-------------------+--------------------------------------+------+--------|
| Grado de suciedad | $\frac{T_{sucio}(0)}{T_{limpio}(0)}$ |  a_r |    c_2 |
|-------------------+--------------------------------------+------+--------|
| Limpio            |                                    1 | 0.17 | -0.069 |
|-------------------+--------------------------------------+------+--------|
| Bajo              |                                 0.98 | 0.20 | -0.054 |
|-------------------+--------------------------------------+------+--------|
| Medio             |                                 0.97 | 0.21 | -0.049 |
|-------------------+--------------------------------------+------+--------|
| Alto              |                                 0.92 | 0.27 | -0.023 |
|-------------------+--------------------------------------+------+--------|


Para estas componenetes el cálculo de irradiancia efectiva es similar al de la irradiancia directa (ecuaciones [[ref:eq:dif-ef-iso]] y [[ref:eq:alb-ef]]). Para la componente difusa circunsolar emplearemos el factor de pérdidas angulares de la irradiancia efectiva(ecuacion [[ref:eq:dif-ef-cir]]):
#+begin_export latex
\begin{equation}
D_{ef}^I(\beta ,\alpha)=D^I(\beta ,\alpha)\cdot[\frac{T_{sucio}(0)}{T_{limpio}(0)}]\cdot (1-FT_D(\beta))
\label{eq:dif-ef-iso}
\end{equation}
\begin{equation}
D_{ef}^C(\beta ,\alpha)=D^C(\beta ,\alpha)\cdot[\frac{T_{sucio}(0)}{T_{limpio}(0)}]\cdot (1-FT_B(\theta_s))
\label{eq:dif-ef-cir}
\end{equation}
\begin{equation}
R_{ef}(\beta ,\alpha)=R(\beta ,\alpha)\cdot[\frac{T_{sucio}(0)}{T_{limpio}(0)}]\cdot (1-FT_R(\beta))
\label{eq:alb-ef}
\end{equation}
#+end_export
Siguiendo el esquema de la figura [[fig:prod-calculo]], a partir de estas irradiancias efectivas se puede calcular la irradiación global efectiva diaria, mensual y anual. Comparando la irradiación global incidente con la irradición efectiva, se puede evaluar el impacto de la suciedad y el desajuste del ángulo en períoods prolongados.

* Cálculo de la energía producida por el generador

** Funcionamiento de una célula solar
Para calcular la energía producida por un generador fotovoltaico, se deben tener en cuenta la influencia de factores tales como la radiación o la temperatura en una célula solar y en los valores de tensión y corriente que se alcanzan en dichas condiciones.

Para definir una célula solar, se tomar 4 variables:
- La corriente de cortocircuito: \(I_{sc}\)\nomenclature[Isc]{\(I_{sc}\)}{Corriente de cortocircuito de una célula}
- La tensión de circuito abierto: \(V_{oc}\)\nomenclature[VOC]{\(V_{oc}\)}{Tensión de circuito abierto de una célula}
- La corriente en el punto de máxima potencia: \(I_{mpp}\)\nomenclature[Impp]{I_{mpp}}{Corriente de una célula en el punto de máxima potencia}
- La tensión en el punto de máxima potencia: \(V_{mpp}\)\nomenclature[Vmpp]{V_{mpp}}{Tensión de una célula en el punto de máxima potencia}

*** Punto de máxima potencia
El punto de máxima potencia es aquel situado en la curva de funcionamiento del generador donde, como su propio nombre indica, los valores de tensión y corriente son tales que la potencia que entrega es máxima (figura [[fig:iv-20-800]]).
#+CAPTION: Curvas corriente-tensión(línea discontinua) y potencia-tensión(línea continua) de una célula solar ($T_a=20ºC$ y $G=800 w/m^2$)
#+NAME: fig:iv-20-800
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio 
[[file:figuras/CurvaIV_Ta20_G800.pdf]]

*** Factor de forma y eficiencia
El área encerrada por el rectángulo definido por el producto $I_{mpp}\cdot V_{mpp}$ es, como e observable en la figura [[fig:iv-20-800]], inferiro a la respresentada por el producto $I_{sc}\cdot V_{oc}$. La relación entre estad dos superficies se cuantifica con el factor de forma:\nomenclature[MPP]{MPP}{Punto de máxima potencia de un dispositivo fotovoltaico}
#+begin_export latex
\begin{equation}
FF=\frac{I_{mpp}\cdot V_{mpp}}{I_{sc}\cdot V_{oc}}
\end{equation}
#+end_export

Conociendo los valores de $I_{sc}$ y $V_{oc}$ es posible calcular la potencia en el punto de máxima potencia, dado que $P_{mpp}=FF\cdot I_{sc}\cdot V_{oc}$.

Por otra parte, la calidad de una célula se puede cuantificar con la eficiencia de conversión (ecuación ).
#+begin_export latex
\begin{equation}
\eta =\frac{I_{mpp}\cdot V_{mpp}}{P_L}
\label{eq:efi-cel}
\end{equation}
#+end_export
donde $P_L=A_c\cdot G_{ef}$ representa la potencia luminosa que incide en la célula\nomenclature[Ac]{\(A_c\)}{Área de una célula}.Como es evidente de la ecuación [[ref:eq:efi-cel]], este valor de eficiencia se corresponde al caso en el que el acoplamiento entre la carga y la célula permite a ésta trabajar en el punto de máxima potencia. En la figura [[fig:nrel-cell]] se muestra la evolución temporal del valor de eficiencia de célula de laboratorio para diferentes tecnologías.

#+CAPTION: Evolución de la eficiencia de células según la tecnología (según el National Renewable Energy Laboratory [[cite:nrel24]] (EEUU)).
#+NAME: fig:nrel-cell
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio
[[file:figuras/cell-efficiencies.pdf]]

*** Influencia de la temperatura y la radiación
Es importante tener en cuenta, a la hora de entender el funcionamiento de una célula solar, la influencia de los dos principales facotres externos: la temperatura ambiente y la iluminación incidente o radiación.

El aumento de la temperatura tiene una influencia notable en la tensión de circuito abierto de la célula según el valor $dV_{oc}/dT_c$. Donde $T_c$ es la temperatura de la célula\nomenclature[Tc]{\(T_c\)}{Temperatura de célula}, dependiente de la termperatura ambiente y la radiación incidente. La forma de calclar ésta temperatura depende de las características constructivas del módulo que encapsula a la célula. Si el fabricante no nos ofrece información sobre este valor, para células de silicio cristalino es común tomar el siguiente valor:
#+begin_export latex
\begin{equation}
\frac{dV_{oc}}{dT_c}=-2,3\frac{mV}{ºC}
\end{equation}
#+end_export
Sin embargo, el efecto que teien la irradiancia sobre la tensión de circuito abierto es mucho menos que el de la temperatura.

** Definición de un SFCR
Un Sistema Fotovoltaico Conectado a Red (SFCR) es un sistema cuya función es producir energía eléctrica en unas condiciones específicas, de tal manera que ésta pueda ser inyectada en la red eléctrica convencional. Para ello, un SFCR se compone del propio generador fotovoltaico, un inversor DC/AC y un conjunto de protecciones eléctricas (figura [[fig:esquema-sfcr]]).
#+NAME: fig:esquema-sfcr
#+CAPTION: Esquema de un SFCR.
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio 
[[file:figuras/EsquemaSFCR.pdf]]

La energía producida por el sistema es consumida total o parcialmente en las cercanías, y la energía sobrante será inyectada en la red para su distribución a otros puntos de consumo. Es común que existan mecanismos de retribución económica que compensan al propietario del sistema por la energía que sus sistema intercambia con la red.




* Operaciones del paquete =solaR2=
En la figura [[fig:prod-solar2]], se muestra el proceso de cálculo que sigue el paquete a la hora de obtener la estimación de la producción del sistema fotovoltaico.
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio
#+CAPTION: Proceso de cálculo de las funciones de =solaR2=
#+NAME: fig:prod-solar2
[[file:figuras/procedure.pdf]]
A la hora de estimar la producción, el programa sigue los siguientes procesos:
1. Se calcula la geometría que definen la posición de la Tierra frente al Sol.
   1. Mediante la función fSolD, se calcula:
      - El ángulo de declinación de la Tierra (\(\delta\)).
      - La corrección debida a la excentricidad de la elipse de la trayectoria terrestre alrededor del sol (\(\epsilon_0\)).
      - La ecuación del tiempo (\(EoT\)).
      - El ángulo del amanecer 
   2. Mediante la función fSolI, se calcula:
      - La hora solar (\(\omega\)).
      - El momento del día en el que es de noche.
      - El ángulo zenital solar (\(\theta_{zs}\)).
      - El ángulo de altura solar (\(\gamma_s\).
      - El ángulo azimutal solar (\(\psi_s\)).
      - La irradiancia extra-terrestre en el plano horizontal (\(B_0(0)\)).
   3. El resultado de ambas funciones se juntan en un solo objeto de clase =Sol= mediante la función calcSol.
2. Se estima la radiación en el plano horizontal.
   1. La información de irradiación en el plano horizontal (en todos sus componentes o, en su defecto, solo la global(\(G_d(0)\))) y temperatura viene dada en un objeto de clase =Meteo=.
   2. Mediante la función fCompD, se calcula:
      - La fracción de radiación difusa diaria (\(F_{Dd}\)).
      - El índice de claridad diario (\(K_{Td}\)).
      - Si solo se tienen datos de la componente global de irradición:
	- La irradiación directa en el plano horizontal (\(B_d(0)\)).
	- La irradiación difusa en el plano horizontal (\(D_d(0)\)).
   3. Mediante la función fCompI, se calcula:
      - La fracción de radiación difusa (\(F_D\)).
      - El índice de claridad (\(K_T\)).
      - Si solo se tienen datos de la componenete global de irradiancia (\(G(0)\)):
	- La irradiancia directa en el plano horizontal (\(B(0)\)).
	- La irradiancia difusa en el plano horizontal (\(D(0)\)).
   4. El resultado de ambas funciones junto a medias mensuales y valores anuales se consolidan en un solo objeto de clase =G0= (que incluye los objetos =Sol= y =Meteo= de los que parte) mediante la función calcG0.
3. Se estima la radiación en el plano del generador.
   1. La información de radiación puede venir dada en forma de un objeto de clase =Meteo= o un objeto de clase =G0= (ya que es este último el que se necesita para estimar la radiación en el plano del generador).
   2. Mediante la función fTheta, se calcula:
      - Ángulo de inclinación de la superficie del módulo (\(\beta\)).
      - Ángulo azimutal de la superficie del módulo (\(\alpha\) ).
      - Ángulo de incidencia de la irradiancia solar en la superficie del módulo (\(\theta_s\)).
   3. Mediante la función fInclin, se calcula:
      - La irradiancia extra-terrestre en la superficie inclinada (\(B_0(\beta, \alpha)\)).
      - La irradiancia directa normal (\(B(n)\)).
      - Las irradiancias global (\(G(\beta, \alpha)\)), directa (\(B(\beta, \alpha)\)), difusa (\(D(\beta, \alpha)\))(total, isotropica y anisotrópica) y del albedo (\(R(\beta, \alpha)\)) sobre una superficie inclinada.
      - Las irradiancias efectivas global (\(G_{ef}(\beta, \alpha)\)), directa (\(B_{ef}(\beta, \alpha)\)), difusa (\(D_{ef}(\beta, \alpha)\))(total, isotropica y anisotrópica) y del albedo (\(R_{ef}(\beta, \alpha)\)) sobre una superficie inclinada.
      - Los factores de pérdidas angulares para las componentes directa (\(FT\)), difusa (\(FT_D\)), y del albedo (\(FT_R\)).
   4. Mediante la función calcShd, se puede calcular:
      - La irradiancia e irradiación incluyendo sombras para seguidores a dos ejes y horizontales y paneles fijos mediante la función fSombra.  
   5. El resultado de estas funciones junto a medias mensuales y valores anuales se consolidan en un solo objeto de clase =Gef= (que incluye el objeto =G0= del que parte) mediante la función calcGef.
4. Se estima la producción eléctrica.
   1. Mediante la función fProd, se calcula:
      - La potencia en corriente continua (\(P_{DC}\)).
      - La potencia en corriente alterna (\(P_{AC}\).
   2. Estos resultados, llevados a valores diarios, mensuales y anuales, se pueden convertir en valores de energía (\(E_{DC}\) y \(E_{AC}\)) y de productividad del sistema (\(Y_f\)), los cuales se consolidan en un solo objeto de clase =ProdGCPV= (que incluye el objeto =Gef= del que parte) mediante la función prodGCPV.
      





* Footnotes
[fn:2] Se van a utilizar las ecuaciones propuestas por P.I. Cooper [[cite:Cooper1969]] por su simpleza.

[fn:1] Para las ecuaciones de este apartado se va a optar por poner la ecuación más simple posible. Sin embargo, el paquete =solaR2= otorga la posibilidad de realizar los cálculos de utilizando las ecuaciones propuestas por 4 autores diferentes.

