\chapter{Marco teórico}
label:chap:marco-teorico
El paquete =solaR2= toma como marco teórico el libro de Oscar Perpiñán, tutor de este trabajo, Energía Solar Fotovoltaica \cite{Perpinan2023} para cada una de las operaciones de cálculo que realizan cada una de las funciones.
En la figura [[fig:prod-calculo]], se muestra un diagrama que resume los pasos que se siguen a la hora de calcular la producción de sistemas fotovoltaicos.
#+CAPTION: Procedimiento de cálculo
#+NAME: fig:prod-calculo
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio
[[file:figuras/ProcedimientoCalculoRadiacionInclinada.pdf]]
Estos pasos son:
1. Calcular la geometría que define la posición relativa del Sol desde la Tierra.
2. Obtener la irradiación global diaria en el plano horizontal
3. A partir de la irradiación global, obtener las componentes de difusa y directa.
4. Se trasladan estos valores de irradición a valores de irradiancia.
5. Integrando estos valores se pueden obtener las estimaciones irradiación diaria difusa, directa y global
6. El generador fotovoltaico produce una potencia en corriente continua dependiente del rendimiento del mismo..
7. Se transforma en potencia en corriente alterna mediante un inversor que tiene una eficiencia asociada.
8. Integrando esta potencia se puede obtener la energía que produce el generador en un tiempo determinado.

* Naturaleza de la radiación solar
label:sec:naturaleza-radiacion-solar
Para el cálculo de la radiación solar que incide en una superficie se deben distinguir tres componentes diferenciados:
- *Radiación Directa*, B\nomenclature[B]{\(B\)}{Radiación directa}: fracción de radiación que procede en línea recta desde el Sol.
- *Radiación Difusa*, D\nomenclature[D]{\(D\)}{Radiación difusa}: fracción de radiación que procede de todo el cielo, excepto del Sol. Son todos aquellos rayos que dispersa la atmósfera.
- *Radiación del albedo*, R\nomenclature[R]{\(R\)}{Radiación del albedo}: parte de la radiación procedente de la reflexión con el suelo.
La suma de las tres componentes constituye la denominada radiación global: \nomenclature[G]{\(G\)}{Radiación global}
#+begin_export latex  
\begin{equation}
G = B + D + R
\label{eq:comp_rad}
\end{equation}
#+end_export
Tomando como base el libro antes mencionado [[cite:Perpinan2023]], se describirá el proceso que se ha de seguir para obtener una estimación de las componenetes directa y difusa a partir del dato de radiación global, dado que es el que comúnmente se puede obtener de una localización determinada.

** Radiación fuera de la atmósfera terrestre
label:subsec:radiacion-fuera-atmosfera-terrestre
Lo primero que se menciona en dicho proceso es la obtención de la irradiancia denominda extra-terrestre o extra-atmosférica\nomenclature[B00]{\(B_0(0)\)}{irradiancia extra-atmósferica o extra-terrestre en el plano horizontal}, que es la radiación que llega a la atmósfera, directamente desde el Sol, que no sufre ninguna pérdida por interaccionar con algún medio. Como la relación entre el tamaño de nuesto planeta y la distancia entre el Sol y la Tierra es muy reducida, es posible asumir que el valor de dicha irradiancia es constante, siendo este valor $B_0=1367\frac{W}{m^2}$, según varias mediciones.
Como la órbita que describe la Tierra alrededor del Sol no es totalmente circular, sino que tiene forma de elipse, para calcular la irradiancia incidente en una superficie tangente a la atmosfera en ua latitud concreta, debemos aplicar un factor de correción de la excentricidad de la elipse:
#+begin_export latex
\begin{equation}
B_0(0)=B_0\epsilon_0cos\theta_{zs}
\label{eq:irrad_horiz}
\end{equation}
#+end_export
Siendo cada componente:
- Constante solar: $B_0=1367\frac{W}{m^2}$ \nomenclature[B0]{\(B_0\)}{Constante solar o irradiancia solar incidente en un plano normal al vector solar en el límite superior de la atmósfera terrestre}
- Factor de corrección por excentricidad: $\epsilon_0=(\frac{r_0}{r})^2=1+0.033\cdot cos(\frac{2\pi d_n}{365})$[fn:1] \nomenclature[epsilon0]{\(\epsilon_0\)}{Corrección debida a la excentricidad de la elipse de la trayectoria terrestre alrededor del sol}
- Ángulo zenital solar: $cos(\theta_{zs})=cos(\delta)cos(\omega)cos(\phi)+sin(\delta)+sin(\phi)$[fn:2]
  #+begin_export latex
  \nomenclature[thetazs]{$\theta_{zs}$}{Ángulo cenital solar}
  #+end_export
  Donde:
  - Declinación: $\delta =23,45^\circ \cdot sin(\frac{2\pi \cdot (d_n+284)}{365})$ \nomenclature[delta]{\(\delta\)}{Declinación}
    donde $d_n$ es el dia del año. \nomenclature[dm]{$d_n$}{Día del año}
  - Latitud: \(\phi\) \nomenclature[phi]{\(\phi\)}{Latitud}
  - Hora solar o tiempo solar verdadero: $\omega = 15\cdot (TO-AO-12)+\Delta \lambda +\frac{EoT}{4}$ \nomenclature[omega]{\(\omega\)}{Hora solar o tiempo solar verdadero}

    Donde:
    - Hora oficial: \(TO\) \nomenclature[TO]{\(TO\)}{Hora oficial}
    - Adelanto oficial durante el horario de verano: \(AO\) \nomenclature[AO]{\(AO\)}{Adelanto oficial durante el horario de verano}
    - Diferencia entre la longitud local y la longitud del huso horario: \(\Delta \lambda\) \nomenclature[deltalambda]{\(\Delta \lambda\)}{Diferencia entre la longitud local y la longitud del huso horario}
    - Ecuación del tiempo: $EoT=229,18\cdot (-0,0334\cdot sin(\frac{2\pi}{365,24}\cdot dn)+0,04184\cdot sin(2\cdot \frac{2\pi}{365,24}\cdot dn+3,5884))$ \nomenclature[EoT]{\(EoT\)}{Ecuación del tiempo}

Esta irradiancia extra-terrestre solo tiene componentes geométicas. De modo que, si integramos la ecuación [[ref:eq:irrad_horiz]], se obtiene la irradiación diaria extra-terrestre:
#+begin_export latex
\begin{equation}
B_{0d}(0)=-\frac{T}{\pi}B_0\epsilon_0(\omega_s sin\phi sin\delta + cos\phi cos\delta sin \omega_s)
\label{eq:irrad_dia}
\end{equation}
#+end_export
Siendo:
- Ángulo del amananecer: \nomenclature[omegas]{\(\omega_s\)}{Ángulo del amanecer}
  \[
  \omega_s=\begin{cases}
  -\arccos(-\tan\delta\tan\phi)& \text{si $|\tan\delta\tan\phi|<1$}\\
  -\pi& \text{si $-\tan\delta\tan\phi<-1$}\\
  0& \text{si $-\tan\delta\tan\phi>1$}
  \end{cases}\]

Es posible demostrar que el promedio mensual de esta irradiación diaria coincide numéricamente con el valor de irradiación diaria correspondiente a los denominados "días promedios", días en los que la declinación correpondiente coincide con el promedio mensual (tabla [[ref:tab:DiasPromedio]])
#+begin_export latex
\begin{center}
{\footnotesize }%
\begin{table}[h]
{\footnotesize \caption{Valor $d_{n}$ correspondiente a los doce días promedio.\label{tab:DiasPromedio}}
}{\footnotesize \par}

\centering{}{\footnotesize }\begin{tabular}{>{\centering}p{6mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{4mm}>{\centering}m{3mm}}
\toprule 
{\footnotesize Mes} & {\footnotesize Ene} & {\footnotesize Feb} & {\footnotesize Mar} & {\footnotesize Abr} & {\footnotesize May} & {\footnotesize Jun} & {\footnotesize Jul} & {\footnotesize Ago} & {\footnotesize Sep} & {\footnotesize Oct} & {\footnotesize Nov} & {\footnotesize Dic}\tabularnewline
\midrule
$d_{n}$ & {\footnotesize 17} & {\footnotesize 45} & {\footnotesize 74} & {\footnotesize 105} & {\footnotesize 135} & {\footnotesize 161} & {\footnotesize 199} & {\footnotesize 230} & {\footnotesize 261} & {\footnotesize 292} & {\footnotesize 322} & {\footnotesize 347}\tabularnewline
\bottomrule
\end{tabular}
\end{table}

\par\end{center}{\footnotesize \par}
#+end_export
 
** Cálculo de componentes de radiación solar
label:subsec:calculo-componentes-radiacion-solar
Para caracterizar la radiación solar en un lugar, Liu y Jordan [[cite:Liu.Jordan1960]] propusieron el índice de claridad, \(K_T\). Este índice es la relación entre la radiación global y la radiación extra-atmosférica, ambas en el plano horizontal. El índice de claridad diario es la relación entre los valores diarios de irradiación: \nomenclature[KT]{\(K_T\)}{Índice de claridad}
#+begin_export latex
\nomenclature[KTd]{\(K_{Td}\)}{Índice de claridad diario}
#+end_export
#+begin_export latex
\begin{equation}
K_{Td}=\frac{G_d(0)}{B_{0d}(0)}
\label{eq:ind-cla-dia}
\end{equation}
#+end_export 
mientras que el índice de claridad mensual es la relación entre las medias mensuales de la irradiación diaria:
#+begin_export latex
\nomenclature[KTm]{\(K_{Tm}\)}{Índice de claridad mensual}
#+end_export
#+begin_export latex
\begin{equation}
K_{Tm}=\frac{G_{d,m}(0)}{B_{0d,m}(0)}
\label{eq:ind-cla-men}
\end{equation}
#+end_export

Una vez se tiene el índice de claridad, se puede calcular la fracción de radiación difusa en el plano horizontal. En el caso de medias mensuales [[cite:Page1961]]:
#+begin_export latex
\begin{equation}
F_{Dm}=1-1,13\cdot K_{Tm}
\end{equation}
#+end_export
Donde:
- Fracción de radiación difusa: $F_D=\frac{D(0)}{G(0)}$ \nomenclature[FD]{\(F_D\)}{Fracción de difusa}
  #+begin_export latex
  \nomenclature[FDd]{\(F_{Dd}\)}{Fracción de difusa diaria} \nomenclature[FDm]{\(F_{Dm}\)}{Fracción de difusa mensual}
  #+end_export
Al tener la fracción de radiación difusa, se pueden obtener los valores de la radiación directa y difusa en el plano horizontal:
#+begin_export latex
\begin{equation}
D_d(0)=F_D\cdot G_d(0)
\label{dif-rad}
\end{equation}
\begin{equation}
B_d(0)=G_d(0)-D_d(0)
\label{dir-rad}
\end{equation}
#+end_export

* Radiación en superficies inclinadas
label:sec:radiacion-superficies-inclinadas
Dados los valores de irradiación diaria difusa, directa y global en el plano horizontal se puede realizar la transformación al plano inclinado. Para ello, es necesario estimar el perfil de irradiancia correspondiente a cada valor de irradiación. dado que la variación solar durante una hora es baja, podemos suponer que el valor medio de la irradiancia durante esa hora coincide numéricamente con la irradiación horaria. Por otra parte, el análisis de valores /medios/  en /largas/ series temporales ha mostrado que la relación entre la irradiancia y la irradiación extra-atmosférica [[cite:Collares-Pereira.Rabl1979]] ([[ref:eq:rel-dif]]):
#+begin_export latex
\begin{equation}
r_D=\frac{D(0)}{D_d(0)}=\frac{B_0(0)}{B_{0d}(0)}
\label{eq:rel-dif}
\end{equation}
#+end_export
Este factor \(r_D\)\nomenclature[rD]{\(r_D\)}{Relación entre la irradiancia y la irradiación difusa en el plano horizontal} es calculable directamente sabiendo que la relación entre irradiancia e irradiación extra-atmosférica es deducible teóricamente a partir de las ecuaciones [[ref:eq:irrad_horiz]] [[ref:eq:irrad_dia]]:
#+begin_export latex
\begin{equation}
\frac{B_0(0)}{B_{0d}(0)}=\frac{\pi}{T}\cdot \frac{cos(\omega)-cos(\omega_s)}{\omega_s\cdot cos(\omega_s)-sin(\omega_s)}=r_D
\label{eq:rel-dif2}
\end{equation}
#+end_export
el mismo análisis mostró una relación entre la irradiancia e irradiación global asimilable a una función dependiente de la hora solar ([[ref:eq:rel-glo]]):
#+begin_export latex
\begin{equation}
r_G=\frac{G(0)}{G_d(0)}=r_D\cdot(a+b\cdot cos(w))
\label{eq:rel-glo}
\end{equation}
#+end_export
Donde:
- $a=0,409-0,5016\cdot sin(\omega_s+\frac{\pi}{3})$
- $b=0,6609+0,4767\cdot sin(\omega_s+\frac{\pi}{3})$

Es importante resaltar que estos perfiles proceden de medias sobre largos períodos, y de ahí que, como es observable en la figura [[fig:Perfil-de-irradiancia]], las fluctuaciones propias del movimiento de nubes a lo largo del día queden atenuadas y se obtenga una curva sin alteraciones.
#+NAME: fig:Perfil-de-irradiancia
#+CAPTION: Perfil de irradiancia difusa y global obtenido a partir del generador empírico de [[cite:Collares-Pereira.Rabl1979]] para valores de irradiancia tomadas cada 10 minutos
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio
[[file:figuras/RgRd.pdf]]

** Transformación al plano del generador
label:subsec:transformación-plano-generador
Una vez otenidos los valores de irradiancia en el plano horizontal, se traspone al plano del generador:
- *Irradiancia Directa* $B(\beta ,\alpha)$: Ecuación basada en geometría solar (ángulo zenital) y del generador (ángulo de incidencia).
  #+begin_export latex
  \begin{equation}
  B(\beta ,\alpha)=B(0)\cdot \frac{max(0,cos(\theta_s))}{cos(\theta_{zs})}
  \label{eq:irradiancia-directa-plano-generador}
  \end{equation}
  #+end_export
  donde:
  - Ángulo de inclinación: \(\beta\).
  - Ángulo de orientación: \(\alpha\). \nomenclature[alpha]{\(\alpha\)}{Ángulo de orientación de un sistema fotovoltaico}
- *Irradiancia Difusa* $D(\beta ,\alpha)$: Utilizando el modelo de cielo anisotrópico [[cite:Perpinan2023]], se distinguen dos componentes de la irradiancia difusa, denominados /circunsolar/ e /isotrópica/. \nomenclature[DI]{\(D^I\)}{Radiación difusa isotrópica} \nomenclature[DC]{\(D^C\)}{Radiación difusa circunsolar}
  #+begin_export latex
  \begin{equation}
  D(\beta ,\alpha)=D^I(\beta ,\alpha)+D^C(\beta ,\alpha)
  \end{equation}
  \begin{equation}
  D^I(\beta ,\alpha)=D(0)(1-k_1)\cdot \frac{1+cos(\beta)}{2}
  \end{equation}
  \begin{equation}
  D^C(\beta, \alpha)=D(0)\cdot k_1\cdot \frac{max(0,cos(\theta_s))}{cos(\theta_{zs})}
  \end{equation}
  #+end_export
  Donde:
  - $k_1=\frac{B(n)}{B_0\cdot \epsilon_0}=\frac{B(0)}{B_0(0)}$
- *Irradiancia de albedo* $R(\beta ,\alpha)$: Se considera isotrópica debido a su baja contribución a la radiación global. Se calcula a partir de la irradiancia global en el plano horizontal usando un coeficiente de reflexión, \(\rho\)\nomenclature[rho]{\(\rho\)}{Coeficiente de reflexión del terreno para la irradiancia de albedo}, que depende del terreno. En la ecuación [[ref:eq:albedo-plano-generador]], se utiliza el factor $\frac{1-cos(\beta)}{2}$, complemetario al factor de visión de la difusa isotrópica (figura [[fig:AnguloVisionCielo]])
  #+begin_export latex
  \begin{equation}
  R(\beta ,\alpha)=\rho \cdot G(0)\cdot \frac{1 - cos(\beta)}{2}
  \label{eq:albedo-plano-generador}
  \end{equation}
  #+end_export
  #+NAME: fig:AnguloVisionCielo
  #+CAPTION: Ángulo de visión del cielo
  #+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio
  [[file:figuras/AnguloVisionCielo.pdf]]

** Ángulo de incidencia y suciedad
label:subsec-angulo-incidencia-suciedad
En un módulo fotovoltaico, la radiación incidente generalmente no es perpendicular a la superficie del módulo, lo que provoca pérdidas por reflexión o pérdidas angulares, cuantificadas por el ángulo de incidencia \(\theta_s\)\nomenclature[thetas]{\(\theta_s\)}{Ángulo de incidencia o ángulo entre el vector solar y el vector director de una superficie}. La suciedad acumulada en la superficie del módulo también reduce la transmitancia del vidrio (representada por $T_{limpio}(0$)), disminuyendo la irradiancia efectiva, es decir, la radiación que realmente puede ser aprovechada por el módulo.
La irradiancia efectiva para radiación directa se expresa en la ecuación [[ref:eq:dir-ef]]:
#+begin_export latex
\begin{equation}
B_{ef}(\beta ,\alpha)=B(\beta ,\alpha)\cdot [\frac{T_{sucio}(0)}{T_{limpio}(0)}]\cdot (1-FTB(\theta_s))
\label{eq:dir-ef}
\end{equation}
#+end_export
donde $FTB(\theta_s)$ es el factor de pérdidas angulares, que se calcula con la ecuación [[ref:eq:factor-perdidas-directa]]: \nomenclature[FTB]{\(FT_B\)}{Factor de pérdidas angulares para irradiancia directa}\nomenclature[FTD]{\(FT_D\)}{Factor de pérdidas angulares para irradiancia difusa}\nomenclature[FTB]{\(FT_R\)}{Factor de pérdidas angulares para irradiancia de albedo}
#+begin_export latex
\begin{equation}
FTB(\theta_s)=\frac{exp(-\frac{cos(\theta_s)}{a_r})-exp(-\frac{1}{a_r})}{1-exp(-\frac{1}{a_r})}
\label{eq:factor-perdidas-directa}
\end{equation}
#+end_export
Este factor depende el ángulo de incidencia \(theta_s\) y del coeficiente de pérdidas angulares \(a_r\). Cuando la radiación es perpendicular a la superficie ($\theta_s=0$), \(FTB\) es cero. En la figura [[fig:PerdidasAngulares]] se puede observar que las pérdidas angulares son más significativas cuando \(\theta_s\) supera los 60º, y se acentúan con mayor suciedad.
#+NAME: fig:PerdidasAngulares
#+CAPTION: Pérdidas angulares de un módulo fotovoltaico para diferentes grados de suciedad en función del ángulo de incidencia.
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio 
[[file:figuras/Suciedad.pdf]]

Para calcular las componente de radiación difusa isotrópica y de albedo se utilizan las ecuaciones [[ref:eq:FTD]] y [[ref:eq:FTR]]:
#+begin_export latex
\begin{equation}
\text{FTD}(\beta) \approx exp[-\frac{1}{a_r}\cdot (c_1\cdot (sin\beta +\frac{\pi -\beta - sin\beta}{1+cos\beta})+c_2\cdot (sin\beta +\frac{\pi -\beta -sin\beta}{1+cos\beta})^2)]
\label{eq:FTD}
\end{equation}
#+end_export
#+begin_export latex
\begin{equation}
\text{FTR}(\beta) \approx exp[-\frac{1}{a_r}\cdot (c_1\cdot (sin\beta +\frac{\beta - sin\beta}{1-cos\beta})+c_2\cdot (sin\beta +\frac{\beta -sin\beta}{1-cos\beta})^2)]
\end{equation}
\label{eq:FTR}
#+end_export
Donde:
- Ángulo de inclinación del generador (en radianes): \(\beta\) \nomenclature[beta]{\(\beta\)}{Ángulo de inclinación de un sistema fotovoltaico}
- Coeficiente de pérdidas angulares: \(a_r\)
- Coeficientes de ajuste: \(c_1\) y \(c_2\) (en la tabla [[ref:tab:coef-perd]] se recogen algunos valores característicos de un módulo de silicio monocristalino convencional para diferentes grados de suciedad)
#+CAPTION: Valores del coeficiente de pérdidas angulares y transmitancia relativa en incidencia normal para diferentes tipos de suciedad. label:tab:coef-perd
|-------------------+--------------------------------------+------+--------|
| Grado de suciedad | $\frac{T_{sucio}(0)}{T_{limpio}(0)}$ |  a_r |    c_2 |
|-------------------+--------------------------------------+------+--------|
| Limpio            |                                    1 | 0.17 | -0.069 |
|-------------------+--------------------------------------+------+--------|
| Bajo              |                                 0.98 | 0.20 | -0.054 |
|-------------------+--------------------------------------+------+--------|
| Medio             |                                 0.97 | 0.21 | -0.049 |
|-------------------+--------------------------------------+------+--------|
| Alto              |                                 0.92 | 0.27 | -0.023 |
|-------------------+--------------------------------------+------+--------|

Para estas componenetes el cálculo de irradiancia efectiva es similar al de la irradiancia directa (ecuaciones [[ref:eq:dif-ef-iso]] y [[ref:eq:alb-ef]]). Para la componente difusa circunsolar emplearemos el factor de pérdidas angulares de la irradiancia efectiva(ecuacion [[ref:eq:dif-ef-cir]]):
#+begin_export latex
\begin{equation}
D_{ef}^I(\beta ,\alpha)=D^I(\beta ,\alpha)\cdot[\frac{T_{sucio}(0)}{T_{limpio}(0)}]\cdot (1-FT_D(\beta))
\label{eq:dif-ef-iso}
\end{equation}
\begin{equation}
D_{ef}^C(\beta ,\alpha)=D^C(\beta ,\alpha)\cdot[\frac{T_{sucio}(0)}{T_{limpio}(0)}]\cdot (1-FT_B(\theta_s))
\label{eq:dif-ef-cir}
\end{equation}
\begin{equation}
R_{ef}(\beta ,\alpha)=R(\beta ,\alpha)\cdot[\frac{T_{sucio}(0)}{T_{limpio}(0)}]\cdot (1-FT_R(\beta))
\label{eq:alb-ef}
\end{equation}
#+end_export
Siguiendo el esquema de la figura [[fig:prod-calculo]], a partir de estas irradiancias efectivas se puede calcular la irradiación global efectiva diaria, mensual y anual. Comparando la irradiación global incidente con la irradición efectiva, se puede evaluar el impacto de la suciedad y el desajuste del ángulo en períoods prolongados.

* Cálculo de la energía producida por un generador fotovoltaico
label:sec:calculo-energia-producida-generador

** Funcionamiento de una célula solar
label:subsec:funcionamiento-celula-solar
Para calcular la energía producida por un generador fotovoltaico, se deben tener en cuenta la influencia de factores tales como la radiación o la temperatura en una célula solar y en los valores de tensión y corriente que se alcanzan en dichas condiciones.

Para definir una célula solar, se tomar 4 variables:
- La corriente de cortocircuito: \(I_{sc}\)
  #+begin_export latex
  \nomenclature[Isc]{\(I_{sc}\)}{Corriente de cortocircuito de una célula}
  #+end_export
- La tensión de circuito abierto: \(V_{oc}\)
  #+begin_export latex
  \nomenclature[VOC]{\(V_{oc}\)}{Tensión de circuito abierto de una célula}
  #+end_export
- La corriente en el punto de máxima potencia: \(I_{mpp}\)
  #+begin_export latex
  \nomenclature[Impp]{$I_{mpp}$}{Corriente de una célula en el punto de máxima potencia}
  #+end_export
- La tensión en el punto de máxima potencia: \(V_{mpp}\)
  #+begin_export latex
  \nomenclature[Vmpp]{$V_{mpp}$}{Tensión de una célula en el punto de máxima potencia}
  #+end_export

*** Punto de máxima potencia
El punto de máxima potencia es aquel situado en la curva de funcionamiento del generador donde, como su propio nombre indica, los valores de tensión y corriente son tales que la potencia que entrega es máxima (figura [[fig:iv-20-800]]).
#+CAPTION: Curvas corriente-tensión(línea discontinua) y potencia-tensión(línea continua) de una célula solar ($T_a=20^\circ C$ y $G=800 W/m^2$)
#+NAME: fig:iv-20-800
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio 
[[file:figuras/CurvaIV_Ta20_G800.pdf]]

*** Factor de forma y eficiencia
El área encerrada por el rectángulo definido por el producto $I_{mpp}\cdot V_{mpp}$ es, como e observable en la figura [[fig:iv-20-800]], inferiro a la respresentada por el producto $I_{sc}\cdot V_{oc}$. La relación entre estad dos superficies se cuantifica con el factor de forma:\nomenclature[MPP]{MPP}{Punto de máxima potencia de un dispositivo fotovoltaico}
#+begin_export latex
\begin{equation}
FF=\frac{I_{mpp}\cdot V_{mpp}}{I_{sc}\cdot V_{oc}}
\label{eq:factor-forma}
\end{equation}
#+end_export

Conociendo los valores de $I_{sc}$ y $V_{oc}$ es posible calcular la potencia en el punto de máxima potencia, dado que $P_{mpp}=FF\cdot I_{sc}\cdot V_{oc}$.

Por otra parte, la calidad de una célula se puede cuantificar con la eficiencia de conversión (ecuación ref:eq:efi-cel).
#+begin_export latex
\begin{equation}
\eta =\frac{I_{mpp}\cdot V_{mpp}}{P_L}
\label{eq:efi-cel}
\end{equation}
#+end_export
donde $P_L=A_c\cdot G_{ef}$ representa la potencia luminosa que incide en la célula\nomenclature[Ac]{\(A_c\)}{Área de una célula}.Como es evidente de la ecuación [[ref:eq:efi-cel]], este valor de eficiencia se corresponde al caso en el que el acoplamiento entre la carga y la célula permite a ésta trabajar en el punto de máxima potencia. En la figura [[fig:nrel-cell]] se muestra la evolución temporal del valor de eficiencia de célula de laboratorio para diferentes tecnologías.

#+CAPTION: Evolución de la eficiencia de células según la tecnología (según el National Renewable Energy Laboratory [[cite:nrel24]] (EEUU)).
#+NAME: fig:nrel-cell
#+ATTR_LATEX: :height 0.5\textheight :width 0.8\textwidth :options keepaspectratio
[[file:figuras/cell-efficiencies.pdf]]

*** Influencia de la temperatura y la radiación
La temperatura y la radiación son factores cruciales en el funcionamiento de una célula solar. El aumento de la temperatura ambiente reduce la tensión de circuito abierto según la relación $dV_{oc}/dT_c$, \nomenclature[Tc]{\(T_c\)}{Temperatura de célula}, que para células de silicio cristalino es de$-2,3\frac{mV}{^\circ C}$. Además, disminuye la eficiencia de la célula solar con $\frac{d\eta}{dT_c}=-0,4\%/^\circ C$.

En cuanto a la iluminación, la fotocorriente y la tensíon de circuito abierto son proporcionales a la irradiancia incidente.

Tomando en cuanta estas influencias, se definen una condiciones de funcionamiento, denominadas condiciones estándar de medida(STC)\nomenclature[STC]{STC}{Condiciones estándar de medida de un dispositivo fotovoltaico}, válidas para caracterizar una célula en el entorno de un laboratorio. Estas condiciones vienen determinadas por:
- Irradiancia: $G_{stc}=1000W/m^2$ con incidencia normal.
  #+begin_export latex
  \nomenclature[GSTC]{\(G_{STC}\)}{Irradiancia incidente en condiciones estandar de medida}
  #+end_export
- Temperatura de célula: $T_c^*=25^\circ C$.\nomenclature[TC*]{\(T_c^*\)}{Temperatura de célula en condiciones estándar de medida}
- Masa de aire: $AM=1,5$.[fn:3]\nomenclature[AM]{\(AM\)}{Masa de aire}
Frecuentemente los fabricantes informan de los valores de las tensiones $V_{oc}^*$ y $V_{mpp}^*$ y las corrientes $I_{sc}^*$ y $I_{mpp}^*$[fn:4]. A partir de estos valores es posible referir a estas condiciones:
- La potencia: $P_{mpp}^*=I_{mpp}^*\cdot V_{mpp}^*$
- El factor de forma: $FF^*=\frac{P_{mpp}^*}{I_{sc}^*\cdot V_{oc}^*}$
- La eficiencia: $\eta^*=\frac{I_{mpp}^*\cdot V_{mpp}^*}{A_c\cdot G_{stc}}$
  
** Funcionamiento de un módulo fotovoltaico
label:subsec:funcionamiento-modulo-fotovoltaico
*** Comportamiento térmico de un módulo
La mayoría de las ecuaciones ue definen el comportamiento de un módulo fotovoltaico se establecen en lo que se conocen como condiciones estándar de funcionamiento. En estas condiciones, la temperatura de la célula es de $25^\circ C$. Sin embargo, la temperatura de operación de la célula es diferente y depende directamente de la radiación que recibe el módulo en cada momento.

El módulo recibe una cantidad de radiación dada, absorbiendo la fracción de ésta que no se refleja al exterior. De dicha fracción, parte de ella es transformada en energía eléctrica mientras que el resto se entrega en forma de calor al entorno.

Para simplificar, se puede asumir que el incremento de la temperatura de la célula respecto de la temperatura ambiente depende linealmente de la irradiancia incidente en ésta. El coeficiente de proporcionalidad depende de muchos factores, tales como el modo de instalación del módulo, la velocidad del viento, la humedad ambiente y las características constructivas del laminado.

Estos factores quedan recogidos en un valor único representado por la temperatura de operación nominal de célula (NOCT o TONC)\nomenclature[TONC]{\(TONC\)}{Temperatura de operación nominal de célula}, definida como aquella que alcanza una /célula/ cuando su /módulo/ trabaja en las siguientes condiciones:
- Irradiancia: $G=800W/m^2$.
- Masa de aire: $AM= 1,5$.
- Irradiancia normal.
- Temperatura /ambiente/: $T_a=20^\circ C$.
- Velocidad de viento: $v_v=1m/s$.

La ecuación [[ref:eq:temp-cel]] expresa una aproximación aceptable del comportamiento térmico de una célula integrada en un módulo en base a las consideraciones previas:
#+begin_export latex
\begin{equation}
T_c=T_a+G_{ef}\cdot \frac{NOCT-20}{800}
\label{eq:temp-cel}
\end{equation}
#+end_export
Para la simulación del funcionmaiento de un módulo fotovoltaico en condiciones de operación real, es necesario contar con secuencias de valores de temperatura ambiente. Si no se dispone de información detallada, se puede asumir un valor constante de $T_a=25^\circ C$ para simulaciones anuales. Sin embargo, si se conocen los valores máximos y mínimos diarios de la temperatura ambiente, se puede generar una secuencia intradiaria usando una combinación de funciones coseno.
*** Cálculo de $V_{oc}$ y $I_{sc}$
Conociendo ya los valores horarios de temperatura de la célula, se puede calcular $V_{oc}$ utilizando la ecuación [[ref:eq:ten-ca]]. Y, por último, mediante la ecuación [[ref:eq:int-cc]] se puede calcular $I_{sc}$.
#+begin_export latex
\begin{equation}
V_{oc}(T_c)=V_{oc}^*+(T_c-T_c^*)\cdot \frac{dV_{oc}}{dT_c}\cdot N_{cs}
\label{eq:ten-ca}
\end{equation}
#+end_export
#+begin_export latex
\begin{equation}
I_{sc}=G_{ef}\cdot \frac{I_{sc}^*}{G^*}
\label{eq:int-cc}
\end{equation}
#+end_export

*** Factor de forma variable
Una vez obtenidos los valores de $V_{oc}$ y $I_{sc}$, el siguiente paso ha de ser calcular los valores de tensión y corriente en el punto de máxima potencia, pues es donde el generador estará entregando su máxima potencia, como su propio nombre indica, y por tanto es un punto de interés para el cálculo.

Existen dos metodologías de cálculo de dicho punto, uno de ellos significantemente más sencillo que el otro. Éste consiste en suponer que el Factor de Forma, definido en la expresión [[ref:eq:factor-forma]] es constante.

Si suponemos que FF es constante, se podrían extraer los valores de tensión y corriente en el punto de máxima potencia ya que si
#+begin_export latex
\begin{equation}
FF=FF^*
\end{equation}
#+end_export
entonces
#+begin_export latex
\begin{equation}
\frac{I_{mpp}\cdot V_{vmpp}}{I_{sc}\cdot V_{oc}}=\frac{I_{mpp}^*\cdot V_{vmpp}^*}{I_{sc}^*\cdot V_{oc}^*}
\end{equation}
#+end_export
pudiendo así obtener los valores de $I_{mpp}$ y $V_{vmmp}$.

Sin embargo, este suposición da resultados alejados a una estimación acertada. Por ello, se tendrá en cuenta la variación del factor de forma:
- *Cálculo de la tensión termica, $V_t$, a temperatura de la célula*: Se calculará el valor de $V_t$ a 25ºC con la expresión:
  #+begin_export latex
  \begin{equation}
  V_{tn}=\frac{V_t\cdot (273+25)}{300}
  \end{equation}
  #+end_export
- *Cálculo de $R_s^*$*: El segundo paso consiste en calcular el valor de resistencia en serie con los valores STC:
  #+begin_export latex
  \begin{equation}
  R_s^*=\frac{\frac{V_{oc}^*}{N_{cs}}-\frac{V_{mpp}^*}{N_{cs}}+m\cdot V_{tn}\cdot ln(1-\frac{I_{mpp}^*}{I_{sc}^*})}{\frac{I_{mpp}^*}{N_{cp}}}
  \end{equation}
  #+end_export
- *Cálculo de $r_s$*: Utilizando el valors de $R_s^*$ calculado en el paso anterior junto con los valores de $V_{oc}$ y $I_{sc}$ podemos calcular $r_s$ que se utilizará más adelante en el proceso.
  #+begin_export latex
  \begin{equation}
  r_s=R_s^*\cdot (\frac{N_{cs}}{N_{cp}}\cdot \frac{I_{sc}}{V_{oc}})
  \end{equation}
  #+end_export
- *Cálculo de $k_{oc}$*: A continuación, utilizando los valores de temperatura ambiente obtenidos con anterioridad junto con la tensión de circuito abierto, se calcula $k_{oc}$ mediante la expresión:
  #+begin_export latex
  \begin{equation}
  k_{oc}=\frac{V_{oc}/N_{cs}}{m\cdot V_t \cdot \frac{T_c+273}{300}}
  \end{equation}
  #+end_export

Con éstos cálculos previos, éste método propone localizar el punto de máxima potencia de forma aprodimada mediante la ecuaciones:
#+begin_export latex
\begin{equation}
i_{mpp}=1-\frac{D_M}{k_{oc}}
\end{equation}
\begin{equation}
v_{mpp}=1-\frac{ln(k_{oc}/D_M)}{k_{oc}}-r_s\cdot i_{mpp}
\end{equation}
#+end_export
donde:
#+begin_export latex
\begin{equation}
D_M=D_{M0}+2\cdot r_s\cdot D_{M0}^2
\end{equation}
\begin{equation}
D_{M0}=\frac{k_{oc}-1}{k_{oc}-lnk_{oc}}
\end{equation}
#+end_export

Por último, multiplicando los valores de $i_{mpp}$ y $v_{mpp}$ por $I_{sc}$ y $V_{oc}$ respectivamente, se obtienen los valores de $I_{mpp}$ y $V_{mpp}$ que serán los que se utilicen para calcular la potencia entregada por el generador en el punto de máxima potencia.

Teniendo estos valores se puede obtener:
#+begin_export latex
\begin{equation}
P_{mpp}=I_{mpp}\cdot V_{mpp}
\end{equation}
#+end_export

** Cálculo de potencias y energías de un sistema fotovoltaico conectado a la red
label:subsec:calculo-potencias-energias
La potencia obtenida en el paso anterior es la de un solo módulo. Para conocer la potencia que va a ser capaz de entregar un sfcr, se debe tener en cuenta su configuración de módulos en serie y en paralelo.
#+begin_export latex
\begin{equation}
P_g^*=N_s\cdot N_p\cdot P_m^*
\end{equation}
#+end_export
Con este paso se obtiene la potencia horaria entregada por el generador fotovoltaico. El siguiente paso será pasar esa potencia a través del inversor y calcular la potencia a la salida de este.

Primero, se esteblecen las expresiones de las potencias normalizadas. Siendo $P_{inv}$ la potencia nominal del inversor:
#+begin_export latex
\nomenclature[Pinv]{\(P_{inv}\)}{Potencia nominal de un inversor}
#+end_export
#+begin_export latex
\begin{equation}
p_i=\frac{P_{DC}}{P_{inv}}
\end{equation}
\begin{equation}
p_o=\frac{P_{AC}}{P_{inv}}
\end{equation}
#+end_export

Por otro lado, el rendimiento de un inversor fotovoltaico se puede modelizar de la siguiente manera:
#+begin_export latex
\begin{equation}
\eta_{inv}=\frac{p_o}{p_o+k_0+k_1p_o+k_2p_o^2}
\end{equation}
#+end_export

De las dos ecuaciones anteriores se puede deducir:
#+begin_export latex
\begin{equation}
p_i=p_o+k_0+k_1p_o+k_2p_o^2
\end{equation}
#+end_export

Desarrollando esta ecuación, se puede obtener una ecuación de segundo grado con $p_o$ como incógnita:
#+begin_export latex
\begin{equation}
k_2p_o^2+(k_1+1)p_o+(k_0-p_i)=0
\end{equation}
#+end_export

Por último, volviendo a las primeras expresiones se puede obtener la potencia en corriente alterna:
#+begin_export latex
\begin{equation}
P_{AC}=p_o\cdot P_{inv}
\end{equation}
#+end_export

Con esta potencia, integrando en función del tiempo se puede obtener la energía que genera el sistema
#+begin_export latex
\begin{equation}
E_{AC}=\int_{T} P_{AC} \,dt
\end{equation}
#+end_export
y la productividad:
#+begin_export latex
\begin{equation}
Y_f=\frac{E_{ac}}{P_g^*}
\end{equation}
#+end_export  

** Cálculo de potencias y energías de un sistema fovoltaico de bombeo
*** Potencia hidráulica
La potencia hidráulica, $P_H$ \nomenclature[PH]{$P_H$}{Potencia hidráulica}, necesaria para bombear agua es función de,
- La altura vertical aparente, $H_v$ \nomenclature[Hv]{$H_v$}{Altura vertical aparente}
- El caudal de agua, $Q$ \nomenclature[Q]{$Q$}{Caudal de agua} \nomenclature[g]{$g$}{Aceleración de la gravedad} \nomenclature[rho]{$\rho$}{Densidad del agua}
#+begin_export latex
\begin{equation}
P_H=g\cdot \rho \cdot Q \cdot H_V
\end{equation}
#+end_export

Expresando $P_H$ en watios, $H_v$ en metros y $Q$ en $m^3/h$ la ecuación resulta en:
#+begin_export latex
\begin{equation}
P_H=2.725\cdot Q \cdot H_v
\end{equation}
#+end_export

Asumiendo que el agua bombeado sale por el coducto a baja velocidad, la potencia de salida de la bomba necesita satisfacer $P_H$ \nomenclature[PH]{$P_H$}{Potencia hidraúlica necesaria en un sistema de bombeo de agua} más las pérdidas de fricción en la tubería, $P_f$ \nomenclature[Pf]{$P_f$}{Pérdidas de frición en la tubería de un sistema de bombeo}. Este valor se asimila a una altura equivalente $H_f$ \nomenclature[Hf]{$H_f$}{Altura asociada a las pérdidas de frición en una tubería} asociado a un caudal determinado: \nomenclature[HT]{$H_T$}{Altura total incluyendo las pérdidas de fricción de la tubería}
#+begin_export latex
\begin{equation}
H_T=H_v+H_f
\end{equation}
#+end_export
La potencia eléctrica a la entrada de la motobomba, $P_{el}$, es:
#+begin_export latex
\nomenclature[Pel]{$P_{el}$}{Potencia eléctrica necesaria en la entrada de una motobomba}
#+end_export
#+begin_export latex
\begin{equation}
P_{el}=\frac{P_H+P_f}{\eta_{mp}} 
\end{equation}
#+end_export
donde $\eta_{mp}$ es la eficiencia de la motobomba.
#+begin_export latex
\nomenclature[etamp]{$\eta_{mp}$}{Eficiencia de una motobomba}
#+end_export
La potencia eléctrica requerida por la motobomba es entregada por un generador FV y acondicionador de potencia:
#+begin_export latex
\begin{equation}
P_{el}=P_g^* \cdot \frac{G}{G_{stc}} \frac{\eta_g}{\eta_g^*} \cdot \eta_{inv}
\end{equation}
#+end_export
siendo $G$ la irradiancia en el plano del generador, $eta_{inv}$ la eficiencia del equipo de acondicionamiento de potencia y $\frac{\eta_g}{\eta_g^*}$ modela el comportamiento del generador con la temperatura.

*** Caudal diario
El caudal diario bombeado por este conjunto es:
#+begin_export latex
\begin{equation}
Q_d = \int_{d} \frac{G}{G^*} \cdot P_g^* \cdot \eta_g \cdot \frac{\eta_{ig}}{\eta_{ig}^*} \cdot \eta_{inv} \cdot \eta_{mp} \, dt
\end{equation}
#+end_export

*** Altura
Se puede definir una altura total equivalente, $H_{TE}$, con las siguientes suposiciones:
#+begin_export latex
\nomenclature[HTE]{$H_{TE}$}{Altura total equivalente de un sistema de bombeo}
#+end_export
- Las pérdidas de fricción en tubería son despreciables ($H_f < 0.05 \cdot H_T$).
- El nivel del agua dentro del pozo se mantiene constante.
#+begin_export latex
\begin{equation}
Q_d = \frac{P^*_g}{2.725 \cdot G^* \cdot H_{TE}} \int \left( \frac{G}{\eta_{ig}^{*} \eta_{m}^{*} \eta_{inv} \eta_{mp}} \right) dt
\end{equation}
#+end_export
Ahora el cálculo en la integral sólo depende de la radiación, temperatura, y equipos.

Para calcular esta altura total equivalente, se debe suponer que:
- El pozo está caracterizado con tres parámetros:
  - Nivel estático, $H_{st}$.
    #+begin_export latex
    \nomenclature[Hst]{$H_{st}$}{Nivel estático de un pozo}
    #+end_export
  - Nivel dinámico, $H_{dt}$.
    #+begin_export latex
    \nomenclature[Hdt]{$H_{dt}$}{Nivel dinámico de un pozo}
    #+end_export
  - Caudal de ensayo, $Q_t$. \nomenclature[Qt]{$Q_t$}{Caudal de ensayo de un pozo}
- Que se ha realizado el ensayo de bombeo para caracterizar los pozos con bomba portátil empleando el caudal máximo del pozo, $Q_{max}$ ($Q_t=Q_{max}$).
  #+begin_export latex
  \nomenclature[Qman]{$Q_{max}$}{caudal máximo del pozo}
  #+end_export

Con estas suposiciones se puede llegar a la expresión:
#+begin_export latex
\begin{equation}
H_{TE} = H_{ot} + H_{st} + \left( \frac{H_{dt} - H_{st}}{Q_T} \right) Q_{AP} + H_f(Q_{AP})
\end{equation}
#+end_export
donde:
- $H_{OT}$, es la altura desde la salida de agua hasta el suelo.
  #+begin_export latex
  \nomenclature[HOT]{$H_{OT}$}{Diferencia de cotas entre la salida de agua y la entrada en el depósito}
  #+end_export
- Nivel estático, $H_{st}$.
- Nivel dinámico, $H_{dt}$.
- Caudal aparente, $Q_{AP} = \alpha \cdot Q_d$
  ($\alpha=1/24=0.0416h^{-1}$).
- $H_f(Q_{AP})$, pérdidas en la tubería al caudal aparente.

*** Potencia del generador
Como primera aproximación, se consideran constantes a lo largo del tiempo las eficiencias de los componentes del sistema con la elección de ciertos valores adecuados ($\frac{\eta_g}{\eta_g^*}=0.85, \eta_{mp}=0.35, \eta_{inv}=0.9$). Así, es posible calcular de forma aproximada la potencia nominal del generador necesaria para bombear un caudal diario $Q_d$ a una altura total equivalente $H_{TE}$ a partir de la ecuación:
#+begin_export latex
\begin{equation}
P^*_g = \frac{10 \cdot HTE \cdot Q_d}{\frac{G_d}{G_{stc}}}
\end{equation}
#+end_export

*** Simulación de sistemas fotovoltaicos de bombeo
Debido a la complicación del cálculo del dimensionamiento de los sistemas fotovoltaicos de bombeo, se puede recurrir a métodos de simulación asistidos por ordenaor. El algoritmo a seguir es:
1. Curva característica de la bomba que relaciona la altura, $H$, y el caudal, $Q$, a la frecuencia nominal de la bomba:
  #+begin_export latex
  \begin{equation}
  H = a \cdot f^2 + b \cdot f \cdot Q + c \cdot Q^2
  \end{equation}
  #+end_export
   - Donde \(a\), \(b\), y \(c\) son coeficientes característicos de la bomba y \(f\) es la frecuencia.
2. Relaciones de semejanza para bombas centrífugas:
  #+begin_export latex
  \begin{equation}
  \frac{f_1}{f_2} = \frac{Q_1}{Q_2} = \left(\frac{H_1}{H_2}\right)^{1/2} = \left(\frac{P_1}{P_2}\right)^{1/3}
  \end{equation}
  #+end_export
3. Cálculo de caudal y altura a frecuencia nominal (50 Hz):
 #+begin_export latex
 \begin{equation}
 Q_{50} = \frac{50 \cdot Q}{f}
 \end{equation}
 #+end_export
 #+begin_export latex
 \begin{equation}
 H_{50} = H \cdot \left(\frac{50}{f}\right)^2
 \end{equation}
 #+end_export
4. Ecuación de potencia hidráulica:
 #+begin_export latex
 \begin{equation}
 P_{h,50} = 2.725 \cdot Q_{50} \cdot H_{50}
 \end{equation}
 #+end_export
5. Potencia mecánica en el eje de la bomba a 50 Hz:
 #+begin_export latex
 \begin{equation}
 P_{b,50} = \frac{P_{h,50}}{\eta_b}
 \end{equation}
 #+end_export
6. Potencia mecánica a frecuencia \(f\):
 #+begin_export latex
 \begin{equation}
 P_b = P_{b,50} \cdot \left(\frac{f}{50}\right)^3
 \end{equation}
 #+end_export
7. Potencia eléctrica demandada por el motor:
 #+begin_export latex
 \begin{equation}
 P_{bc} = P_b \cdot \frac{50}{f}
 \end{equation}
 #+end_export
 #+begin_export latex
 \begin{equation}
 P_{e,50} = \frac{P_{bc}}{\eta_m}
 \end{equation}
 #+end_export
 #+begin_export latex
 \begin{equation}
 P_e = P_{e,50} \cdot \frac{f}{50}
 \end{equation}
 #+end_export
8. Perfil de irradiancia diaria (según IEC 61725):
 #+begin_export latex
 \begin{equation}
 G = G_{max} \cdot \cos\left(\frac{t}{t_0} \cdot \frac{\pi}{2}\right) \cdot \left[1 + s \cdot \left(1 - \cos\left(\frac{t}{t_0} \cdot \frac{\pi}{2}\right)\right)\right]
 \end{equation}
 #+end_export
 donde G es la irradiancia ($W/m^2$) en la hora $t$, $G_{max}$ es el valor máximo de irradiancia ($W/m^2$) dureante el día en cuestión, y $s$ es el facotor de forma definido por:
 #+begin_export latex
 \begin{equation}
 s = \frac{d \cdot \frac{\pi}{2} - 1}{1 - \frac{\pi}{4}}
 \end{equation}
 #+end_export
 siendo $d$ el factor de conjunto de datos calculado con:
 #+begin_export latex
 \begin{equation}
 d = \frac{G_d}{G_{max} \cdot h}
 \end{equation}
 #+end_export

* Sombras y ocupación de terreno
Al diseñar una central fotovoltaica se debe decidir la ubicación de las diferentes partes del generador resolviendo un compromiso entre la mejor ocupación del terreno disponible y la minimización del impacto de sombras mutuas arrojadas entre los módulos.

Este factor de sombras implica un nivel de ocupación de terreno que depende del modo de seguimiento del generador. La ocupación del terreno se puede medir con dos métricas:
- Relación de ocupación del terreno (/Ground Coverage Ratio/, $GCR$): es la relación entre el área del generador, $A_G$, y el área del terreno ocupado, $A_T$ (por tanto, siempre será GCR < 1). \nomenclature[AG]{$A_G$}{Área de un generador fotovoltáico} \nomenclature[GCR]{$GCR$}{Ground coverage ratio}
  #+begin_export latex
  \begin{equation}
  GCR = \frac{A_G}{A_T}
  \end{equation}
  #+end_export
- Ratio de ocupación del terreno ($ROT$, o /Ground Requirement Ratio/, $GRR$): es el inverso del GCR, la relación entre el área de terreno ocupado, $A_T$, y el área del generador, $A_G$. \nomenclature[ROT]{$ROT$}{Ratio de ocupación del terreno}
  #+begin_export latex
  \begin{equation}
  ROT = \frac{A_T}{A_G}
  \end{equation}
  #+end_export

** Sistemas estáticos
Las filas que componen el generador arojan sombras unas sobre otras en determinados momentos del días y año. Como recomendación general, es de uso común respetar un mínimo de 4 horas de sol en torno al mediodía del solsticio de invierno libres de sombra. La longitud de la sombra de un obstáculo se mide con:
#+begin_export latex
\begin{equation}
d = \frac{h}{tan\gamma_s}
\end{equation}
#+end_export
siendo $h$ la altura de la fila adyacente, $h=L\cdot sin(\beta)$ y $L$ la longitud del generador, según se indica en la figura ref:fig:sombras-estaticos.
#+CAPTION: Dimensiones y distancias entre filas de un sistema estático. label:fig:sombras-estaticos
file:figuras/SombrasEstaticas.pdf

En el mediodía del solsticio de invierno la altura solar es $\gamma_s = 90^\circ - 23.45^\circ - |\phi| \simeq 67^\circ - |\phi|$. Por tanto, la distancia mínima que permite 4 horas libres de sombra alrededor del mediodía es:
#+begin_export latex
\nomenclature[dmin]{$d_{min}$}{Distancia mínima entre hileras de un generador para evitar el sombreado}
#+end_export
#+begin_export latex
\begin{equation}
d_{min}=\frac{h}{tan(61^\circ - |\phi|)}
\end{equation}
#+end_export

** Sistemas de seguimiento a doble eje
El diseño de un sistema de seguimiento solar a doble eje busca optimizar la ubicación de los seguidores para minimizar las pérdidas de radiciación por sombras, utilizando eficientemente el terreno. Para esto, se simula el sistema en diferentes configuraciones y se elige la más eficiente en términos de productividad y ROT, que se calcucula con la fórmula:
#+begin_export latex
\begin{equation}
ROT = \frac{L_{ns}\cdot L_{eo}}{L\cdot W}
\end{equation}
#+end_export
donde (figuras ref:fig:sombras-doble y ref:fig:dimensiones-sombras-doble):
- $L_{ns}$ es la separación entre seguidores en la dirección Norte-Sur.
  #+begin_export latex
  \nomenclature[Lns]{$L_{ns}$}{Separación entre seguidores en sentido Norte-Sur}
  #+end_export
- $L_{eo}$ es la separación en la dirección Este-Oeste.
  #+begin_export latex
  \nomenclature[Leo]{$L_{eo}$}{Separación entre seguidores en sentido Este-Oeste}
  #+end_export
- $L$ es la longitud del seguidor.
- $W$ es la anchura del seguidor.

#+CAPTION:Sombras mutuas en un conjunto de cuatro seguidores. label:fig:sombras-doble
#+ATTR_LATEX: :height 0.2\textheight
file:figuras/Sombras2X.pdf
#+CAPTION:Dimensiones de un seguidor a doble eje y longitud de su sombra arrojada. label:fig:dimensiones-sombras-doble
#+ATTR_LATEX: :height 0.2\textheight
file:figuras/DimensionesSeguidorSombra.pdf
#+CAPTION:Posibles sombras en un conjunto de seis seguidores. label:fig:conjunto-seis-seguidores
#+ATTR_LATEX: :height 0.2\textheight
file:figuras/SixTrackerShadow.pdf

  
El sistema se modela como un grupo de seis seguidores en una matriz de dos filas en dirección Norte-Sur (figura ref:fig:conjunto-seis-seguidores), representando tres situaciones de sombra: lateral (Este-Oeste), frontal (Norte-Sur) y diagonal, caracterizados por los factores de sombra $FS_{xx}$, definidos como la relación entre el área sombreada y el área total del generador. Las ecuaciones para estos factores son, en las que se emplean los valores normalizados de las distancias, $l_{eo}=\frac{L_{eo}}{W}$ y $l_{ns}=\frac{L_{ns}}{W}$:
#+begin_export latex
\begin{equation}
\begin{array}{c}
|l_{eo}\cdot\cos(\psi_{s})|<1\\
|l_{eo}\cdot\sin(\psi_{s})|<s\end
{array}
\Rightarrow
FS_{eo}=\frac{(1-|l_{eo}\cos(\psi_{s})|)\cdot(s-|l_{eo}\sin(\psi_{s})|)}{s}
\end{equation}
\begin{equation}
\begin{array}{c}
|l_{ns}\cdot\cos(\psi_{s})|<s\\
|l_{ns}\cdot\sin(\psi_{s})|<1
\end{array}
\Rightarrow 
FS_{ns}=\frac{(s-|l_{ns}\cos(\psi_{s})|)\cdot(1-|l_{ns}\sin(\psi_{s})|)}{s}
\end{equation}
\begin{align*}
\begin{array}{c}
s>|l_{ns}\cdot\cos(\psi_{s})|+|l_{eo}\sin(\psi_{s})|\\
1>|l_{eo}\cdot\cos(\psi_{s})|-|l_{ns}\cdot\sin(\psi_{s})|
\end{array} 
& \Rightarrow
\end{align*}
\begin{equation}
FS_{d}=\frac{\left[s-\left(|l_{eo}\cdot\sin(\psi_{s})|+|l_{ns}\cos(\psi_{s})|\right)\right]\cdot\left[1-\left(|l_{eo}\cdot\cos(\psi_{s})|-|l_{ns}\sin(\psi_{s})|\right)\right]}{s}
\end{equation}
#+end_export
siendo $\psi_{s}$ el acimut solar y $\gamma_{s}$ la altura solar y donde la longitud de sombra (normalizada con la anchura del seguidor) se calcula con:
#+begin_export latex
\begin{align}
s & =s_{1}+s_{2}\\
s_{1} & =b\cdot\cos(\beta)\\
s_{2} & =\frac{b\cdot\sin(\beta)}{\vert\tan(\gamma_{s})\vert}
\end{align}
#+end_export
El factor $\frac{\sin(\gamma_{s})}{\sin(\gamma_{s}+\beta)}$ representa 
la proyección de sombra existente en el suelo sobre el plano del generador, y por tanto, el porcentaje de área sombreada que debe ser eliminado de la radiación directa. Desarrollando este factor se obtiene una formulación alternativa que puede facilitar el cálculo de los tres factores:
#+begin_export latex
\begin{align}
FS_{eo} & =\frac{(1-l_{eo}\cos(\psi_{s}))\cdot(s-l_{eo}\sin(\psi_{s}))}{s}\\
FS_{ns} & =\frac{(s-l_{ns}\cos(\psi_{s}))\cdot(1-l_{ns}\sin(\psi_{s}))}{s}\\
FS_{d} & =\frac{\left[s-\left(l_{eo}\cdot\sin(\psi_{s})+l_{ns}\cos(\psi_{s})\right)\right]\cdot\left[1-\left(l_{eo}\cdot\cos(\psi_{s})-l_{ns}\sin(\psi_{s})\right)\right]}{s}
\end{align}
#+end_export

Realizando la simulación de este sistema incluyendo el cálculo de sombras, y repitiendo la simulación para varias combinaciones (Lns, Leo) pueden elaborarse gráficos de nivel como el de la figura ref:fig:abaco-sombras, donde se recoge el ratio entre la energía anual producida por un seguidor /promedio/ incluyendo el efecto de por sombras mutuas[fn:5] y la energía anual producida por un seguidor sin sombreado.
#+CAPTION: Ábaco para planta de seguimiento a doble eje. Recoge el ratio entre la energía anual producida por un seguidor afectado por sombras mutuas ($E_{acS}$) y la producida por un seguidor sin sombreado ($E_{ac0}$). Las curvas de color negro representan la fracción de energía no afectada por sombras. Las curvas de puntos representan el valor del ROT. label:fig:abaco-sombras
#+ATTR_LATEX: :height 0.4\textheight
file:figuras/AbacoSombras.pdf

** Sistemas de seguimiento de eje horizontal
Se considera que los seguidores son de longitud infinita en sentido Norte-Sur (se desprecia el efecto de borde). Así, los parámetros que determinan el diseño de este tipo de sistema son (figura ref:fig:SeguidorEjeHorizontalSombras):
#+CAPTION: Dimensiones básicas en sistemas con seguidores de eje horizontal. label:fig:SeguidorEjeHorizontalSombras
#+ATTR_LATEX: :scale 0.9
file:figuras/SombrasHoriz.pdf
1. La inclinación del generador fotovoltaico, $\beta$, (coincidente con el ángulo $\psi_{ns}$).
2. La dimensión en sentido Este-Oeste del campo generador, L.
3. La separación entre los diferente seguidores en la dirección Este-Oeste, $L_{eo}$.
   Por tanto, $ROT=\frac{L_{eo}}{L}$.

Para caracterizar numéricamente el sombreado, se empreará el factor $FS_{eo}$. Mediante consideraciones geométricas, utilizando la distancia normalizada $l_{eo}=\frac{L_{eo}}{L}$, es posible escribir:
#+begin_export latex
\begin{align}
FS_{eo} & =\frac{s-l_{eo}}{s}\nonumber \\
 & =1-l_{eo}\cdot\cos(\beta)\nonumber \\
 &
 =1-l_{eo}\cdot\frac{\sin(\omega)}{\sqrt{\sin^{2}(\omega)+\left(\cos(\omega)\cos(\phi)+\tan(\delta)\sin(\phi)\right)^{2}}}\label{eq:FSeoHorizontal}
\end{align}
#+end_export

*** Limitación de ángulo y retroseguimeitno
En seguidores de eje horizontal se puede evitar la incidencia de sombras en cualquier en cualquier instante mediante algoritmos de /backtracking/ o retroseguimiento cite:Panico.Garvison.ea1991. Esta técnia provoca el desvío del seguidor de su posición óptima en los instantes en los que se produce la sombra entre seguidores, evitando el impacto de sombras pero con la consiguiente reducción en energía producida pro alejamiento del apuntamiento óptimo.

Para evitar la aparición de sombras, el ángulo de inclinación de los seguidores debe ser tal que la longitud de la sombra sea igual a la distancia entre seguidores. Siendo, $\beta$ el ángulo de inclinación con retroseguimiento, y, $\beta_0$ el ángulo de inclinación original, de la ecuación ref:eq:FSeoHorizontal se deduce que sólo será necesario aplicar esta técnica cuando $l_{eo}\cdot cos(\beta_0) \leq 1$. El triángulo definido por el rayo solar, el seguidro y la sombra debe cumplir la siguiente condición, basada en el teorema de los senos:
#+begin_export latex
\begin{equation}
\label{eq:BT_senos}
\frac{l_{eo}}{\cos(\beta_0-\beta)}=\frac{1}{\cos{\beta_0}}
\end{equation}
#+end_export

Por tanto, el ángulo de inclinación que grantiza la ausencia de sombras a costa de apartarse de la condición de seguimiento es:
#+begin_export latex
\begin{equation}
\label{eq:retroseguimiento}
\beta=\beta_0-\arccos(l_{eo}\cdot\cos{\beta_0})  
\end{equation}
#+end_export
ecuación que debe aplicarse sólo cuando $l_{eo} \cdot \cos(\beta_0) \leq 1$. En caso contrario $\beta = \beta_0$.







* Footnotes
[fn:5] En el cálculo de la producción del seguidor afectado por sombras mutuas se considera que la reducción en potencia está exclusivamente relacionada con el área sombreada, por tanto, no se tienen en cuenta las conexiones eléctricas entre módulos. 

[fn:1] Para las ecuaciones de este apartado se va a optar por poner la ecuación más simple posible. Sin embargo, el paquete =solaR2= otorga la posibilidad de realizar los cálculos de utilizando las ecuaciones propuestas por 4 autores diferentes.

[fn:2] Se van a utilizar las ecuaciones propuestas por P.I. Cooper [[cite:Cooper1969]] por su simpleza.

[fn:3] Relación entre el camino recorrido por los rayos directos del Sol a través de la atmósfera hasta la superficie receptora y el que recorrerían en caso de incidencia vertical ($AM=1/cos\theta_{zs}$).

[fn:4] Es de uso común añadir un asterisco como superíndice para denotar aquellos parámetros medidos en estas condiciones.
